### ISSUE TITLE
spelling mistake and update sorting system

### ISSUE THREAD

**Issue by AbdullahBinJahed** [LNReader/lnreader#100]
1. just a little spelling mistake in global sort
![IMG_20211031_140423](https://user-images.githubusercontent.com/39275638/139573988-d85ba694-3ef1-4622-abc4-5383e0549477.jpg)

2. when change chapter sorting of a novel it only changes for that particular novel ...
basically ... i like when 1st chapter is at the last and last chapter is on the top ... but change chapter sort for every novel is tedious so I'd like those changes to happen for every novel .... just like Tachiyomi
![IMG_20211031_140344](https://user-images.githubusercontent.com/39275638/139574045-317e28c3-a5b3-4d5d-9ccb-dc173dd8023a.jpg)

**Comment by AbdullahBinJahed** [comment]
@rajarsheechatterjee did you also fix the spelling mistake ?

**Comment by rajarsheechatterjee** [comment]
> @rajarsheechatterjee why not also fix the spelling mistake ?

Already fixed.

**Comment by AbdullahBinJahed** [comment]
> > @rajarsheechatterjee why not also fix the spelling mistake ?
> 
> Already fixed.

thanks ☺️
