### ISSUE TITLE
text in between <> will be displayed as nothing

### ISSUE THREAD

**Issue by ShalolaAuthor** [LNReader/lnreader#1005]
### Steps to reproduce

go to webview because i was flabbergasted why sometimes theres a word or two missing. turns out all the missing words are wrapped in <>.

### Expected behavior

if the original written as <Nebula>. it should not be omitted.

<>. i think the parser recognize this as html tags so thats why it is being omitted? 

### Actual behavior

from certain <Nebula>.

displayed as:
from certain .

### LNReader version

1.1.19

### Android version

Android 11

### Device

Tab S6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.19](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by ShalolaAuthor** [comment]
frustrated because it also happens in github i will now revert this what im saying with this >< instead of this <>.

>Nebula< is written. but it was omitted due to <>.

**Comment by ShalolaAuthor** [comment]
i think you guys get the point right?

**Comment by rajarsheechatterjee** [comment]
Could you provide an example of a novel and chapter along with the source where this issue can be reproduced?

**Comment by Inshal240** [comment]
Hello! I believe the OP is reading the same novel as me. Try "Omniscient Reader's Viewpoint", Chapter 388, the fourth paragraph:

[Nebula, <missing text>, has opened a portal that wil summon you].

Over here it showsup correctly:
https://www.lightnovelworld.com/novel/omniscient-readers-viewpoint-265/chapter-388

**Comment by Inshal240** [comment]
Perhaps we can sanitize the <> here:
https://github.com/LNReader/lnreader/blob/484c2b7e33fc4832b2d987c7f8a3dce74ef7b642/src/screens/reader/ReaderScreen.tsx#L298

Or there some special mark up to prevent it from reading it as html here:
https://github.com/LNReader/lnreader/blob/484c2b7e33fc4832b2d987c7f8a3dce74ef7b642/src/screens/reader/ReaderScreen.tsx#L346

Honestly, I don't have experience with app development at all so I'm very hesitant to touch the code myself. However, this will definitely improve the reading experience of this app as key character names are within those <>. I had thought it was an error in the translation for the past 50 or more chapters and now I feel like an idiot :c

**Comment by 1-minute-to-midnight** [comment]
Yes I also have this issue

**Comment by Palloxin** [comment]
```js
chapter = document.querySelector('chapter');
chapter.innerHTML = chapter.innerHTML
.replace(/<(\w+\b[\s\w’\']+)>/g, '&lt;$1&gt;');
```
Not a perfect solution but a lot of them should show with this..

**Comment by Palloxin** [comment]
Say the novel name and chapter
