### ISSUE TITLE
Readwn can't download

### ISSUE THREAD

**Issue by xiaxue-ys** [LNReader/lnreader#1006]
### Steps to reproduce

1. Can't download from apk
2. Can't read 
3. From WebView is fine

### Expected behavior

Can anyone fix it?

### Actual behavior

I want to download a novel but always error, then I try to read from apk but it display network error, so I try from WebView and it's normal 

### LNReader version

1.1.19

### Android version

13

### Device

Xiaomi Redmi 12c

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.19](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
