### ISSUE TITLE
pictures not downloaded

### ISSUE THREAD

**Issue by gyslo** [LNReader/lnreader#101]
![Screenshot_20211031_171628_com.rajarsheechatterjee.LNReader.jpg](https://user-images.githubusercontent.com/93453773/139592709-228579e0-7d35-4c25-a2c2-eb94ef69faa6.jpg)![Screenshot_20211031_171646_com.rajarsheechatterjee.LNReader.jpg](https://user-images.githubusercontent.com/93453773/139592724-555f1c33-f71e-410a-a09d-ffe3009852bb.jpg)![Screenshot_20211031_171650_com.rajarsheechatterjee.LNReader.jpg](https://user-images.githubusercontent.com/93453773/139592732-fe9a0815-c0f8-48da-84b4-d706c3d1c2e2.jpg)![Screenshot_20211031_171656_com.rajarsheechatterjee.LNReader.jpg](https://user-images.githubusercontent.com/93453773/139592741-180ae77f-2f6d-47a8-9d48-c48f4c421cdc.jpg)

**Comment by rajarsheechatterjee** [comment]
This is a source issue, open a issue [here](https://github.com/LNReader/lnreader-sources/issues/new?assignees=&labels=Bug&template=report_issue.yml).
