### ISSUE TITLE
Cloudfare Verification Failure

### ISSUE THREAD

**Issue by Perry-God** [LNReader/lnreader#1010]
### Steps to reproduce

1. Go to webview on a site with cloudfare, like foxaholic.
2. Try to complete Cloudfare verification.
3. Loads for a while, then failure.
4. Tried with VPN on and off, tried clearing cookies from the app, and the cache of the app itself, doesn't work.
5. App doesn't seem to let you change user agent, not sure if it would even help.

### Expected behavior

Enter webview
Complete Cloudfare verification
Success

### Actual behavior

Enter webview
Complete Cloudfare verification
Failure

### LNReader version

1.1.19

### Android version

Android 13

### Device

Samsung Galaxy A71

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.19](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment]
Any source which uses captcha don't work anymore I believe. The userAgent currently in use by 1.1.19 is being rejected. Based on user reports, this has affected
- lightnovelpub
- lightnovelworld
- foxaholic
- novel updates (accessing chapter links with captcha)
I recommend moving over to beta if this is important to you since it has a userAgent switcher.

**Comment by Perry-God** [comment]
Do you know if the backup will save chapters not yet turned into epub?  Can't seem to find that location.
