### ISSUE TITLE
Smooth AutoScroll

### ISSUE THREAD

**Issue by alex-dlgg** [LNReader/lnreader#1012]
### Describe your suggested feature

I love the autoscroll feature, but the jumps are jarring at times and its hard to keep up as my reading speed varies and there's no indication of when it will jump.
An option to make it scroll smoothly like movie credits would be greatly appreciated and make it so much easier to read in my opinion!!
Thanks!!!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
![Screenshot_20240716-160629](https://github.com/user-attachments/assets/a9d75c32-ad49-4cca-99d4-fd25228545fc)
You can customize autoscroll in settings -> reader -> auto scroll (visible when autoscroll is enabled)
