### ISSUE TITLE
add plugin manager in settings

### ISSUE THREAD

**Issue by AhmadNaruto** [LNReader/lnreader#1028]
### Describe your suggested feature

I hope this feature can be added, so that when creating or fixing plugins we no longer need to change the PluginManager.ts file and recompile the application to test plugin 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
You can run the website in plugin repo to test instead.
For app side test, you can build an apk which point to your own plugin dist branch

**Comment by AhmadNaruto** [comment]
what you say is very true and I do that too but it would be more practical if this feature existed. so we just add the address of the plugin.
