### ISSUE TITLE
TTS feature 

### ISSUE THREAD

**Issue by Karutovn** [LNReader/lnreader#1030]
### Describe your suggested feature

- Set tts language as plugin language (NOT system language)
- Save last tts readed
- auto go to next chapter on tts mode
- set tts as media player 
### Another feature 
- set app language in app

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Closing this since there are separate issues for each of the enhancements mentioned on the GitHub issue.
