### ISSUE TITLE
Cannot find export to epub option after the last update

### ISSUE THREAD

**Issue by INVI434** [LNReader/lnreader#1031]
### Steps to reproduce

1. Update to latest version(2.0.0)
2. Open a novel in your library
3. Click the download button

### Expected behavior

Export to epub option should be in the download drop-down menu

### Actual behavior

The option is not found

### LNReader version

2.0.0

### Android version

Android 12

### Device

Vivo 1938

### Other details

The option was available in the previous version, it only got messed up when I updated to the latest version 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CD-Z** [comment]
This is not a bug, the feature hasn't been implemented in the 2.0.0 version yet.

**Comment by INVI434** [comment]
> This is not a bug, the feature hasn't been implemented in the 2.0.0 version yet.

Is there a workaround until then?

**Comment by CD-Z** [comment]
The only one is to downgrade back to 1.1.19
