### ISSUE TITLE
Novel is not opening in Beta V2.0.0

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader#1032]
### Steps to reproduce

1. Open the Beta App
2. Add an extention or source
3. Click on the added source
4. Click on a novel 

### Expected behavior

It should show the cover page, description and chapters of the novel 

### Actual behavior

There is only a gray page is showing but if I go to home screen without closing the app and access the app again from recent tab it will show the novel

### LNReader version

2.0.0

### Android version

Android 11 

### Device

Realme 3 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
I am unable to reproduce this issue. The sources you are using may be experiencing slowdowns due to an issue on their end, or your internet connection may be slower, causing delays in displaying the novel details.

**Comment by Pheonix-Flames** [comment]
> I am unable to reproduce this issue. The sources you are using may be experiencing slowdowns due to an issue on their end, or your internet connection may be slower, causing delays in displaying the novel details.

I can send you a screen recording
