### ISSUE TITLE
Backup is not working in Beta V2.0.0

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader#1033]
### Steps to reproduce

1. Go to Settings > Backup > Restore Backup/ Restore Error
2. Select the migration file

### Expected behavior

It should start restoring the files saved in the backup 

### Actual behavior

It just gives an error notification with the number of novels

### LNReader version

2.0.0

### Android version

Android 11 

### Device

Realme 3 pro 

### Other details

I added few novels in the library and then create a new backup and then i reinstalled the beta 2.0.0 app and tried to Restore the backup i create using 2.0.0 but it shows the same error 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
This is working as expected. Make sure to install the plugins before restoring the Novels, or the process will fail.
