### ISSUE TITLE
The covers of light novels are not being updated.

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader#1038]
### Steps to reproduce

1. Restore a backup that includes novels with non-updated covers.
2. Open the backed-up novel from your library.
3. Access the novel in WebView to check if the cover has been updated on the website.
4. Close the WebView and refresh the novel to see if the cover has been updated within your library.

### Expected behavior

After refreshing, the novel cover should be updated to the latest one displayed in the WebView.

### Actual behavior

Even after refreshing, the novel cover remains unchanged. Furthermore, if the novel is migrated to a new source, it still retains the cover of the old novel source.

### LNReader version

2.0.0

### Android version

Android 11 

### Device

Realme 3 pro 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
Did you enable `refresh novel metadata` in settings?

**Comment by Pheonix-Flames** [comment]
> Did you enable `refresh novel metadata` in settings?

No

**Comment by nyagami** [comment]
You have to enable that option in settings to tell app updates novel metadata (cover, name... ), otherwise app only updates chapters
