### ISSUE TITLE
The search function is not working in some of the novel sources.

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader#1039]
### Steps to reproduce

1. Add plugins such as Wuxiacity, WuxiaMTL, FanNovel, and Wuxiap to your platform.
2. Open any of the mentioned plugins.
3. Use the search box at the top to search for something specific within the plugin.

### Expected behavior

The search function should display the search results based on the entered text in the search box within the plugin.

### Actual behavior

It doesn't do anything different and doesn't show any changes; it simply displays what is already shown on the homepage.

### LNReader version

2.0.0

### Android version

Android 11 

### Device

Realme 3 pro 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
