### ISSUE TITLE
Adjustable length for TTS pause 

### ISSUE THREAD

**Issue by Hhutilum** [LNReader/lnreader#1041]
### Describe your suggested feature

Since the last update it is now possible to start the TTS reader from anywhere within a given chapter which is a very nice feature.

However due to how it stops after every comma or period for 2 full seconds, it leads to many pauses and an awkward listening experience.

I would love to see a setting allowing us to either reduce the duration of pauses after TTS is done reading the bolded text or making it possible for the TTS reader to select and read full paragraphs in one fell swoop instead of fragmented sentences just like it had been able to prior to this app version.

https://streamable.com/zg1oje

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by sweetbbak** [comment]
If you go into the TTS settings inside of the stock Android settings app, you can adjust speed and pitch. See if that helps.

**Comment by Hhutilum** [comment]
> If you go into the TTS settings inside of the stock Android settings app, you can adjust speed and pitch. See if that helps.

It unfortunately doesn't help with the lengthy pauses.

**Comment by sthasam2** [comment]
Is it possible to auto switch to next chapter when tts for current chapter is completed?

If it's possible, having that option would be super neat.
