### ISSUE TITLE
The app adds a new entry to the history tab rather than updating the previous record.

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader#1053]
### Steps to reproduce

1. Open and read a novel from any source 
2. Read multiple pages
3. Check history tab 

### Expected behavior

It should show the last read chapter of the novel.
![Screenshot_2024-04-28-19-26-56-61_3c1c179116822eec69c21805387f0489](https://github.com/LNReader/lnreader/assets/105352597/db068744-4a1d-4ff8-81c3-e99994536882)

### Actual behavior

The app adds a new entry to the history tab rather than updating the previous record.
![Screenshot_2024-04-28-19-21-22-70_20a0a7b89aa33ffd9ff252f469dd0447](https://github.com/LNReader/lnreader/assets/105352597/a0b5dba9-adc9-454e-a6d2-e4409f48d877)

### LNReader version

2.0.0

### Android version

Android 11

### Device

Realme 3 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Palloxin** [comment]
Fixed in the super latest beta.

**Comment by nyagami** [comment]
Updated in https://github.com/LNReader/lnreader/pull/1052
