### ISSUE TITLE
Delay in Content Update During Loading Animation

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader#1058]
### Steps to reproduce

1. Open any novel source.
2. Scroll down until you encounter the loading animation.
3. Stop scrolling without reaching the end of the page, ensuring the loading animation is visible.
4. Notice that regardless of how long you wait, the subsequent content remains unchanged.
5. Scroll all the way down to the end of the loading animation to prompt an update of the following content.

### Expected behavior

If the feature were working correctly, the subsequent content should automatically update, similar to version 1.1.19.

### Actual behavior

Instead, it won't update the following content until the page is scrolled all the way down to the end of the loading animation.

https://github.com/LNReader/lnreader/assets/105352597/6e865c3e-8564-4b0d-9c50-d765170a2d58

### LNReader version

2.0.0

### Android version

Android 11 

### Device

Realme 3 Pro 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Pheonix-Flames** [comment]
Any updates

**Comment by rajarsheechatterjee** [comment]
@Pheonix-Flames This is an open-source project where anyone can contribute, and no one is obligated or paid to maintain it. If you need this implemented urgently, please feel free to contribute.

**Comment by Pheonix-Flames** [comment]
> @Pheonix-Flames This is an open-source project where anyone can contribute, and no one is obligated or paid to maintain it. If you need this implemented urgently, please feel free to contribute.

What should I learn if i want to contribute ?

**Comment by rajarsheechatterjee** [comment]
> What should I learn if i want to contribute ?

You can learn TypeScript and React Native.

**Comment by nyagami** [comment]
@CD-Z  is the tailing novel loading fixes this?

**Comment by CD-Z** [comment]
Yes, since I set bottomreached freshhold to 1.5. That means it already loads the next data before loading is even visible.

**Comment by nyagami** [comment]
Fixed by https://github.com/LNReader/lnreader/pull/1064
