### ISSUE TITLE
comrademao novel still chinese 

### ISSUE THREAD

**Issue by Dlordload** [LNReader/lnreader#106]
so comrademao chapters sometimes load Chinese chapters which refreshes? into English it doesn't seem to work in the app here's a link which loaded at least to mine a chinese chap it starts from c217 to the latest chap

https://comrademao.com/novel/mysterious-noble-beasts/

**Comment by rajarsheechatterjee** [comment]
The chapter gets translated by google translate as you scroll down, so it's not possible for the app to scrape the fully translated chapter.
