### ISSUE TITLE
Default Chapter Sort is not functioning properly 

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader#1060]
### Steps to reproduce

1. Open the app on your device.
2. Navigate to More > Settings > General > Default Chapter Sort.
3. Set the Default Chapter Sort to descending order.
4. Open a new novel from any source within the app.
5. Notice that despite the Default Chapter Sort being set to descending order, the chapters are sorted in ascending order by default.
6. Attempt to refresh the novel by swiping down on the screen.
7. Verify that even after refreshing, the novel's chapters remain sorted in ascending order.
8. Check the sorting option to confirm that the Default Chapter Sort is still set to descending order.
9. Manually change the displayed sorting order to ascending and then back to descending.
10. Observe that after this manual adjustment, the chapters are correctly sorted in descending order as per the Default Chapter Sort setting.

### Expected behavior

If the Default Chapter Sort feature were functioning correctly, setting it to descending order should ensure that when a new novel is opened, the chapters are automatically sorted in descending order. Refreshing the novel should maintain this descending order, and checking the sorting option should confirm the selected setting. Users would not need to manually adjust the sorting order, as the default setting would be accurately reflected without any additional steps.

### Actual behavior

Despite setting the Default Chapter Sort to descending order in 'More > Settings > General > Default Chapter Sort,' new novels are sorted in ascending order by default. Even after refreshing the novel or checking the sorting option, the default setting remains in descending order, yet the novels are displayed in ascending order. However, manually changing the displayed sorting order to ascending and then back to descending corrects the sorting, aligning the chapters in the desired descending order.

### LNReader version

2.0.0

### Android version

Android 11 

### Device

Realme 3 Pro 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Palloxin** [comment]
https://github.com/LNReader/lnreader/assets/75091899/ff01926b-7ca4-4caf-86a0-5e36eff7f3c4

**Comment by Pheonix-Flames** [comment]
Is it fixed ?
