### ISSUE TITLE
Optimizing Category Selection for Library Organization

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader#1062]
### Describe your suggested feature

1. **Direct Selection of Multiple Categories:** Users will have the ability to select multiple categories directly when clicking on the 'Add to Library' option in the novel page. This eliminates the automatic addition to the default category and gives users the flexibility to choose categories for their library.

2. **Category Modification:** Additionally, users can modify the categories of a novel by long-pressing the 'In Library' option on the novel page. This action opens the option to adjust the novel's categories as desired, offering further customization and organization options for the user's library.

I've categorized my novels into 5 categories: All, Reading, Plan To Read, Dropped, and Completed. When adding a novel to my library, the default is set to 'All,' automatically placing all novels in this category. However, this means that I have to manually add additional categories like 'Plan To Read' by long-pressing the 'In Library' option. Personally, this extra step for selecting multiple categories disrupts my user experience. Therefore, the suggested new feature would greatly improve this process.

### Other details

You can refer to how TachiyomiSY adds manga to their library as a reference. Their method aligns with my suggestion for adding novels to multiple categories in LNReader.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Palloxin** [comment]
Your features seem already present in beta and stable, except a way to get a direct(without long press) every time u click on "add to library"

**Comment by Pheonix-Flames** [comment]
> Your features seem already present in beta and stable, except a way to get a direct(without long press) every time u click on "add to library"
> 
> In the beta, the option that allows to choose the default category has been temporarly removed.

Which version ?

**Comment by rajarsheechatterjee** [comment]
Both of the requested features are already available in the stable version.

**Comment by Pheonix-Flames** [comment]
> Both of the requested features are already available in the stable version.

Link for beta version ?
