### ISSUE TITLE
Extension not working 

### ISSUE THREAD

**Issue by Honggyyy** [LNReader/lnreader#1077]
### Steps to reproduce

I was trying to add a certain novel using the novel updates extension but I can't seem to find the chapters of the novel it always show 0 chapter to any novel i searched. 
![Screenshot_20240523_133104](https://github.com/LNReader/lnreader/assets/170599933/f2b94da9-4f6a-4a16-a89a-9cc7a8be87b0)
![Screenshot_20240523_133118](https://github.com/LNReader/lnreader/assets/170599933/61c2e95c-b4fe-4db7-94ff-548718c31251)
![Screenshot_20240523_133129](https://github.com/LNReader/lnreader/assets/170599933/597184de-8733-4dea-9f2b-a7b405193cb3)

### Expected behavior

I expect to see the chapter that I'm able to access in the website. 

### Actual behavior

But what happened is the that I can search the story but the chapters are all missing. 

### LNReader version

2.0.0

### Android version

14

### Device

Vivo V29

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).

You need to login to NovelUpdates in WebView for chapters to show up.
