### ISSUE TITLE
Save previous read line

### ISSUE THREAD

**Issue by Karutovn** [LNReader/lnreader#1085]
I have any time to find last read on this chapter so can this app save last line i read on this chapter?

**Comment by nyagami** [comment]
What do you mean?
LNReader tracks your reading progress, so whenever you reopen that chapter, app scrolls to the last position.

**Comment by Karutovn** [comment]
> What do you mean?
> LNReader tracks your reading progress, so whenever you reopen that chapter, app scrolls to the last position.

Wait, I read some lightnovel but if I go out chapter and return it, it go to the top

**Comment by nyagami** [comment]
I think yu should try this [dev build](https://github.com/LNReader/lnreader/actions/runs/9266345221).
in 2.0.0, this  issue was resolved
