### ISSUE TITLE
Looping text-to-speech in dev build r944

### ISSUE THREAD

**Issue by Max762x39** [LNReader/lnreader#1086]
### Steps to reproduce

Select any chapter 
Play tts ( from the top or at least a paragraph before the end)

### Expected behavior

Whenever text-to-speech reaches the end of the chapter, it pauses reading or starts to the beginning of next chapter (if exists)

### Actual behavior

Tts begins back up from the top of the chapter, and this behavior repeats without end.

### LNReader version

2.0.0 beta-1 / dev build r944 + 2.0.0 beta - 2

### Android version

14

### Device

OPPO Reno 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by ichinel** [comment]
Also, the pause of TTS during comma "," is takes long.

**Comment by Max762x39** [comment]
This has already been solved by going to the r944 dev build. The comma issue wat the tts text splitter being punctuation. It is now the paragraph brackets "<p></p>" but the TTS doesn't end at the chapters end. See discord support posts
