### ISSUE TITLE
Add the text-to-speech button from 1.1.9 back on the top of chapters in 2.0.0

### ISSUE THREAD

**Issue by Max762x39** [LNReader/lnreader#1087]
### Describe your suggested feature

In previous lnreader versions, a very convenient button for starting tts "from chapter beginning" is located in the reader UI of all chapters, and is not ugly in the UI.
It's convenient because most users of the feature will begin tts from beginning, and will want to quickly and easily switch to next chapter before beginning tts from the top again.
Note that it's especially convenient if you like to use tts while doing other tasks (at wok, while gaming, driving... ) and not having to hold press all the time makes it easier to use.

### Other details

While not having a simple "1 tap button" for tts is inconvenient, the feature that lets you start from a chosen part needs to be kept. Although I don't really see a button for tts interfering with the current function.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
Im thinking about a bubble button (like messenger chat bubble). ofcourse no 1.1.19 tts button back
