### ISSUE TITLE
Plugin Specific CSS

### ISSUE THREAD

**Issue by Batorian** [LNReader/lnreader#1088]
### Describe your suggested feature

Currently all CSS is set through the app, which makes it difficult to add CSS which is needed for the chapter text from certain plugins to be displayed correctly. The idea is to introduce separate CSS files for each plugin to enable a more dynamic work environment.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by 1-minute-to-midnight** [comment]
Yes a major part of the novel I was reading was missing due to this. (Source: Genesis TL)

**Comment by Batorian** [comment]
> Yes a major part of the novel I was reading was missing due to this. (Source: Genesis TL)

Hey, I'd like you to use my [LNReaderTesting](https://github.com/Batorian/lnreader-app/actions/runs/9282302141#artifacts) if you want. Genisis TL is one of the plugins which should be fixed in my version. I'd appreciate feedback and any missing CSS you encounter.

**Comment by 1-minute-to-midnight** [comment]
I tried it out and I can't see the CSS elements. (I tried version 1.0.6 of the extension). The novel I tested on is named "The Main Heroines are Trying to Kill me". Chapter 3 (under "System, show clear privilege"). This is a very good novel to test on as this has a lot of custom CSS elements.

**Comment by Batorian** [comment]
> I tried it out and I can't see the CSS elements. (I tried version 1.0.6 of the extension). The novel I tested on is named "The Main Heroines are Trying to Kill me". Chapter 3 (under "System, show clear privilege"). This is a very good novel to test on as this has a lot of custom CSS elements.

Could you try the same novel and same chapter but under Novel Updates? I think I need to change some stuff in the Genesis TL plugin to make it work directly.

**Comment by Palloxin** [comment]
Since this will loose the sanitization, will it allow specific classes or all of them?

**Comment by Batorian** [comment]
> Since this will loose the sanitization, will it allow specific classes or all of them?

The plan is to have it only accept specific classes and their styles right now.

**Comment by 1-minute-to-midnight** [comment]
Yeah some elements are still missing in Genesis TL.

**Comment by Batorian** [comment]
> Yeah some elements are still missing in Genesis TL.

If you see missing elements, could you press F12 and tell me the class name of the element?

**Comment by 1-minute-to-midnight** [comment]
Here you go:
`<div class="game-prompt-gold-info-title ta-center">「Traits」</div>`

For reference, this is in a novel called "The Villain Who Robbed the Heroines" Chapter 2

**Comment by Batorian** [comment]
> Here you go: `<div class="game-prompt-gold-info-title ta-center">「Traits」</div>`
> 
> For reference, this is in a novel called "The Villain Who Robbed the Heroines" Chapter 2

![Screenshot_20240705-095709](https://github.com/LNReader/lnreader/assets/53831711/b4f1df71-b141-40b2-a58b-9fb2bb3e1f13)

Are you really using my app?

**Comment by 1-minute-to-midnight** [comment]
I haven't gotten the latest update yet

**Comment by nyagami** [comment]
Is this done with Plugin custom js/css feature?

**Comment by Batorian** [comment]
> Is this done with Plugin custom js/css feature?

Yeah, it is.

**Comment by nyagami** [comment]
Complete in https://github.com/LNReader/lnreader/commit/867b63af2241e0abb56dab89975441a648f2dde8
