### ISSUE TITLE
Freewebnovel site in ln reader is not loading and the novels in my library is not downloading 

### ISSUE THREAD

**Issue by Jabowockers** [LNReader/lnreader#1089]
### Steps to reproduce

![Screenshot_20240530-215608](https://github.com/LNReader/lnreader/assets/171260012/6ca7a6c1-3425-4001-b40f-903027745517)
![Screenshot_20240530-215624](https://github.com/LNReader/lnreader/assets/171260012/8dfdb296-709a-4415-bb12-7ca85c062604)

### Expected behavior

This should happen
![Screenshot_20240530-215854](https://github.com/LNReader/lnreader/assets/171260012/7f613afb-fa17-4ddf-bf96-71164b5a930b)

### Actual behavior

This happend instead 
![Screenshot_20240530-215624](https://github.com/LNReader/lnreader/assets/171260012/1bba7e16-fa5e-4e2b-a514-6283e30a8ba4)

### LNReader version

1.1.19

### Android version

Android 10

### Device

Infinix note 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by FoolishRaven** [comment]
Freewebnovel itself is down on the web, likely their long-awaited transition to libread. Likely not an issue with the app itself.

There is an issue in the sources repository predating 1.1.19 requesting the transfer, which was supposedly done? https://github.com/LNReader/lnreader-plugins/issues/655

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).

If the issue is still open, it has not been resolved yet.
