### ISSUE TITLE
Import Error: jin.xhtml: open failed: ENOENT (No such file or directory)

### ISSUE THREAD

**Issue by lalalasupa0** [LNReader/lnreader#1109]
### Steps to reproduce

Import epub

### Expected behavior

Should import it right

### Actual behavior

![Screenshot_20240618_140311_LNReader](https://github.com/LNReader/lnreader/assets/101371218/668eae2b-8315-4b11-830d-39c17d1d4d0c)

### LNReader version

2.0.0

### Android version

Android 12

### Device

Samsung S10+

### Other details

I have a SD Card memory, and it doesn't matter from where I select the file to import, if it's the same, still giving the same error, even the same file but from different sources

I've been looking for that jin.xhtml file it mentions but idk about it

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
could you provide the epub file?

**Comment by lalalasupa0** [comment]
https://files.catbox.moe/4jcwue.epup
Can't upload epubs here

**Comment by nyagami** [comment]
unable to access the link

**Comment by lalalasupa0** [comment]
> unable to access the link

https://www.mediafire.com/file/sdlbr5qnd6itg4t/The+Mythical+Hero's+Otherworld+Chronicles+-+Volume+05+[J-Novel+Club][Premium].epub/file

**Comment by lalalasupa0** [comment]
@nyagami 
Is it going to be implemented in a future updated? I'm asking just in case the beta of the app is being hosted in another place and can already be installed, maybe i'm actually in an old update lol (2.0.0)

**Comment by lalalasupa0** [comment]
> Only plugins updates can be delivered immediately. App updates required new installation. You can try the dev build here https://github.com/LNReader/lnreader/actions/runs/9693770711

I'm interested, but just to get the new stuff fastest.

Do you recommend installing that? I mean, coule there be data loss somehow or something?
