### ISSUE TITLE
[Bug] btn are not responsive

### ISSUE THREAD

**Issue by Mano5JP** [LNReader/lnreader#111]
Loved the app. UI is great too, 

Sometimes I find that buttons aren't responsive as a result I might need to double or triple-click.
See Video [Sample](https://imgur.com/a/vyxGAho).
This happens on both libraries and chapters filters too.

**Comment by SkillGG** [comment]
The button stops responding because the app is reloading the list.
It stops listening for everything else until it is done filtering the list.

**Comment by rajarsheechatterjee** [comment]
> Sometimes I find that buttons aren't responsive as a result I might need to double or triple-click.

This only happens on Samsung devices, taps don't get registered in bottomsheets.

**Comment by Mano5JP** [comment]
Oh!! Won't be switching phones so will stick to what's available right now.
