### ISSUE TITLE
Kolnovel new domain

### ISSUE THREAD

**Issue by kiraoussama** [LNReader/lnreader#1111]
### Steps to reproduce

Kolnovel changed there domain

### Expected behavior

Changed domain

### Actual behavior

https://kolbook.xyz/

### LNReader version

Stable 2.0.0

### Android version

Android 14

### Device

Oppo Reno 11

### Other details

New domain 
https://kolbook.xyz/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by hamzaal7ref** [comment]
I have the same issue i don't know how to read

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
