### ISSUE TITLE
kolnovel domain got changed

### ISSUE THREAD

**Issue by kiraoussama** [LNReader/lnreader#1116]
### Steps to reproduce

kolnovel still got the old domain

### Expected behavior

change the domain please

### Actual behavior

there still old domain

### LNReader version

Stable 2.0.0

### Android version

Android 14

### Device

Oppo Reno 11

### Other details

nothing really

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).

**Comment by kiraoussama** [comment]
ooooh ok
