### ISSUE TITLE
[Feature Request] continuous vertical reading

### ISSUE THREAD

**Issue by Mano5JP** [LNReader/lnreader#112]
please add continuous vertical reading, this will greatly make the reading experience much better.

I do have gesture enable So, I do use swipe gestures but, sometimes there are accidental swipes.

Disabling the gesture is the worst experience, as now you need extra steps to need to be done to go prev/next chapter.

Personally, I believe that having continuous vertical reading would be ideal.

**Comment by earthmonkey0** [comment]
I'd love to have this feature, I am new to the repo but will give it a try soon!

**Comment by shivamsbatra** [comment]
hope this feature gets implemented soon. 🤞
