### ISSUE TITLE
Dev build: Not getting chapters

### ISSUE THREAD

**Issue by lalalasupa0** [LNReader/lnreader#1121]
### Steps to reproduce

Import epub
Mine: https://www.mediafire.com/file/op7hhylpa8111na/Date_A_Live_Volume_22_-_Tohka_Good_End_Second_Half.epub/file

### Expected behavior

Should load chapters

### Actual behavior

![Screenshot_20240628_050416_LNReader](https://github.com/LNReader/lnreader/assets/101371218/d07cfeef-8b86-4cf1-a234-6ef9aba70cc8)

### LNReader version

Github Action 2.0.0 (27/06/24 09:05 AM UTC) Commit: 9b4bdfea

### Android version

Android 12

### Device

Samsung S10+

### Other details

Using [this](https://github.com/LNReader/lnreader/actions/runs/9693770711) build

No descriptions either

I opened the file with moon reader and it seems to be fine, I didn't navigate too much because it could spoil the series for me

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
`[Tittle here]` is the actual title of that epub.

**Comment by lalalasupa0** [comment]
> `[Tittle here]` is the actual title of that epub.

Oh, deamn, you're right lol
