### ISSUE TITLE
Words within <> brackets are not rendered in the app despite being visible in web view

### ISSUE THREAD

**Issue by plainboyyy** [LNReader/lnreader#1123]
### Steps to reproduce

I have noticed that words are missing entirely from the text and when compared to the webpage it can be deducted that anything written with <> will not be displayed, nor the brackets.

### Expected behavior

Web page displays the following text:
"[Fables from Nebula < Hongik > are observing < Kim Dokja's Company >!]"
![Screenshot_20240630-170132](https://github.com/LNReader/lnreader/assets/113251107/7007e9e0-2aa7-4fac-9205-6e77f1d0a098)

### Actual behavior

Text displayed in the reader:
"[Fables from Nebula are observing !]"
![Screenshot_20240630-170230](https://github.com/LNReader/lnreader/assets/113251107/79aa3b75-5928-406e-86ff-424eee4ddd0c)

### LNReader version

2.0.0

### Android version

Android 14

### Device

Nothing Phone (1)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by elfing44** [comment]
The issue has already been fixed.
I think this is what resolves it: #1049 
The fix will be available in an upcoming release.

![image](https://github.com/LNReader/lnreader/assets/106489440/5e93864e-0fef-4aef-acae-f62324f932db)

**Comment by plainboyyy** [comment]
Any idea when this release will be rolled out?

**Comment by Quiksmage** [comment]
Same, one of the LNs I'm reading is super affected by this.

**Comment by rajarsheechatterjee** [comment]
Closing this issue as it should be resolved in the [_v2.0.0-beta.2_](https://github.com/LNReader/lnreader/releases/tag/v2.0.0-beta.2) release.
