### ISSUE TITLE
Dev build: Crash with repository "plugins.min.json" on "Available" page

### ISSUE THREAD

**Issue by lalalasupa0** [LNReader/lnreader#1125]
### Steps to reproduce

Open repositories setting
Add `https://raw.githubusercontent.com/lnreader/lnreader-plugins/plugins/v2.0.0/.dist/plugins.min.json` (I believe the url is okay, following what it says [here](https://github.com/LNReader/lnreader-plugins?tab=readme-ov-file#via-an-app) 
Go to 'Browse' and then 'Available'
Update 'Available' page

### Expected behavior

Should show the plugins ig

### Actual behavior

App crashes

### LNReader version

Github Action 2.0.0 (29/06/24 08:44 PM UTC) Commit: b67d6f80

### Android version

Android 12

### Device

Samsung S10+

### Other details

https://github.com/LNReader/lnreader/assets/101371218/c5df6dbd-f0f2-49db-a3df-9587cb0165f7

It happens even if I have one or two languages selected btw

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
That dev build is not compatible with plugin repo version 2.0.
You have to use plugin repo v3+. 
Official repo: https://lnreader.github.io/plugins
