### ISSUE TITLE
[Featured Request] Google Translate

### ISSUE THREAD

**Issue by fourthavenue** [LNReader/lnreader#113]
Hi Developers,

Thank you for this app, it makes reading easier. I hope that you can add a feature where in chinese sites can be translated automatic via google translate even if it's raw file so it will be much easier reaf without going to the web view and have the google translate app to automatically ask for translate. Hope you can incorporate it in the system where in you just have to click a certain button and it will translate it into english. kindly add as well https://m.sobiquge.com/ as well on the list of resources. thanks and more power.

**Comment by rajarsheechatterjee** [comment]
Google's translate API is paid and as this app is completely free I am not making any money so I can't implement it.

For source request, open a issue in [sources repo](https://github.com/LNReader/lnreader-sources/issues/new/choose).
