### ISSUE TITLE
Can refresh the updates...

### ISSUE THREAD

**Issue by TonyRaj02** [LNReader/lnreader#1136]
When I tried to refresh the updates section for new updated chapter.but the apps is getting stopped directly.please resolve the issue

**Comment by error7404** [comment]
What is your version number and what are the sources you are using, and can you send screenshots

**Comment by TonyRaj02** [comment]
Yes I am using 1.1.19
Sources are -
Novelfull
Boxnovel
Allnovelfull
Novel buddy
Freewebnovel
Novelhall
MTL novel
Ranobes
Fastnovel
Novelbin

**Comment by error7404** [comment]
Try the beta

**Comment by TonyRaj02** [comment]
![Screenshot_2024-07-12-22-50-43-79_3c1c179116822eec69c21805387f0489.jpg](https://github.com/user-attachments/assets/f85fcca3-7484-4f19-a757-7c7e54bb07d2)

See after downloading beta when I tried to download sources but is does not show any sources please help me with it

**Comment by Cohinem** [comment]
Please read the [release notes ](https://github.com/LNReader/lnreader/releases)

**Comment by rajarsheechatterjee** [comment]
Closing this issue as it is likely due to a specific source breaking in _v1.1.19_. I suggest continuing to use the beta version, as it will be the next stable release and is actively maintained.
