### ISSUE TITLE
[Bug] Delete Download Chapters

### ISSUE THREAD

**Issue by Mano5JP** [LNReader/lnreader#114]
I am using the Download Option for offline uses.

I have encountered that when I am reading a series while I am connected to Wi-Fi; Chapters that were downloaded and I have read are deleted, even though there is no option to delete chapters when marked as read.

But While I am Offline and read the downloaded chapters it won't delete the chapter that was read.

**Comment by rajarsheechatterjee** [comment]
I can't reproduce it. Can you share a screen recording?

**Comment by Mano5JP** [comment]
I just tried to replicate the steps but, i could not reproduce it again.

Maybe it happens randomly or i caught it accidentally. 

Couldn't reproduce so, you may close this one.
