### ISSUE TITLE
Option for speech speed selection

### ISSUE THREAD

**Issue by sthasam2** [LNReader/lnreader#1141]
### Describe your suggested feature

Previously, in 1.x when the app used the System TTS we could configure the speech and pitch via the system TTS settings.

![Screenshot_2024-07-13-19-54-56-151_com android settings-edit](https://github.com/user-attachments/assets/8907b4ab-75b8-40ec-ab10-b677d2fb083a)

After 2.x and the inclusion of the highly anticipated voice selection option, it seems we can't alter said Speed and Pitch even when we select the System Voice. 

![Screenshot_2024-07-13-19-56-03-736_com rajarsheechatterjee LNReader-edit](https://github.com/user-attachments/assets/5f2e04ff-02f9-452a-a647-49789c3ba01a)

Is it possible to implement this speed functionality, or is there a chance I might be doing something wrong and the configuration for speed could be done?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
Done in https://github.com/LNReader/lnreader/commit/19ce7da32e2a05a463cd94f3faa25136e71a569e
