### ISSUE TITLE
Dot alignment does not work in Arabic (._.)

### ISSUE THREAD

**Issue by Rekodo** [LNReader/lnreader#1145]
Hi 
Please add HTML View button in the application to align points at the end of dialogues in Arabic.
 After version 1.14, the dots were no longer aligned after the end of words in the Arabic language. I tried to modify the application myself, but I could not😅😭
![Picsart_24-07-16_14-54-02-341](https://github.com/user-attachments/assets/c5f905b3-4cc4-49ac-a238-f370a6cd8706)
 Please help and add a solution so I can enjoy reading
![Picsart_24-07-16_14-50-15-649](https://github.com/user-attachments/assets/c14412e9-801c-491c-adea-7256deba49c3)

**Comment by error7404** [comment]
it's a known issue with RTL languages, the current fix is to apply a custom CSS to the text as mentioned in https://github.com/LNReader/lnreader-plugins/issues/959
```CSS
* {
   direction: rtl; 
}
```
(if it doesn't work try to go to beta 2.0)

**Comment by Rekodo** [comment]
thank you soo much it work♥️♥️♥️
