### ISSUE TITLE
Make New TTS Context Menu Optional

### ISSUE THREAD

**Issue by pro-nav** [LNReader/lnreader#1147]
### Describe your suggested feature

The recently added context menu in the app includes Text-to-Speech (TTS) functionality but removes the default system context menu, which typically contains the "Define <word>" function and extensions for Google and other dictionary apps. Since I rarely use Text-to-Speech, I would prefer to retain my default context menu actions. Please make the new context menu optional.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Palloxin** [comment]
It would be better if tts could be disabled completely (so tts buttons too), and with it its custom context menu.
-tts OFF(default): just like 1.1.19 with default context menu and no tts buttons near progress bar
-tts ON: custom context menu and tts buttons
Everybody happy
