### ISSUE TITLE
Incorrect Padding when disabling Full Screen 

### ISSUE THREAD

**Issue by Batorian** [LNReader/lnreader#1148]
### Steps to reproduce

- disable full screen mode

### Expected behavior

- adjusted padding after disabling full screen mode

### Actual behavior

- notice the padding not changing and words disappearing at the top of the chapter

### LNReader version

2.0.0-beta.2

### Android version

Android 14 (latest)

### Device

Google Pixel 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by WGmg23** [comment]
yea
