### ISSUE TITLE
page order

### ISSUE THREAD

**Issue by WGmg23** [LNReader/lnreader#1151]
### Describe your suggested feature

![Screenshot_2024-07-17-23-14-22-041_com rajarsheechatterjee LNReader](https://github.com/user-attachments/assets/71a00ed4-958a-485c-aa0a-a88f89e47181)
![Screenshot_2024-07-17-23-14-32-628_com rajarsheechatterjee LNReader](https://github.com/user-attachments/assets/c4bc5046-bad3-4a45-b22e-515a1052c831)

some extensions like these have the lasts chapters in page 1 and recent chapters in last page(example:18) add an option in app or for extensions to revert page order

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Ideally, all plugins should have chapters starting from page 1. 

Please open separate issues in the [lnreader-plugin](https://github.com/LNReader/lnreader-plugins) repository for each plugin that has chapters in reverse order.
