### ISSUE TITLE
Can't view available aources

### ISSUE THREAD

**Issue by Remielas** [LNReader/lnreader#1154]
### Steps to reproduce

1. Open Lnreader
2. Go to available source 

### Expected behavior

This will then show the list of ready to download source 

### Actual behavior

But it just shows blank, even after several refreshes and reboot

### LNReader version

2.0.0-beta 1

### Android version

Android 13

### Device

Techno Spark 20

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
You need to upgrade to _v2.0.0-beta.2_. 

Plugins are no longer pre-installed in the app, so you'll need to add a plugin repository. Refer to the changelog for the steps to add one.
