### ISSUE TITLE
Ranobes extension stopped working 

### ISSUE THREAD

**Issue by x-tj** [LNReader/lnreader#1156]
### Steps to reproduce

Update app to latest beta version
Open ranobes extension
Shows error
![Screenshot_2024-07-19-20-48-46-797_com rajarsheechatterjee LNReader](https://github.com/user-attachments/assets/93e9d310-d2ac-4ce1-a8b6-3a7e10f22719)

### Expected behavior

Should show novels

### Actual behavior

Shows error
![Screenshot_2024-07-19-20-48-46-797_com rajarsheechatterjee LNReader](https://github.com/user-attachments/assets/9995a595-2f32-48f4-b8c0-6aac3f8100a5)

### LNReader version

2.0.0 - beta.2

### Android version

13

### Device

Redmi Note 10S

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
remove the plugin and add it again

**Comment by x-tj** [comment]
Removed the plugin  but when i try to re add it. Its not showing up 
![Screenshot_2024-07-19-21-10-48-849_com rajarsheechatterjee LNReader](https://github.com/user-attachments/assets/171b87e9-6b99-4bb5-bb39-b16ce625abce)

**Comment by nyagami** [comment]
https://lnreader.github.io/plugins
click button then reload the available tab

**Comment by x-tj** [comment]
My bad . It's fixed now. Thanks for help
