### ISSUE TITLE
custom js causing bug

### ISSUE THREAD

**Issue by WGmg23** [LNReader/lnreader#1159]
### Steps to reproduce

download app from github actions
use custom js 

### Expected behavior

works

### Actual behavior

When you use custom JS and enter to read a chapter, the menu does not appear and only the tts works and if you use the option to move from page by page (experiment) it only shows the current page and only shows (1/1) below

### LNReader version

2.0.0

### Android version

13

### Device

Redmi 10c

### Other details

...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CD-Z** [comment]
This seems to be happening since your custom js code throws an error. Please provide your code

**Comment by Palloxin** [comment]
I know his problem.
It's about the "dialogue highlighter" snippet bugging the reader after the commit 19ce7da3 (beta, nyagami)
```js
const regex = /[\"“”](?<!\=\")(?!>|\s?[\"“”])([^\"“”]+?)(<br>[^\"“”]+)?[\"”](?<!=\")/g;
const colorElement = (x) => {
    x.innerHTML = x.innerHTML
		.replace(regex, `"<ww>$1$2</ww>"`)
		.replace(/[\u2033]/, '\"');
};
(col = (parent) => {
    if (parent.nodeName === "SCRIPT") return;
    const childsWith = [...parent.children].filter((ch) =>
        /[\"“”]/.exec(ch.innerText)
    );
    if (!childsWith.length) colorElement(parent);
    else childsWith.forEach((ch) => col(ch));
})(document.querySelector("chapter"));
```

**Comment by rajarsheechatterjee** [comment]
It should be the other way around, with the Custom JS written to complement the app's JS. If it broke due to a recent commit, please update your Custom JS accordingly.
