### ISSUE TITLE
Royalroad reading issue

### ISSUE THREAD

**Issue by mskomek** [LNReader/lnreader#1163]
### Steps to reproduce

Read world reader novel link: https://www.royalroad.com/fiction/7509/world-keeper

### Expected behavior

Read properly

### Actual behavior

Empty screen
![Screenshot_20240725-223458_LNReader](https://github.com/user-attachments/assets/86f84010-1bae-45c0-a225-e7ee3ed8e779)
![Screenshot_20240725-223507_LNReader](https://github.com/user-attachments/assets/3ca5ecef-47fd-408c-9ee0-e5cf86ff7034)
![Screenshot_20240725-223515_LNReader](https://github.com/user-attachments/assets/d5fdd8b2-9aaf-4849-8682-5140477ad529)
![Screenshot_20240725-223528_LNReader](https://github.com/user-attachments/assets/ae1a962a-f857-4c44-8801-675332607ec8)

### LNReader version

2.0.0

### Android version

12

### Device

Galaxy note 10+ Samsung

### Other details

Thank you best regards

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
