### ISSUE TITLE
Plugin For A New Website

### ISSUE THREAD

**Issue by darker-than-black-69** [LNReader/lnreader#1165]
I don't know how it works, but someone said to make an issue. I wanted this website in LNRedaer : https://helscans.org/

**Comment by B3H3M0T** [comment]
You request at wrong page bro go to source page for plugin request.

**Comment by darker-than-black-69** [comment]
> You request at wrong page bro go to source page for plugin request.

Sorry, I am new to GitHub but thanks

**Comment by error7404** [comment]
Btw helscans should be available through novel update
