### ISSUE TITLE
Save progress in backups

### ISSUE THREAD

**Issue by OMNITHORN** [LNReader/lnreader#1167]
### Describe your suggested feature

If someone creates a backup of their library when the backup is restored it should retain progress in their books, for example: let's say I created a backup of a novel and i read 984 chapters when i restore the backup my progress should still be saved. (I lost the progress of alot of webnovels because i though the backups saved chapters progress)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CD-Z** [comment]
This is already the case since 2.0.0. All 1.x versions as well as the legacy backup don't support it.

**Comment by OMNITHORN** [comment]
Thank you.
