### ISSUE TITLE
Hello can someone add one novel website to this app? The website is https://mydramanovel.com/ its a request 

### ISSUE THREAD

**Issue by Aruraka** [LNReader/lnreader#1175]
### Describe your suggested feature

https://mydramanovel.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Cohinem** [comment]
"If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose)."
