### ISSUE TITLE
Tidak ada bab di BACA LIGHT NOVEL

### ISSUE THREAD

**Issue by Qiskdbwob** [LNReader/lnreader#1177]
### Steps to reproduce

1.klik sebuah novel acak di BACA LIGHT NOVEL
2.pada saat ada di halaman tersebut 
3.bab novel tidak ditemukan "tidak dapat mengurai halaman"

### Expected behavior

Seharus nya ada bab novel yang tersedia sedangkan itu tidak di temukan bab novel

### Actual behavior

Tidak dapat mengurai halaman

### LNReader version

2.0.0

### Android version

Android 12

### Device

Galaxy A02s

### Other details

tidak dapat mengurai halaman, tidak ada bab, 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).

Additionally, please create issues in English since there are no Indonesian contributors.
