### ISSUE TITLE
Menunda agak lama

### ISSUE THREAD

**Issue by Qiskdbwob** [LNReader/lnreader#1178]
### Steps to reproduce

1.saya mengunduh bab novel
2. menelusuri novel lain
3. Mengklik novel
4. Jeda terlalu lama 

https://github.com/user-attachments/assets/bd79b313-fa22-4cf4-aa2b-68e5a34b1de7

### Expected behavior

Ketika tidak ada kegiatan latar belakang mengunduh bab, ini normal tidak ada jeda terlalu lama 

### Actual behavior

Jeda terlalu lama ketika ada kegiatan latar belakang mengunduh bab novel

### LNReader version

2.0.0

### Android version

Android 12

### Device

Galaxy A02s

### Other details

Ya meskipun tidak masalah bagi saya, saya harap ini dapat di perbaiki

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
This has always been the behavior because background actions are resource-intensive operations, and there isn't a direct fix for this issue.

Additionally, please create issues in English, as there are no Indonesian contributors.

**Comment by Qiskdbwob** [comment]
> ### Steps to reproduce
> 1.I downloaded the novel chapter 2.browsing other novels 3.clicking on the novel 4. Pause is too long
> 
>  floatee-video-1722770539520_8ByCJvXG.mp4 
> ### Expected behavior
> When there is no background activity downloading chapters, it is normal that there is no too long pause
> 
> ### Actual behavior
> Too long pause when there are background activities downloading novel chapters
> 
> ### LNReader version
> 2.0.0
> 
> ### Android version
> Android 12
> 
> ### Device
> Galaxy A02s
> 
> ### Other details
> Yes even though it doesn't matter to me, I hope this can be fixed
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
> * [x]  I have written a short but informative title.
> * [x]  If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
> * [x]  I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
> * [x]  I will fill out all of the requested information in this form.

**Comment by Qiskdbwob** [comment]
Ok,thank you
