### ISSUE TITLE
Is there a way to add a Novel website

### ISSUE THREAD

**Issue by Rekodo** [LNReader/lnreader#1179]
Hi. 
Is there a way to add a Novel website to the application via Termux for example؟.
I want to add a Novel website and renew it myself.
Is there a simple way to work with it?
(●_●)

**Comment by rajarsheechatterjee** [comment]
Plugins are simply basic JS scripts containing the scraping logic. There's a contributing guide available in the README of the [lnreader-plugins](https://github.com/LNReader/lnreader-plugins/blob/master/README.md) repo. The application used to write the script is not important.
