### ISSUE TITLE
Restore is not working properly 

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader#1182]
### Steps to reproduce

1. Create a Backup
2. Clear app data
3. Restore the backup 

### Expected behavior

It should restore all the Novels in the backup with their category and read and unread chapters 

### Actual behavior

Only Novels are restored but their catagory and the number of read and unread chapters are not restored. All the restore Novel have their all chapters unread. This is the same as 1.1.19

### LNReader version

LNReader v2.0.0-beta.2

### Android version

Android 11 

### Device

Realme 3 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment]
this is why it's called "create backup (deprecated)" you should be using google drive backup or self host if you want everything to be backed up

**Comment by rajarsheechatterjee** [comment]
This is expected since the older Backup creation didn't support it. For a more detailed backup, use a Self Hosted or Google Drive backup option.
