### ISSUE TITLE
Loading animation is not showing 

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader#1183]
### Steps to reproduce

1. Go to Browse
2. Click on a novel 

### Expected behavior

It should show a loading animation 

### Actual behavior

A blank display is showing 

https://github.com/user-attachments/assets/129f4eef-852f-452c-b07a-d04c0ee5b3d4

### LNReader version

LNReader v2.0.0-beta.2

### Android version

Android 11 

### Device

Realme 3 pro 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Pheonix-Flames** [comment]
Any updates?

**Comment by Palloxin** [comment]
The problem started with this build 
https://github.com/LNReader/lnreader/actions/runs/9823188607
So this commit 5262567 made by @nyagami

**Comment by hamunoz** [comment]
Any update?

**Comment by Palloxin** [comment]
https://github.com/user-attachments/assets/4db1e638-38f7-4a96-b0e3-6c687e88fafe

Not fixed
