### ISSUE TITLE
select and translate problem.

### ISSUE THREAD

**Issue by MJ933** [LNReader/lnreader#1189]
### Steps to reproduce

when i was able to select any text and then it show me a menu to chose if i can translate it using Google translator but now it not working in this new beta it was work correctly in the 1.1.19.

### Expected behavior

.

### Actual behavior

.

### LNReader version

2.0.0 

### Android version

android 13

### Device

Xiaomi pad 5

### Other details

when i was able to select any text and then it show me a menu to chose if i can translate it using Google translator but now it not working in this new beta it was work correctly in the 1.1.19.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Palloxin** [comment]
The custom context menu has been removed. Wait for Beta3
