### ISSUE TITLE
Chapters in branches are not displayed

### ISSUE THREAD

**Issue by Farori** [LNReader/lnreader#1191]
### Steps to reproduce

open [Власть книжного червя (Новелла)](https://ranobelib.me/ru/book/6689--ascendance-of-a-bookworm-novel?section=chapters)

### Expected behavior

show chapter 1 of branch one when branch one is opened.
show chapter 1 of branch two when branch two is opened.

### Actual behavior

Chapter 1 is only available in one of the two branches.
Chapter 1 will not be displayed in the other branch.

### LNReader version

v2.0.0-beta.2

### Android version

Android 13

### Device

moto 20 pro

### Other details

lnreader-plugins RanobeLib 2.0.1
[lnreader-plugins/ranobelib.ts](https://github.com/LNReader/lnreader-plugins/blob/master/src/plugins/russian/ranobelib.ts) I don't practice TypeScript and haven't tested the code, but the code does work with branches. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
