### ISSUE TITLE
[Font Request] Josefin Sans

### ISSUE THREAD

**Issue by Quackified** [LNReader/lnreader#120]
I would like to request a font to be added in the app its called Josefin Sans. The source is in Google Font API, Thank You.

**Comment by rajarsheechatterjee** [comment]
1. Turn on Use WebView in reader bottom sheet.

2. Go to More > Settings > Reader Settings and past this in custom css and save.

```
@import url('https://fonts.googleapis.com/css2?family=Josefin+Sans&display=swap');

* {
    font-family: 'Josefin Sans', sans-serif;
}
```
