### ISSUE TITLE
Add a speed toggle for the TTS voice

### ISSUE THREAD

**Issue by Gylsera** [LNReader/lnreader#1201]
### Describe your suggested feature

Tye default speed for the TTS here is slow for me and adding a speech rate speed toggle/slider would be very nice

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
It was added. 
You can wait for next release or try a dev build from github actions

**Comment by Gylsera** [comment]
oh, I'll check it out when it's out then, thank you!
