### ISSUE TITLE
Missing German Translations

### ISSUE THREAD

**Issue by Batorian** [LNReader/lnreader#1204]
### Steps to reproduce

1. Just missing in general at some places

### Expected behavior

1. Expected German translations

### Actual behavior

1. No translations provided

### LNReader version

2.0.0-beta.2

### Android version

Android 14

### Device

Google Pixel 7

### Other details

Reminder to check this out when available.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
it is not a bug, you can raise a PR for adding translations.
