### ISSUE TITLE
Certain Symbols and/or Text Not Showing

### ISSUE THREAD

**Issue by NAGEQUIT** [LNReader/lnreader#1227]
### Steps to reproduce

![Screenshot_20240821-171156](https://github.com/user-attachments/assets/2c3bfb3b-445b-44c6-9d84-db425e5d4abb)
![Screenshot_20240821-171223](https://github.com/user-attachments/assets/da0577bb-46ce-4e0b-ba11-11c64e91291c)

### Expected behavior

The text should be showing on the reader.

### Actual behavior

Specific Symbols and/or Text does not show.

### LNReader version

2.0.0-beta.2

### Android version

Android 14

### Device

Nothing Phone (2)

### Other details

I have texted with other sources and the issue is the same.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CheshireCat27** [comment]
Fixed, issue can be closed.
