### ISSUE TITLE
Updated information doesn't stick

### ISSUE THREAD

**Issue by glitch-m0de** [LNReader/lnreader#1231]
### Steps to reproduce

1. Open any novel
2. Try editing any of the fields
3. Novel screen shows the edited information
4. Go back to the library and the information isn't updated
5. Clicking the same novel shows the outdated information

### Expected behavior

It should show the updated information.

### Actual behavior

It doesn't show the updated information.

https://github.com/user-attachments/assets/f80c3514-6e45-4142-b517-ef6dd5d18f21

### LNReader version

2.0.0 beta 2

### Android version

Android 14

### Device

Oppo Reno 8 5G

### Other details

I don't know if this bug is because I have updated the app to this [build](https://github.com/LNReader/lnreader/actions/runs/10493343791) since it was working fine on the stable version of v2.0.0 beta 2. I have also tried doing this on a novel from another source and the same thing happens, so I'm assuming it's an app issue rather than a source one. Let me know if there's anything I'm missing or if this is a genuine bug, thanks!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Palloxin** [comment]
Fixed, if someone can close it
