### ISSUE TITLE
Missing .env file

### ISSUE THREAD

**Issue by cmmaio** [LNReader/lnreader#1236]
### Steps to reproduce

![image](https://github.com/user-attachments/assets/6c7ff4af-7c9a-477d-ada1-ca511de09135)

### Expected behavior

Should compile successfully. I have the correct jdk and node versions installed as well as android studio + sdk installed. Followed build instructions in contributing and resulted in this error.

### Actual behavior

Gives the error shown in image

### LNReader version

Source

### Android version

N/A

### Device

Windows 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment]
create an empty .env file

**Comment by cmmaio** [comment]
> create an empty .env file

Thanks but now i get the 
'.' is not recognized as an internal or external command,
operable program or batch file.
error. Is there any other requirements i need?

**Comment by error7404** [comment]
what command are you running? and what operating system are you using?
(if you want more info for compilation don't forget to join the discord https://discord.gg/QdcWN4MD63)

**Comment by nyagami** [comment]
change buildRelease in package.json file to
`"buildRelease": "node scripts/setEnvFile.cjs Release && cd android && gradlew clean && gradlew assembleRelease"`

**Comment by cmmaio** [comment]
Thank you both for the help finally managed to get it built
