### ISSUE TITLE
Status bar

### ISSUE THREAD

**Issue by Kartik-dev72** [LNReader/lnreader#1247]
### Describe your suggested feature

More features or customisation options for status bar (like make it resizable or more options like chapter no., etc).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Could you provide more details about the feature request? It's not entirely clear to me what is expected.

**Comment by Kartik-dev72** [comment]
> Could you provide more details about the feature request? It's not entirely clear to me what is expected.

At the bottom of screen, where the battery% and reading progress is present, I hope there would be more customisations to it because it has much potential.
