### ISSUE TITLE
New update 2.0.0 beta 2, how to add plugins.

### ISSUE THREAD

**Issue by Boosolomon** [LNReader/lnreader#1252]
### Steps to reproduce

So I installed the new version but I did not know it didn't support plugins 

### Expected behavior

now I do not know how to add them or use the repository functions. 

### Actual behavior

Please help

### LNReader version

2.0.0 beta 2

### Android version

android 11

### Device

s24

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment]
https://lnreader.github.io/plugins

**Comment by Konuchi** [comment]
Attempting to add that results in a message saying "Repository URL is invalid".

**Comment by rajarsheechatterjee** [comment]
You need to open the above URL, and there should be a button to add the repository directly in the app. This is also mentioned in the changelog of the new release.
