### ISSUE TITLE
Sleep lockscreen not turnoff while AFK

### ISSUE THREAD

**Issue by B3H3M0T** [LNReader/lnreader#1253]
### Steps to reproduce

Read like normaly you do and left behind your phone.

### Expected behavior

Lockscreen sleep not activate or we can say screen always on, make battery will drain more  when not used.

### Actual behavior

Screen always on until it died out

### LNReader version

V2 beta 2

### Android version

Android 13

### Device

Xiaomi Poco f3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Palloxin** [comment]
https://github.com/LNReader/lnreader/issues/835
This would help many for the reason you just described.

**Comment by rajarsheechatterjee** [comment]
We've already merged a commit to add an option to toggle 'Keep Screen On.' You can switch to a build from GitHub Actions if you want to try it out. It should be included in the next release.

**Comment by B3H3M0T** [comment]
Thx alot bro and update tabs will be fixed too? Because it was bugged to betweens updated meta and updated chapter. And updated meta always fill today update..
