### ISSUE TITLE
Problem no writing in chapter

### ISSUE THREAD

**Issue by Kayan877** [LNReader/lnreader#1256]
### Steps to reproduce

![Screenshot_20240925-204943_LNReader](https://github.com/user-attachments/assets/d41ea010-d875-4f8f-8563-98bb04356b6c)

### Expected behavior

There should be a writing in that chapter 

### Actual behavior

Instead it doesn't display anything 

### LNReader version

2.0.0.beta 2

### Android version

Android 11

### Device

Samsung galaxy A03s

### Other details

Source name : SakuraNovel.id

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
