### ISSUE TITLE
Novel bin is not working 

### ISSUE THREAD

**Issue by ChaosReturn** [LNReader/lnreader#1270]
### Steps to reproduce

Step 1: Open novel bin from sources.
Step 2: open any novel.
Issue: no novel name and chapters are displayed.

### Expected behavior

Novel name and chapters are displayed 

### Actual behavior

No novel name and chapters are displayed 

### LNReader version

2.0.0

### Android version

Android 12

### Device

Redmi k50i

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
