### ISSUE TITLE
Request Source: Wuxiaspot

### ISSUE THREAD

**Issue by hamunoz** [LNReader/lnreader#1277]
### Describe your suggested feature

Hello
Source : https://www.wuxiaspot.com/
Thx

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment]
- [x] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
