### ISSUE TITLE
Website not converting backup correctly

### ISSUE THREAD

**Issue by prithveemishra** [LNReader/lnreader#1278]
### Steps to reproduce

Goto your conversion url-
https://lnreader.github.io/guides/upgrade

Upload my file
[lnreader_backup_2024-10-15_03_51.json](https://github.com/user-attachments/files/17370034/lnreader_backup_2024-10-15_03_51.json)
You get this file- 
[migrated-backup.json](https://github.com/user-attachments/files/17370035/migrated-backup.json)
Also added converted file. 

### Expected behavior

Expected behaviour is, the new file to be around comparable size, ime. 69kb. And contain all the novel's, not just 3.

### Actual behavior

The website to convert backup from 1.1.19 to 2.0.0 is not converting my backup file correctly.
I have more than 50 novels in the back but the converted version has just 3 novels (which is visible by the size as well, 69 kb old backup file turns into 2kb new backup file).
You can reproduce it by uploading my file 

### LNReader version

2.0.0 beta 2

### Android version

Android 14

### Device

POCO X6 PRO

### Other details

This is not a device or app's problem. It's the conversion tool's bug. Please email me if there is any update or resolution. Much appreciated, thanks.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Not all plugins that were available in the stable version are present in the beta. Either they haven't been implemented yet, or the websites they rely on no longer work. 

Could you check if the novels that aren't present have their respective plugins available in the beta?

**Comment by prithveemishra** [comment]
Hi, thanks for a prompt reply. 
I have checked, the plugins are available, most of my novels were from the source AllNovelFull. And it has been installed. Infact i even tried to load the backup after installing all the plugins, but still it just ends after 3 novels. 
You can also load my backup in old version to verify the source, it is present in the new version as well.

**Comment by prithveemishra** [comment]
@rajarsheechatterjee Hey guys, are you working on this? Would love to get some updates on this. Thanks for your hardwork.

**Comment by nyagami** [comment]
upload your backup file here or in our discrod server

**Comment by prithveemishra** [comment]
Hi @nyagami , i have uploaded my backup file in the original post. Re-attaching these-

My file for old version with all 50+novels +-
[lnreader_backup_2024-10-15_03_51.json](https://github.com/user-attachments/files/17435928/lnreader_backup_2024-10-15_03_51.json)

My file after using your link for new version with just 3 novels-
[migrated-backup.json](https://github.com/user-attachments/files/17435931/migrated-backup.json)

Thank you for looking into this.

**Comment by nyagami** [comment]
allnovelfull.com has changed to allnovelfull.net
I pushed the fix, reload your page and try again

**Comment by prithveemishra** [comment]
Hey @nyagami , it worked. Thanks for the quick fix.
