### ISSUE TITLE
Riwayat domain change 

### ISSUE THREAD

**Issue by Mingo3347** [LNReader/lnreader#1280]
### Steps to reproduce

Site domain changed 

### Expected behavior

Latest domain

### Actual behavior

Captcha error

### LNReader version

2.0.0

### Android version

Android 11

### Device

Samsung a70 

### Other details

cenele.com
https://cenele.com

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
