### ISSUE TITLE
Locked Chapters on webnovel source not complete

### ISSUE THREAD

**Issue by NKJibu02** [LNReader/lnreader#1281]
### Steps to reproduce

Open app
Enter webnovel sources
Search some paid novel
Downloaded it all
Open the locked chapter
Half of the chapter contents are available 

### Expected behavior

Full content is expected to show

### Actual behavior

Half chapter content

### LNReader version

2.0.0

### Android version

Android 10

### Device

Infinix hot 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).

Do you expect the app to display content from locked chapters that you haven’t paid for?

**Comment by lunyx** [comment]
How do you authenticate with a source?  I have a paid subscription but can't seem to find anywhere to log in to a source.

**Comment by K1ngfish3r** [comment]
are you able to log in to webview? swipe a novel to the right and find the globe icon

**Comment by lunyx** [comment]
> The lock symbol will persist, however you should still be able to read the full chapter. You can remove the novel from your library, go to settings > advanced > clear cached novels and add the novel again, then the lock icon will be gone. Also I think it doesn't work to automatically buy new chapters.

I tried this and saw that it disappeared from my reading history, but the chapter still seems to be cached.  I also tried clearing the app cache in the android settings, but still doesn't work.  Checked in browser again and confirmed that I can access the entire chapter while logged in.

**Comment by CD-Z** [comment]
And you haven't downloaded the chapter

**Comment by lunyx** [comment]
Correct, the download icon is still available next to it (not the check mark).

**Comment by CD-Z** [comment]
Could you try an older beta version of the app, since it should work and does on my device. However I am using a version between beta 2 and 3.

**Comment by lunyx** [comment]
> Could you try an older beta version of the app, since it should work and does on my device. However I am using a version between beta 2 and 3.

I could.  Does the backup feature save my library, reading progress, and all my settings?  The warning on the download page implies that old ones don't but new ones do, though there's nothing anywhere that I can find on what it actually backs up.
