### ISSUE TITLE
Add Change User Agent

### ISSUE THREAD

**Issue by ChriszZ8** [LNReader/lnreader#1284]
### Describe your suggested feature

Add feature change user agent to unlock clodflare high protection.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
Already added in v2 app

**Comment by ChriszZ8** [comment]
Private ? When public release
