### ISSUE TITLE
Back up not restoring chapter progress

### ISSUE THREAD

**Issue by forr34** [LNReader/lnreader#1285]
### Steps to reproduce

i went back from version 2.00 to 1.18
i tried to backup using my old files
it didn't restore chapter progress

### Expected behavior

i thought if you back up it will also restore the chapter progress 

### Actual behavior

i have over 160 novels it all resetted to chapter 1 

### LNReader version

1.18

### Android version

Android 12

### Device

Samsung S10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CD-Z** [comment]
First why did you go back to 1.1.18, the latest not 2 version is 1.1.19.

Second the legacy backup, that is used by 1.1.19 and below can only restore the novels and not the progress. Full backups are only supported for the backups not marked as deprecated in 2.0 and up.

**Comment by rajarsheechatterjee** [comment]
This is the expected behavior, as chapter progress was not included in the backup. This was addressed in version 2.0.0 beta with Google Drive/remote server backup.

**Comment by sriwijaya572** [comment]
I was careless when doing the installation to ver 2 beta 3

Now all my novel from version 1.19 disappeared

Is there a way to recover it?
I have backup, but not covering New added novel @rajarsheechatterjee

Please
