### ISSUE TITLE
morenovel, sakura and Some sources Indonesia language novel is eror plisss fix this

### ISSUE THREAD

**Issue by YunYing288** [LNReader/lnreader#1286]
### Steps to reproduce

![Screenshot_2024-10-17-03-43-32-659_com rajarsheechatterjee LNReader](https://github.com/user-attachments/assets/d12eafcf-7c8b-43db-89f6-baba070819eb)
![Screenshot_2024-10-17-03-39-16-458_com rajarsheechatterjee LNReader](https://github.com/user-attachments/assets/0f30985a-97ea-42ef-b4f8-286f59f7c8b0)

### Expected behavior

As usual they are crazy, please fix it, I beg you as soon as possible, what I attached is just a little bit of a problem

### Actual behavior

Atas

### LNReader version

2.0.0

### Android version

Android 11

### Device

Redmi note 8

### Other details

Just fix this, plisss :3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
