### ISSUE TITLE
Only one of the arabic sources work

### ISSUE THREAD

**Issue by MKVCDY** [LNReader/lnreader#1289]
### Steps to reproduce

The sources load but chapters are empty but it works on the website 

### Expected behavior

Please fix it i love your app if you don't have time please just fix kolnovels it's the only Arabic reliable  source

### Actual behavior

It loads but all the chapters are empty

### LNReader version

The latest

### Android version

The latest

### Device

S22 ultra

### Other details

Please fix it i can't go for another day without novels

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment]
- [ ] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).

**Comment by error7404** [comment]
Btw there is already a PR open to fix it
