### ISSUE TITLE
Sources update

### ISSUE THREAD

**Issue by Darkmasterx2** [LNReader/lnreader#1293]
### Steps to reproduce

So basically the Arabic language sources has no updates and the links of them are changing a lot so basically non of them are working cause the url has changed and can't access them on app for example the arnonovel this one has changed the link and can't be updated cause there is no manual option for updating it 

### Expected behavior

There should be a tracker to automatically update the link in the source after its change or an option to modify it by yourself 

### Actual behavior

There is nothing to update the old sources 

### LNReader version

2.0.0

### Android version

Android 12

### Device

Vivo y20

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
