### ISSUE TITLE
Nav-bar in web

### ISSUE THREAD

**Issue by VectorNEON** [LNReader/lnreader#1301]
### Steps to reproduce

Just go to any resource on the web where the navigation is at the bottom, for example ranobelib
In this case, the nav-bar must be turned on (if there is an option on the phone).
In the screenshot I gave an example of how this is implemented in Tachiyomi and LnReader
![лн](https://github.com/user-attachments/assets/82f7d19a-3745-44f3-a391-84873f37159a)

### Expected behavior

When the nav-bar is active on the web, the page should adjust and rise without blocking the view, like Tachiyomi, which I gave as an example in the screenshot above.

### Actual behavior

In LnReader, the web nav-bar closes the navigation

### LNReader version

2.0.0

### Android version

Android 10

### Device

Realme C11 (2020)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
Ye, the webview is missing padding bottom for window insets
