### ISSUE TITLE
Will the export to EPUB feature come back in the newest update?

### ISSUE THREAD

**Issue by Perry-God** [LNReader/lnreader#1309]
### Describe your suggested feature

The feature existed in 1.1.19 but got removed in 1.1.20.  Would it be possible to add it back?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
next beta version

**Comment by nyagami** [comment]
Available in Beta3
