### ISSUE TITLE
no illustrations

### ISSUE THREAD

**Issue by VectorNEON** [LNReader/lnreader#1313]
### Steps to reproduce

The program does not see illustrations on some short stories.
When viewing online and downloading they are not there, but if you look through the web there are illustrations
Here is a link to the chapter for example - https://ranobelib.me/ru/39562--otonari-no-tenshi-sama-ni-itsu-no-ma-ni-ka-dame-ningen-ni-sareteita-ken- wn/read/v7/c0.1?ui=2555856
![image](https://github.com/user-attachments/assets/15781330-15be-494f-803e-17325d50a2f5)
![image](https://github.com/user-attachments/assets/61bab3f3-83d4-48ac-bc32-4ba002c2ca5a)

### Expected behavior

So that the illustrations are visible

### Actual behavior

The program doesn't see them.

### LNReader version

2.0.0

### Android version

Android 10

### Device

Realme C11 (2020)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
Duplicated of https://github.com/LNReader/lnreader/issues/1298
You can download the latest apk from https://github.com/LNReader/lnreader/actions/runs/11705198378

**Comment by VectorNEON** [comment]
> You can download the latest apk from

So the problem is different, it does not show that there is a loading error, the program simply does not see them.
And I downloaded the latest build 1035, it’s the same there.
There is a different error here than there was before.
Yes, and on the extreme ones there is still a problem with the chapters, but I already wrote about this earlier in another report.

**Comment by rajarsheechatterjee** [comment]
Illustrations are loading fine for me in the latest build. You’ll need to delete the previously downloaded chapters for them to appear.

**Comment by VectorNEON** [comment]
> Illustrations are loading fine for me in the latest build. You’ll need to delete the previously downloaded chapters for them to appear.

This does not happen in all chapters, and I gave an example for a specific chapter where the problem occurs
I even posted a link to this chapter.

**Comment by rajarsheechatterjee** [comment]
> This does not happen in all chapters, and I gave an example for a specific chapter where the problem occurs
> I even posted a link to this chapter.

I checked the link, and the illustrations are loading fine for me.

**Comment by VectorNEON** [comment]
> > This does not happen in all chapters, and I gave an example for a specific chapter where the problem occurs
> > I even posted a link to this chapter.
> 
> I checked the link, and the illustrations are loading fine for me.

It’s strange, I don’t have any illustrations online or even after downloading the chapter, I even reinstalled the plugin. Visible only on the Web

**Comment by VectorNEON** [comment]
> ![Screenshot_20241106-222911.png](https://private-user-images.githubusercontent.com/86464880/383621487-4bf454f1-8884-4ab3-8405-f8b6836d5c4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MDczNzEsIm5iZiI6MTczMDkwNzA3MSwicGF0aCI6Ii84NjQ2NDg4MC8zODM2MjE0ODctNGJmNDU0ZjEtODg4NC00YWIzLTg0MDUtZjhiNjgzNmQ1YzRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDE1MzExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwYmI4ZDljMzA2OWM1MGQzYmM2M2RjZDg0MzUwMWQ1MGU5MDA3Y2QzZmU2OTgxNjgxZjA3Mzc1Zjc1ZDkyZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yliMU-gDFVorE9_8ioIdSub1WG-EN2sp_Pg6eaXixcg)
> 
> Reinstall the plugin, clear cookies, webview data then try again

Already did and even reinstalled the program completely, but no changes

**Comment by Palloxin** [comment]
https://github.com/user-attachments/assets/51b6eee5-d723-4dbe-885e-ee656a2aa46b

**Comment by VectorNEON** [comment]
> YouCut_20241106_170118364.mp4

Unfortunately, for some reason I don’t have it even after downloading the chapter, I tried everything: reinstalling the program and plugin, and even via VPN, I don’t understand what the problem is.😢

**Comment by Palloxin** [comment]
```js
chapter = document.querySelector('chapter');
chapter.innerText = chapter.outerHTML
```
Settings=>Reader=>custom js
paste this and screemshot the chapter

**Comment by nyagami** [comment]
show your app version in `more -> about -> version`

**Comment by VectorNEON** [comment]
> show your app version in `more -> about -> version`

![image](https://github.com/user-attachments/assets/467b8eb0-8330-47b5-a462-6d913e109eb0)

**Comment by VectorNEON** [comment]
> ```js
> chapter = document.querySelector('chapter');
> chapter.innerText = chapter.outerHTML
> ```
> 
> Settings=>Reader=>custom js paste the code and screemshot the chapter

Nothing happened, or maybe I’m doing something wrong, although I seem to have done everything correctly.

**Comment by nyagami** [comment]
Oh wait, it looked like the internet is slow, just wait for 2-5 mins

**Comment by VectorNEON** [comment]
> Oh wait, it looked like the internet is slow, just wait for 2-5 mins

Already did it
Yes, and I doubt it, because then it’s strange that even after downloading the chapters they are not there, although they should be there in any case.
Yes, and in other chapters it works fine, on volume 5 0.1 chapters there are no problems, for example.
on volumes 6 and 7, chapters 0.1 are empty, although there are illustrations there - it works somehow strangely.

**Comment by Palloxin** [comment]
come to the server of LNReader

**Comment by VectorNEON** [comment]
[2024-11-07-13-13-16.txt](https://github.com/user-attachments/files/17659873/2024-11-07-13-13-16.txt)
log
