### ISSUE TITLE
ranobehub stopped working

### ISSUE THREAD

**Issue by VectorNEON** [LNReader/lnreader#1319]
### Steps to reproduce

Just open any chapter of any work on ranobehub
![image](https://github.com/user-attachments/assets/2b8fc6ce-a7fc-4092-ada9-4e212e9bd533)

### Expected behavior

Normal chapter opening

### Actual behavior

We see a box with “Enable endless chapter feed” and “Hide message”
![image](https://github.com/user-attachments/assets/af8106c9-3078-4c53-ac08-665af0a385b5)

### LNReader version

2.0.0

### Android version

Android 10

### Device

Realme C11 (2020)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
