### ISSUE TITLE
Nav-bar hides the "Tracking" form

### ISSUE THREAD

**Issue by VectorNEON** [LNReader/lnreader#1322]
### Steps to reproduce

When the Nav-bar is active and Tracking is enabled, the nav-bar covers the Tracking form and you have to lift it every time to see everything.
![353453](https://github.com/user-attachments/assets/ed7c0c7a-c44c-4237-9e90-94c85b89ade4)

### Expected behavior

So that the "Tracking" form is automatically at the nav-bar level if it is enabled.

### Actual behavior

Nav-bar closes the "Tracking" form
The screenshot above shows the problem.

### LNReader version

2.0.0

### Android version

Android 10

### Device

Realme C11 (2020)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by vvirtues** [comment]
same on gesture navigation
