### ISSUE TITLE
Chapters are blank/empty

### ISSUE THREAD

**Issue by Mudblood2001** [LNReader/lnreader#1323]
### Steps to reproduce

1.Open the novel
2. Click the chapter
3. It says that if the chapters are available on webview report on github

### Expected behavior

![Screenshot_20241114_172047](https://github.com/user-attachments/assets/3798b0ff-b473-4387-82a0-47d0df6bb859)

### Actual behavior

![Screenshot_20241114_172017](https://github.com/user-attachments/assets/12cb3754-2c39-431a-8b96-30778b7c0846)

### LNReader version

2.0.0

### Android version

Android 12

### Device

Vivo y20

### Other details

It's shows the chapters in webview . The issue is on novel bin extension

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
