### ISSUE TITLE
Most Arabic sources do not work

### ISSUE THREAD

**Issue by abdogabal** [LNReader/lnreader#1324]
### Steps to reproduce

kolnovel, riwyet,arnovel don't work 
kolnovel show this whenever i open any chapter 
![Screenshot_٢٠٢٤١١١٥_١١٤٦٢٨_LNReader](https://github.com/user-attachments/assets/b9ae6a3d-9370-4b70-aa78-9265e6466b70)

### Expected behavior

To open the chapter normally

### Actual behavior

The source is broken or changed

### LNReader version

1.1.19

### Android version

14

### Device

Samsung A24

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment]
- [ ] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).

Please update to version 2.0

**Comment by abdogabal** [comment]
Ok I will do that but the problem with version 2.0.0 is that it doesn't show any source and it looks a bit buggy in design so I always go back to the offical version instead of the beta until the official version of the next version is released
![Screenshot_٢٠٢٤١١١٥_١٤٣٨٠٠_LNReader](https://github.com/user-attachments/assets/96b9d03f-6a8f-4086-9f64-c0a113f1e7ea)
![Screenshot_٢٠٢٤١١١٥_١٤٣٨٠٦_LNReader](https://github.com/user-attachments/assets/df31e289-b4b2-42e0-980b-230586c556db)
![Screenshot_٢٠٢٤١١١٥_١٤٣٨٠٩_LNReader](https://github.com/user-attachments/assets/11b6ecef-2dc4-46c3-92c3-2418b19dcc6b)

**Comment by CD-Z** [comment]
As the people working on this app do it just for fun or for features they want themself we don't have the man power to also support the "main" version. So these problems won't be fixed.

**Comment by abdogabal** [comment]
Thank you this helped a lot and also thank you for your work I really appreciate it and I didn't mean to pressure you or bother you

**Comment by nyagami** [comment]
LNReader ver 2 has plugin system works like Tachi/Mihon extensions. 
Go to https://lnreader.github.io/plugins to add repo and reload the available tab.
