### ISSUE TITLE
[Feature request] Disable option for Browse badge

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#1343]
### Describe your suggested feature

An option to disable badges here:
![Screenshot1](https://github.com/user-attachments/assets/7297c682-8c72-454f-ae95-3f47cc3a8bd5)

Nothing much, i prefer to not see it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Palloxin** [comment]
I do want the updates avaiable (avaiable), just... not the annoying badge.
ingand removing the repo is annoying, ss well as the visual presence of the badge.
If an user goes to settings just to disable it, why not?

**Comment by Soopyboo32** [comment]
maybe it makes more sense to add an update all button / autoupdate plugins setting

**Comment by Palloxin** [comment]
It's like a program constanly harassing you to update its version, everyday. I want to know it's there, but don't be annoying everyday. Even you used (or still use) Java 15 node 18. Why not latest? 
In this case it's the visual badge, that's all.

Here an example, maybe to empatize:

https://github.com/user-attachments/assets/81131f68-73ed-4220-82f6-d2a377fa07ad

Can you re-open the issue?

**Comment by nyagami** [comment]
React Native always complains why not upgrade to the latest whenever devs start app in dev mode
