### ISSUE TITLE
Novel bin. Chapter is empty 

### ISSUE THREAD

**Issue by ChaosReturn** [LNReader/lnreader#1345]
### Steps to reproduce

Step 1:Open novel bin
Step 2:Open any novel (eg:Strongest Superhuman System chapter 1)
Step 3: Chapter will show empty 

### Expected behavior

Chapter should be shown 

### Actual behavior

Most chapters of most novels are empty 

### LNReader version

2.0.0

### Android version

Android 12 

### Device

Redmi k50i

### Other details

There were other issues related to it. But it's showing closed and the issue is still ongoing.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MrVantes** [comment]
> **Reproduced the issue:**  
> Steps followed:  
> 1. Opened **LNReader 2.0.0** on Android 13 (Device: Redmi Note 10 Pro).  
> 2. Opened the **"Strongest Superhuman System Chapter 1"**  and **"Shadow Slave chapter 3"** novel.
> 3. The chapter page displayed as "Chapter is empty".
> 4. Opened the webview for Novelbin,  **"Strongest Superhuman System Chapter 1"**  and **"Shadow Slave chapter 3"** both are present.
>  
> Additional findings:  
> - The issue occurs with multiple chapters from different novels, not just "Strongest Superhuman System".  
> - The source chapter is available in webview.  
> - Tried clearing the app cache. The issue persists.
>  
> It seems like the chapters are not loading properly across several titles. This might be related to an app bug.  
>
> Please let me know if you need more information to help resolve this!

**Comment by error7404** [comment]
- [ ] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-plugins).

Please open your issue in the right repository

**Comment by ChaosReturn** [comment]
I am still having this issue in novel bin.
