### ISSUE TITLE
Issue in Fetching details from MLTNovels

### ISSUE THREAD

**Issue by prathikprajapati** [LNReader/lnreader#1352]
### Steps to reproduce

Add any novel from the MLTNovel extension 
After being added to your library the cover image and the all the details and content gets blank

The content is available in web view 

### Expected behavior

After adding the novel to library it's cover page and the title to be showed
And content to be loaded when chapter is opened 

### Actual behavior

The cover page is missing/null
Title is Null
Chapter after fetching is Null

### LNReader version

Stable 1.1.19

### Android version

11

### Device

Redmi Note 8 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MrVantes** [comment]
> * [ ]  If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-plugins).
> 
> Please open your issue in the right repository and make sure to not create duplicate issues.

**Comment by prathikprajapati** [comment]
Thanks for  the info,
I will change it.

Prathik Prajapati
