### ISSUE TITLE
EPUBs from Fenrir Translations getting "window.pubfuturetag"

### ISSUE THREAD

**Issue by lalalasupa0** [LNReader/lnreader#1358]
### Steps to reproduce

Open source "Fenrir Translations"
Download chapters
Click epub icon and save it somewhere
Open a chapter

### Expected behavior

The chapter should only have the text showed in the same LNReader

### Actual behavior

All chapters start this way:
`window.pubfuturetag = window.pubfuturetag || [];window.pubfuturetag.push({unit: "663dd6d999cc415993a26925", id: "pf-8982-1"})
`
`Chapter 1: <from here onwards all seems alright>`

### LNReader version

54a3feb

### Android version

11

### Device

Motorola One 5G

### Other details

That window.pubfuturetag thing doesn't appear when opening a chapter in LNReader

It appears where on the website are ads, like

[ad] gets replaced with [window.pubfuturetag]

I confirmed that when I got this other thing:
`window.pubfuturetag = window.pubfuturetag || [];window.pubfuturetag.push({unit: "663f070a99cc415993a37135", id: "pf-8990-1"})`

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MrVantes** [comment]
> > * [ ]   If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-plugins).
> > 
> > Please open your issue in the right repository and make sure to not create duplicate issues.

**Comment by lalalasupa0** [comment]
> > * [ ]    If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-plugins).
> > 
> Please open your issue in the right repository and make sure to not create duplicate issues.

Since it's a thing with the epub maker itself, I thought it would be more conventional to report it here as it's related to the core of the app, and it may not only happen with that extension too
I do wonder if I should open this there tho

**Comment by lalalasupa0** [comment]
> Since the issue appears to stem from the source content, it doesn’t seem to be directly related to the EPUB maker itself. Given that the EPUB maker is imported from an external library, it would be more efficient and appropriate to modify the source content rather than altering the EPUB maker.
> 
> I hope this clarifies the confusion.
> 
> (Unless a senior contributor says otherwise)

Makes sense
