### ISSUE TITLE
novel arabic

### ISSUE THREAD

**Issue by nassiri-ajawi2** [LNReader/lnreader#136]
المواقع العربية لم تعد تعمل حتى الموقع الواحد الدي كان
 يعمل ولكن بعد التحديت الاخير لم يعد يعمل أرجو من الاخوة الكرام حل المشكلة وشكرا على التطبيق لقد احببته جدا شكرا لكل القائمين عليه ❤
Arabic sites no longer work, even the one that used to be
  It works, but after the last update, it no longer works. I hope the honorable brothers solve the problem. Thank you for the application. I liked it very much. Thank you to all those who made it ❤

**Comment by rajarsheechatterjee** [comment]
Open separate issues for each source in [sources repo](https://github.com/LNReader/lnreader-sources/issues/new/choose).
