### ISSUE TITLE
Please add another Arabic site like the world of novels

### ISSUE THREAD

**Issue by rdgryhc** [LNReader/lnreader#1367]
### Describe your suggested feature

https://realmnovel.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rdgryhc** [comment]
Please add a site https://realmnovel.com/

**Comment by nyagami** [comment]
>  If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
