### ISSUE TITLE
there is no translation into Russian "Multi", although there is a translation in the settings.

### ISSUE THREAD

**Issue by VectorNEON** [LNReader/lnreader#1369]
### Steps to reproduce

there is no translation into Russian "Multi", although there is a translation in the settings.
![cats](https://github.com/user-attachments/assets/48f2c0b4-9da5-493f-bd4b-641d22b8975a)

### Expected behavior

no translation

### Actual behavior

 the translation must be present, because there is a translation

### LNReader version

Github Action 2.0.0 (27/12/24 03:17 PM UTC) Commit: e01cbefd

### Android version

Android 10

### Device

Realme C11 (2020)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
On the plugins list, the language string comes from the keywords defined in the plugin repository, not from the app’s strings, which is why they aren’t translated.

**Comment by VectorNEON** [comment]
> On the plugins list, the language string comes from the keywords defined in the plugin repository, not from the app’s strings, which is why they aren’t translated.

Got it, then there are no questions.
I thought it was taken from the program, but apparently I was wrong.
