### ISSUE TITLE
Blank chapters on Novelbin extension 

### ISSUE THREAD

**Issue by Mudblood2001** [LNReader/lnreader#1372]
### Steps to reproduce

Open chapters of the a novel from this extension

### Expected behavior

![Screenshot_20241114_172047](https://github.com/user-attachments/assets/276b3f3e-5fa5-4762-a571-de941f74c05d)

### Actual behavior

![Screenshot_20241126_132651](https://github.com/user-attachments/assets/6f3a4ead-996a-4b8c-99a8-c815e25634c7)

### LNReader version

2.0.0

### Android version

12

### Device

Vivo y20

### Other details

I've asked about in the discord but other people are not facing this issue ,please tell me is there a way to fix this .Thank you 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
