### ISSUE TITLE
Japanese font

### ISSUE THREAD

**Issue by Geniusssmit** [LNReader/lnreader#140]
Since there is a JP source, can you add a few Japanese fonts? With currently available fonts all japanese symbols renders as chinese

**Comment by rajarsheechatterjee** [comment]
You can turn Render HTML on in reader bottom sheet or Reader Settings and use custom CSS to use any font.

For example

```
@import url('https://fonts.googleapis.com/css2?family=Noto+Sans+JP&display=swap');

* {
    font-family: 'Noto Sans JP', sans-serif; 
}
```
