### ISSUE TITLE
Add Right To Left option

### ISSUE THREAD

**Issue by HamedAlKhateeb** [LNReader/lnreader#146]
Could you please add the Right to left option (for the text) in the app? some languages like Arabic are readable that way. It really will help me and every Arabic speaker.

**Comment by SkillGG** [comment]
You could get RTL using custom CSS and using WebView reader.
CSS:
```
* {
    direction: rtl;
}
```

**Comment by HamedAlKhateeb** [comment]
Worked like magic, thank you.

‫في الخميس، 13 يناير 2022 في 10:27 م تمت كتابة ما يلي بواسطة ‪Marcin
Majewski‬‏ ***@***.***‬‏>:‬
