### ISSUE TITLE
[Feature Request] Navigation through tapping right or left side of the screen. 

### ISSUE THREAD

**Issue by ProdiptoPantho** [LNReader/lnreader#149]
I want to suggest that you add per page layout in reader mode and the feature of navigation through tapping the right or left side of the screen to navigate page by page.

Suggestions:
1. You can follow the feature of Moonreader from the play store.
2. You can go through this favourite app of mine.  Link: https://drive.google.com/file/d/1my3UWLUx6_kEsY-EDG6eIURcOGcOsXi3/view?usp=drivesdk

**Comment by PascalLeroi** [comment]
Hi,
I saw that this app now has the functionality to export to EPUB :) 
Would it be also possible to have the same page making functionality but in the app itself? That way you don't have to export each chapter and then go back to the app to check the chapters as read, and also tracking. 
I use my ereader for manga and would love to use it for LightNovels as well, but infinity scrolling sadly does not go well on an E-Ink screen. 
Checked the code myself to see if I could find out how to divide the pages and make the functionality myself, but it went over my head... 
If you could point in the right direction, that would help a lot :D Thanks
