### ISSUE TITLE
Reader voice stuttering

### ISSUE THREAD

**Issue by sjain3097** [LNReader/lnreader#162]
Hi,
The reading voice keeps stuttering when the chapter starts and in the middle again

**Comment by sjain3097** [comment]
Any updates on this?

**Comment by rajarsheechatterjee** [comment]
Can you provide the Source, Novel & Chapter name so that I can reproduce it?

Also does it happen for every chapter in your library?

**Comment by sjain3097** [comment]
Previously it was happening for every novel and chapter but now the issue is fixed and Eveything seems to be working fine
