### ISSUE TITLE
[Feature Request] Integrated Translator

### ISSUE THREAD

**Issue by EletroMBC** [LNReader/lnreader#163]
add a translator integrated in the APP to translate the chapters into other languages

**Comment by rajarsheechatterjee** [comment]
Good/reliable translation services are paid and as this app is completely free I am not making any money so it's not possible to implement it.

**Comment by Snowad14** [comment]
Why not use "googletrans" which uses the free and unlimited Google translate API?

**Comment by rajarsheechatterjee** [comment]
> Why not use "googletrans" which uses the free and unlimited Google translate API?

Could you share the npm package for it which works with React Native?
