### ISSUE TITLE
External sources

### ISSUE THREAD

**Issue by ghost** [LNReader/lnreader#166]
Is it possible to make the installation of external applications to be done manually, instead of internal ones, such as the tachiyomi-extensions and Anyomi application?  

Like on that next
![Screenshot_20220216-113726](https://user-images.githubusercontent.com/87826849/154227303-939ceffd-ad64-4ecb-8e0d-b9137c6f88b0.png)

**Comment by rajarsheechatterjee** [comment]
I do plan on making sources external. Currently, I don't know how to do it in React Native.

**Comment by SGthecoder** [comment]
> I do plan on making sources external. Currently, I don't know how to do it in React Native.

Then atleast give us options to search from limited sources do not search in all it consume to much data for me and user like who have limited data access

**Comment by rajarsheechatterjee** [comment]
> Then atleast give us options to search from limited sources do not search in all it consume to much data for me and user like who have limited data access

You can pin the sources you want to use and turn off search all sources in browse settings and the app would only search pinned sources in global search.

**Comment by SGthecoder** [comment]
> > Then atleast give us options to search from limited sources do not search in all it consume to much data for me and user like who have limited data access
> 
> You can pin the sources you want to use and turn off search all sources in browse settings and the app would only search pinned sources in global search.

Thank you

**Comment by nyagami** [comment]
implemented in v2
