### ISSUE TITLE
Swiping gestures suck

### ISSUE THREAD

**Issue by AbdullahBinJahed** [LNReader/lnreader#171]
this has been said already but swiping gestures suck too much in this app. i just can't use them.

any way to fix them ? which code is in charge of swiping gestures ? tell me the path to the files

**Comment by rajarsheechatterjee** [comment]
I am using a package ([react-native-swipe-gestures](https://github.com/glepur/react-native-swipe-gestures)) for swipe gestures.

It is being used in [ReaderScreen](https://github.com/LNReader/lnreader/blob/main/src/screens/reader/ReaderScreen.js) (line 369). Feel free to submit a fix.
