### ISSUE TITLE
 I want to add sources

### ISSUE THREAD

**Issue by yemenihandsome** [LNReader/lnreader#172]
Can you explain to me how to add resources to the application?

**Comment by rajarsheechatterjee** [comment]
You can see the [contributing guide](https://github.com/LNReader/lnreader/blob/main/CONTRIBUTING.md) for setting up the environment.

Then you can take a loot at [sources folder](https://github.com/LNReader/lnreader/tree/main/src/sources).

Create a new file with the name of source in it's language folder. You can pick the template from any other source and just edit the selectors. If the source's website follows a common format such as Madara, etc. go to the `multiSrc`  folder and create a new object in the generator file.

Once you have done that import your source in `src/sources/sources.js` and add it to the `scrapers` object and also add a new object  for your source in `src/sources/sources.json`.

If you have any doubts or face an issue feel free to ask.
