### ISSUE TITLE
[question] How can i help translate the app?

### ISSUE THREAD

**Issue by Vilianexe** [LNReader/lnreader#190]

**Comment by rajarsheechatterjee** [comment]
Currently, you can't translate the app. I do plan on settings up translations in future.

**Comment by kyoyacchi** [comment]
> Currently, you can't translate the app. I do plan on setting up translations in future.

Is there a way to translate now? Like, from crowdin or something?

**Comment by rajarsheechatterjee** [comment]
@kyoyacchi I have created a [crowdin project](https://crowdin.com/project/lnreader). I still have to add all the keys in the strings file and the app for the translations to work.
