### ISSUE TITLE
Option to disable RTL

### ISSUE THREAD

**Issue by ItsNotAMe** [LNReader/lnreader#195]
I click the button and nothing happens. Also would be nice if the app wouldn't support Rtl or add an option to disable it or something. Some things in my app are on the opposite side.
Also, the app crashes when I scroll all the way down in the reader settings.

**Comment by rajarsheechatterjee** [comment]
> I click the button and nothing happens. Also would be nice if the app wouldn't support Rtl or add an option to disable it or something. Some things in my app are on the opposite side.

Are you on a preview version or using TTS for a language other than english?

**Comment by ItsNotAMe** [comment]
What do you mean a preview version and how do I choose a language for TTS?

**Comment by rajarsheechatterjee** [comment]
> What do you mean a preview version
You can check the version in More > About.

>  how do I choose a language for TTS?
I meant language of the chapter. TTS only works for English.

**Comment by ItsNotAMe** [comment]
I changed the language of TTS on my phone to English and it is working now.
About the other problem I mentioned, all the buttons are on the opposite side
![Screenshot_20220408-162156_LNReader](https://user-images.githubusercontent.com/32935681/162444446-4d810fc5-036b-43ac-bdec-00e564c33f4d.jpg)

**Comment by rajarsheechatterjee** [comment]
Closing since the app is getting translated in other languages and RTL shouldn't be an issue.

**Comment by ItsNotAMe** [comment]
I don't want the app to be in my language, I want it in English. Will choosing the language to be English disable RTL?

**Comment by rajarsheechatterjee** [comment]
Changing your device's language to English should disable RTL.

**Comment by ItsNotAMe** [comment]
I didn't mean my phone language. Will there be an option to choose the language in the app and if yes will it disable RTL when I choose English?

**Comment by rajarsheechatterjee** [comment]
> Will there be an option to choose the language in the app

No

> if yes will it disable RTL when I choose English?

No, it would still depend on your device's language.

**Comment by rajarsheechatterjee** [comment]
> Could you add a way to change the language?

No, as things like RTL layouts are handled by React Native based on you device settings and adding an option to change the language would require me to manually add support for things which are handled automatically and maintain them.
