### ISSUE TITLE
Novel titles suddenly disappearing

### ISSUE THREAD

**Issue by Kai-Nui** [LNReader/lnreader#215]
Novel titles suddenly and randomly disappearing at v. 1.1.8.2

**Comment by rajarsheechatterjee** [comment]
Can you provide steps to reproduce this?

**Comment by Kai-Nui** [comment]
Sometimes after updating novels. Then I restart the app and the missing titles comeback. Sometimes after rebooting phone and lauching app the some titles also disppear. Like this. 
![Uploading Screenshot_2022-04-07-22-27-30-1820363722.png…]()
![Uploading Screenshot_2022-04-07-22-27-20-0950884634.png…]()

**Comment by Kai-Nui** [comment]
I don't know how it happened but it somehow got fixed after installing v1.1.8.3 and restarting phone. 😯🤔😅
