### ISSUE TITLE
[Bug] "Only show pinned sources" doesn't work 

### ISSUE THREAD

**Issue by seizue** [LNReader/lnreader#226]
Only show pinned sources doesn't work on latest release (v1.1.8.3)
It still shows all sources and not the pinned sources only.
....
also thank you for adding the new sources!

**Comment by Kai-Nui** [comment]
True. I had to re-pin my sources. 😅😅😅

**Comment by rajarsheechatterjee** [comment]
@Kai-Nui I changed the way pinned sources were stored, so existing data was lost.
