### ISSUE TITLE
[Feature Request] Theme Splash Screen

### ISSUE THREAD

**Issue by BreadGenie** [LNReader/lnreader#23]
The splash screen looks good with the default theme but is mismatched using with other themes

**Comment by rajarsheechatterjee** [comment]
> The splash screen looks good with the default theme but is mismatched using with other themes

I think I can make the app change the splash screen colors based on the current theme. I'll look into it.

> Can this be done to app icon too? 🤔

I don't think it is possible to change the app icon programmatically.
