### ISSUE TITLE
Include the app on F-Droid 

### ISSUE THREAD

**Issue by Poussinou** [LNReader/lnreader#247]
Hi,

Since this app is MIT licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, are you ok with the integration of this app on F-Droid?

**Comment by rajarsheechatterjee** [comment]
Didn't F-droid remove Tachiyomi because of copyright claims? Wouldn't same happen to this app if it's added?

**Comment by advait404** [comment]
I am still able to see and install tachiyomi from f-droid, so I think it should be ok to have LNreader as well.

**Comment by Poussinou** [comment]
It looks like it's ok to put this app in F-Droid repo, so [I opened a RFP](https://gitlab.com/fdroid/rfp/-/issues/2098).

Maybe you could establish Fastlane in this repo ([link](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane) to a good and helpful summary from a F-Droid maintainer), it'll be useful for F-Droid latter

**Comment by IzzySoft** [comment]
The issue I see is rather this:

```
Offending libs:
---------------
* Play Install Referrer Library (/com/android/installreferrer): NonFreeDep,NonFreeNet,Tracking
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Android Market (/com/google/android/finsky): NonFreeNet
* Google Mobile Services (/com/google/android/gms): NonFreeDep
* Firebase (/com/google/firebase): NonFreeNet,NonFreeDep
* Firebase Analytics (/com/google/firebase/analytics): NonFreeDep,Tracking

6 offenders.
```

F-Droid won't be able to accept and build this given the non-free dependencies.

**Comment by IzzySoft** [comment]
@rajarsheechatterjee completed? I cannot find the app on F-Droid. The RFP is still open, and cannot be processed that soon as there are still things missing. One thing are the proprietary dependencies (which linsui wrote can be patched out, but no such recipe was yet proposed) – the other is that there's no description of what the app is about and capable to do (else I had already included it with my repo): yes, it's a "novel reader". But where does it get the novels from? What features does it offer? Ideally, you'd have that in [Fastlane structure](https://gitlab.com/-/snippets/1895688) in your repo here, so you are in control of how your app is presented.

May I suggest to keep the issue open until the task is completed? :wink:

**Comment by linsui** [comment]
@rajarsheechatterjee What happened here? Are you OK if we package this app?

> One thing are the proprietary dependencies (which linsui wrote can be patched out, but no such recipe was yet proposed) – the other is that there's no description of what the app is about and capable to do (else I had already included it with my repo): yes, it's a "novel reader". But where does it get the novels from? What features does it offer? Ideally, you'd have that in [Fastlane structure](https://gitlab.com/-/snippets/1895688) in your repo here, so you are in control of how your app is presented.

I thought they can be patched out easily. But I didn't have a try since there is no answer here. I can open a PR for the description and it's not a blocker anyway.

**Comment by IzzySoft** [comment]
@linsui thanks! The missing description might not be a blocker (if you can substitute it) – but those 6 libs would be. So yes: if @rajarsheechatterjee is willing to merge it, your PR is definitely welcome – as is your patch :smiley:

**Comment by linsui** [comment]
About Tachiyomi, we got a DCMA notification, see https://gitlab.com/fdroid/admin/-/issues/195, but we finally ignored it and never removed Tachiyomi.

**Comment by linsui** [comment]
> This is just a side project I like to work on in my free time so I don't see any benefits of adding it to F-Droid.

Yes, of course. But there is no harm, right?

**Comment by rajarsheechatterjee** [comment]
> Yes, of course. But there is no harm, right?

I don't want to deal with copyright related issues.

**Comment by linsui** [comment]
Me neither :). But such copyright issue won't be caused by F-Droid inclusion, right? Or you worry about F-Droid will make it more popular so it has more chance to get a DCMA request?

**Comment by rajarsheechatterjee** [comment]
>  Or you worry about F-Droid will make it more popular so it has more chance to get a DCMA request?

This. And as I started this project just to learn React Native the code quality and performance isn't that good. So I don't plan on working on this app for much longer as it's just difficult to maintain and implement new features.
