### ISSUE TITLE
paragraph spacing is way to large. 

### ISSUE THREAD

**Issue by afat123** [LNReader/lnreader#248]
The previous version didn't have this problem. After i update the app, the paragraph spacing becomes way to big. 
![Screenshot_2022-05-07-01-00-34-439_com rajarsheechatterjee LNReader](https://user-images.githubusercontent.com/65108757/167193880-00eec4fa-ee16-45da-b335-504719025c91.jpg)
^This is the new updated version. 

While below is the old spacing:
![Screenshot_2022-05-07-01-08-17-562_com rajarsheechatterjee LNReader](https://user-images.githubusercontent.com/65108757/167194017-85c93b4a-cb92-4884-aa6f-267076929d68.jpg)

Please reduce the spacing. 
Thanks in advance

**Comment by rajarsheechatterjee** [comment]
In the previous versions, the app used to clean up the HTML from the source website using Regex whereas now it's using a package [sanitize-html](https://github.com/apostrophecms/sanitize-html) for it which is better as it preserves the original formatting and also has many other features.

You can use custom CSS in More > Settings > Reader to reduce the spacing.

**Comment by afat123** [comment]
how to use it? the CSS thingy i mean.
is there a code or something i can copy?
because, i don't understand on how to use the custom CSS.

**Comment by rajarsheechatterjee** [comment]
> is there a code or something i can copy?

No as styles differ from site to site.

You have to check the chapter's HTML in the source website and add the CSS accordingly. Alternatively, I can add an option to reduce multiple new lines to a single one to reduce the spacing.

**Comment by afat123** [comment]
Alternatively, I can add an option to reduce multiple new lines to a single one to reduce the spacing.

if you can, please reduce it. 
dont worry about taking a long time. i can wait.
