### ISSUE TITLE
[Feature Request] Add Last Read sorting system and option to create categories

### ISSUE THREAD

**Issue by H7XXY** [LNReader/lnreader#255]
Hi, In the next update can you please add another sorting system named LAST READ and add an option to create Categories like the Tachiyomi app ? 

It is very frustrating to find the novel I was reading after opening the app another time.

**Comment by seizue** [comment]
@H7XXY  Why not just go to "history" to check the recent novels you read. It temporary resolved your issue. As for for  the categories it's been requested, the dev been working on it i think
