### ISSUE TITLE
[ Feature Request ] Text Filtering

### ISSUE THREAD

**Issue by qwertea** [LNReader/lnreader#263]
A lot of sources include garbage text. For example:
![image57](https://user-images.githubusercontent.com/24505745/168882915-f88af32a-ea68-4b42-a687-47ab6dd69b52.png)
It can be pretty annoying, especially if you use TTS and have to listen to it every time.

It would be quite useful if we could remove text like this with user-defined text filters. Ideally the filters would support regex patterns for text matching but simple exact-match filtering would be immensely useful by itself.

They should probably be source or novel-specific to avoid unwanted filtering in other novels.

(I don't think this is possible with custom CSS; if it is, please let me know how.)

**Comment by rajarsheechatterjee** [comment]
This should be possible using Custom JS in Reader settings.

**Example**

```js
html = html.replace("for faster releases read on webnovel.site", "")
```

**Source Specific** (sourceId is present in Browse screen)

```js
if (sourceId === N) {
  html = html.replace("for faster releases read on webnovel.site", "")
}
```
