### ISSUE TITLE
[Feature Request] Add a scroll bar in chapter list

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader#278]
It is annoying to scroll through all the chapters

Add a scroll bar like Tachiyomi:

![IMG_20220528_223233](https://user-images.githubusercontent.com/105352597/170835409-b9487558-9aa6-4253-9a7a-2aa8e9b77ac3.jpg)

**Comment by rajarsheechatterjee** [comment]
It's not possible in React Native, list items get rendered on screen as you scroll for better performance and loading all chapters at once would take a bit of time and make the app even slower.

You can read more about it [here](https://reactnative.dev/docs/flatlist).

**Comment by Pheonix-Flames** [comment]
> It's not possible in React Native, list items get rendered on screen as you scroll for better performance and loading all chapters at once would take a bit of time and make the app even slower.
> 
> You can read more about it [here](https://reactnative.dev/docs/flatlist).

But 'Novel Library' app has scroll bar :

![Screenshot_2022-05-29-14-26-56-99_156c7236e6feadae6e32e367f1641d5a](https://user-images.githubusercontent.com/105352597/170860263-5856f38f-114a-4d2b-8b98-8cb311fcfd8e.jpg)

**Comment by rajarsheechatterjee** [comment]
> It's not possible in React Native

Novel library is a native app written in Kotlin.

**Comment by Pheonix-Flames** [comment]
> > It's not possible in React Native
> 
> Novel library is a native app written in Kotlin.

Then how is it possible in Tachiyomi it is also a React native app

**Comment by Pheonix-Flames** [comment]
Then is it Possible to add a Chapter Search Option in novel Like how 'Shosetsu' does:

Here is a Screenshot:

![Screenshot_2022-06-03-22-42-18-08_fa10efb44922cf31ab3f2ab1e3bc7c48](https://user-images.githubusercontent.com/105352597/171913950-4fbadbb6-7107-4b29-9867-007f5f7412c2.jpg)
![Screenshot_2022-06-03-22-45-40-38_fa10efb44922cf31ab3f2ab1e3bc7c48](https://user-images.githubusercontent.com/105352597/171913957-c6fac102-0e47-4aa0-916f-6410308fe08b.jpg)

**Comment by rajarsheechatterjee** [comment]
There already is an option for that in the app.

![Screenshot_2022-06-03-22-47-08-93_3c1c179116822eec69c21805387f0489.jpg](https://user-images.githubusercontent.com/57822170/171914124-515e22bd-bec9-47c3-ab87-38ef3dbb7ab5.jpg)
