### ISSUE TITLE
About Text To Speak

### ISSUE THREAD

**Issue by massmia** [LNReader/lnreader#280]
Is it possible to add a highlight option that highlights the reading line like moon+ reader pro reader? 
Image For reference 

![Screenshot_20220603_141848_com.flyersoft.moonreaderp.jpg](https://user-images.githubusercontent.com/98101010/171817966-672bcdb7-1430-4c5e-9615-9d5acfe1fed7.jpg)

**Comment by rajarsheechatterjee** [comment]
Duplicate of #90
