### ISSUE TITLE
[Feature Requests] Add Search by genre in sources

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader#285]
Add The Features For Searching Novel By Genre In Noval Sources

**Comment by Pheonix-Flames** [comment]
When this feature will be available on the app ?

**Comment by rajarsheechatterjee** [comment]
It's available in [preview](https://github.com/LNReader/lnreader-preview/releases/tag/v1.1.10.1). Currently filters are only available  for NovelUpdates and ReadLightNovel as they need to be manually added for each source.
