### ISSUE TITLE
[Feature Request] Horizontal reading mode

### ISSUE THREAD

**Issue by renatopdalencar** [LNReader/lnreader#29]
Hello again. Sorry for this second request, but if both are implemented, this app would be perfect for me.

It would be great to have an option to toggle between the current vertical reading mode and an horizontal/page by page reading mode. Scrolling for a long time when reading multiple chapters can be tiring, so I find it more comfortable to just tap at the sides to go back or forward a page.

**Comment by rajarsheechatterjee** [comment]
Horizontal reading mode is planned for future. There isn't a way to add it right now.

**Comment by renatopdalencar** [comment]
I understand. Thank you for your effort.
