### ISSUE TITLE
[Feature Request] Add Search option in Browser instead of 'Search Source'

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader#293]
Switch 'Global Search' And 'Search Source'

![IMG_20220613_010305](https://user-images.githubusercontent.com/105352597/173250435-89655a24-3c9b-47fe-b5c3-5f7324072097.jpg)

**Comment by rajarsheechatterjee** [comment]
Closing since tabs would be added on browse screen like Tachiyomi in future which would handle this.
