### ISSUE TITLE
[Bug] Many Websites are not working

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader#294]
Many Websites are not working if we are using their sources but they are working if we are using web browser

![Screenshot_2022-06-13-01-23-08-13_3c1c179116822eec69c21805387f0489](https://user-images.githubusercontent.com/105352597/173251052-70c3fc77-d69c-4970-9c60-373747389d1f.jpg)
![Screenshot_2022-06-13-01-23-13-33_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/105352597/173251054-64ee7ce0-9563-4dc9-b8a8-6f2483ec4811.jpg)

**Comment by rajarsheechatterjee** [comment]
Create individual request for each source in the [sources repo](https://github.com/LNReader/lnreader-sources/issues).
