### ISSUE TITLE
Weird behavior of the "Finished" label in the reader

### ISSUE THREAD

**Issue by satarov-ruslan** [LNReader/lnreader#304]
At the bottom of the chapter, the "Finished" label shows the name of the current chapter (pic 1).
![Screenshot_20220618-153936](https://user-images.githubusercontent.com/42942835/174438319-f8db5008-8e77-4776-ba46-fca56674a960.jpg)

But if you close the app at this page and then reopen the app, the "Finished" label also prepends the title of the novel (pic 2).
![Screenshot_20220618-153919](https://user-images.githubusercontent.com/42942835/174438399-3748125d-7931-4b98-87c1-b93714d83832.jpg)

And when you go to another chapter, this novel title disappears.
Is this the expected behavior?

**Comment by SkillGG** [comment]
I noticed it too when I was doing WebView buttons. Couldn't figure out why the novel title sometimes had the name of the novel in it, and sometimes didn't. I just assumed that the particular source I was using was adding it, but it seems like I was wrong. It's something with novelName that's passed to reader component (webview/regular reader) but I'm not sure what causes it

**Comment by rajarsheechatterjee** [comment]
There are two chapter names for each chapter.

1. Chapter name in the chapter list.
2. Chapter name which is taken from the chapter's page from the source website.

So the chapter name in finished text is usually the 2nd one and if it's not present it shows the first one.

> Is this the expected behavior?

Yes, I do plan to make things like these more consistent in future when the code for the reader screen will be rewritten . 

> It's something with novelName that's passed to reader component (webview/regular reader) but I'm not sure what causes it

I don't think so as chapter name is same for both the readers.

https://github.com/LNReader/lnreader/blob/b4c234ef938c23c11c25f2bcbe61cab6a4cc62d9/src/screens/reader/ReaderScreen.js#L443
