### ISSUE TITLE
Here is the list of all non working Sources of LNReader

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader#305]
https://github.com/LNReader/lnreader-sources/issues/317#issue-1275663784

ComradeMao
FastNovel
KissLightNovels
LightNovelPub
LightNovelHub
[Ltnovel.com](http://ltnovel.com/)
MTLCornor
NitroScans
Novelmt
NovelPub
NovelsRock
OnlyMTL
Readwn
WebNovelLove
[Wuxia.city](http://wuxia.city/)
[WuxiaWorld.cloud](http://wuxiaworld.cloud/)

**Comment by rajarsheechatterjee** [comment]
Duplicate of LNReader/lnreader-sources#317
