### ISSUE TITLE
[Bug] Reader background doesn't change instantly on some devices

### ISSUE THREAD

**Issue by joseph619** [LNReader/lnreader#31]
As discussed on discord - https://discord.com/channels/835746409357246465/835757769172713503/850261076927184896

**Comment by rajarsheechatterjee** [comment]
I have added an option to change reader background in Settings > Reader which should change it instantly. I'll need to figure out why it is slow on some devices.

**Comment by joseph619** [comment]
Yeah it can be slow to change if done from reader sheet.

**Comment by rajarsheechatterjee** [comment]
Resolved by #515
