### ISSUE TITLE
Add image upload

### ISSUE THREAD

**Issue by dkpeld** [LNReader/lnreader#314]
It currently does not load images for offline reading, and even if you load an image by opening a chapter, the next time you go offline, it will unload it from the image cache. You can make an option in the settings whether to upload images, for those who do not want to - let it be turned off by default. Those who want this feature will change it themselves in the settings. Thanks.

**Comment by rajarsheechatterjee** [comment]
This is not possible as images in a chapter are just `<img>` tags and they are converted to native views when a chapter is opened.

**Comment by dkpeld** [comment]
> This is not possible as images in a chapter are just `<img>` tags and they are converted to native views when a chapter is opened.

Then make sure that they are not unloaded from the cache.

**Comment by rajarsheechatterjee** [comment]
> Then make sure that they are not unloaded from the cache.

The images in a chapter are not cached.
