### ISSUE TITLE
App closing when settings> reader page is scrolled to the bottom

### ISSUE THREAD

**Issue by Kai-Nui** [LNReader/lnreader#322]
https://user-images.githubusercontent.com/96187646/180357635-b4e61ba5-0aeb-4f10-9c1d-a08b19290b38.mp4

App closing when settings> reader page is scrolled to the bottom

I'm trying to code custom css but when I scroll down, the app closes. I'm using latest preview build and went back to latest stable release 1.1.10 but same behavior

**Comment by rajarsheechatterjee** [comment]
Could you try changing the reader theme in reader bottom sheet and then open reader settings.

**Comment by Kai-Nui** [comment]
Tried this just now, app still closing when scrolled down to bottom of page

**Comment by Kai-Nui** [comment]
I'm on MIUI 13.0.2.0 just in case it's os glitch

**Comment by rajarsheechatterjee** [comment]
It's been reported before but I have never been able to reproduce it.

Could you share the logs of the crash? You can use [logcat](https://play.google.com/store/apps/details?id=com.dp.logcatapp).

**Comment by Kai-Nui** [comment]
Like this? Not sure if I did it properly.

**Comment by Kai-Nui** [comment]
The logcat with android permission setting granted via ladb is over 25mb, I cant attach it here

**Comment by rajarsheechatterjee** [comment]
> Like this? Not sure if I did it properly.

This doesn't seem to have any info related to the app/crash.

> The logcat with android permission setting granted via ladb is over 25mb, I cant attach it here

Not sure how large the logs usually are but you can upload them to a google drive and share the link.

**Comment by Kai-Nui** [comment]
https://drive.google.com/file/d/12zpLIbisyYs4rYzyxqQi6M1Q7mU8mooa/view?usp=drivesdk

**Comment by Kai-Nui** [comment]
Did this one capture the crash?

**Comment by Kai-Nui** [comment]
> > https://drive.google.com/file/d/12zpLIbisyYs4rYzyxqQi6M1Q7mU8mooa/view?usp=drivesdk
> 
> I didn't find anything about the crash related to the app in the logs but I think I have found the issue. I'll share an apk soon with the fix.

Eh, sorry if the logs weren't useful. Maybe I did it wrong. Looking forward to the fix. Thank you so much.

**Comment by rajarsheechatterjee** [comment]
Could you check if the crash is fixed in [this version](https://drive.google.com/file/d/1TjzIZAosdjxr0UxI_UENQpHz9PBxrtDV/view?usp=sharing)?

**Comment by Kai-Nui** [comment]
> Could you check if the crash is fixed in [this version](https://drive.google.com/file/d/1TjzIZAosdjxr0UxI_UENQpHz9PBxrtDV/view?usp=sharing)?

Updated using that version, reboot phone- still crashing 

Uploading ScreenRecord-2022-07-22-12-52-13~2.mp4…

**Comment by rajarsheechatterjee** [comment]
You can either share better crash logs (only record the crash) or backup and try a clean install. The latter should definitely fix the issue but you'll lose your progress and downloads.

**Comment by Kai-Nui** [comment]
Tips on how to only record crash logs? Sorry I'm a coding dummy.

**Comment by rajarsheechatterjee** [comment]
> Tips on how to only record crash logs?

Only record opening the app and going to reader settings.

> I tried clean reinstall and rebootng phone but still crashing when render html is toggled on and scrolling to bottom

If clean reinstall isn't fixing it I don't think it's an app issue. Could be something device specific.

**Comment by Kai-Nui** [comment]
I used the filter to include only lnreader. Hope this captured the crash. 
[logcat_07-22-2022_17-32-25.txt](https://github.com/LNReader/lnreader/files/9166553/logcat_07-22-2022_17-32-25.txt)

**Comment by Kai-Nui** [comment]
> If clean reinstall isn't fixing it I don't think it's an app issue. Could be something device specific.

I also have a feeling it's MIUI. Lately having issues with other apps too after updating to MIUI 13.

**Comment by CaptPlasma** [comment]
I have more details on this

This only occurs if renderhtml is enabled, the app won't crash if u disable first
