### ISSUE TITLE
Make the vibration when you select chapters optional

### ISSUE THREAD

**Issue by JackTheRipper47** [LNReader/lnreader#326]
Didn't know where else to post this but it would be nice if you could add categories
Also make the vibration when you select chapters in each novel optional
Also there are a lot of delays when reading and changing settings, like going to the next chapter or enabling something..

**Comment by rajarsheechatterjee** [comment]
> Didn't know where else to post this but it would be nice if you could add categories

There's an open issue for categories #45

> Also there are a lot of delays when reading and changing settings, like going to the next chapter or enabling something

Performance should eventually get better.

**Comment by mazyuin** [comment]
Just about to make an issue about this. Please make the vibration go away 😿
