### ISSUE TITLE
Select text feature bug(?)

### ISSUE THREAD

**Issue by mazyuin** [LNReader/lnreader#332]
So, it works fine if you open the novel from your library but if you open it from history tab then no matter what you do, "select text" feature won't work! It's like having the default reader option instead of the customized option.
What i've tried to do are re-enabling the "select text" feature and skip to the next chapter to see if it works in the next chapter. I also tried to go back to the chapter i was reading, but it's to no avail.
I can't even opt to html render mode since they do not actually save your progress...
(novel source: mysticalseries)
Edit: the bug also happen when i open from the library tab now.... It happens after i select the text, then continuously tap the area where there is a text. (not the selected text area)

**Comment by rajarsheechatterjee** [comment]
Text selection doesn't work in the default reader due to it being wrapped in a touchable, I'll remove the option.

> I can't even opt to html render mode since they do not actually save your progress...

It does save the progress in preview version.
