### ISSUE TITLE
Global Search Option is Lagging 

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader#337]
Video of the Issue: https://youtu.be/FVG2Rq6FWeE

**Comment by rajarsheechatterjee** [comment]
This has already been mentioned in browser settings. Sending multiple requests to different websites at the same time will freeze the app. Turn off search all sources and search only a limited number of sources.

![Screenshot_2022-07-28-15-13-01-40_3c1c179116822eec69c21805387f0489.jpg](https://user-images.githubusercontent.com/57822170/181475309-e9ee6cb9-5eb1-493c-9b3b-7b5e5db8fc90.jpg)
