### ISSUE TITLE
Bug with quick chapter change

### ISSUE THREAD

**Issue by satarov-ruslan** [LNReader/lnreader#348]
If you switch between the previous and the next chapters quick enough, you can see an "undefined" label on the Next Chapter button. And if you continue this process, it will show an error like on the screen.
Tested on Martial World (LightNovelHeaven)
![Screenshot_20220801-205728](https://user-images.githubusercontent.com/42942835/182213482-27e3d84f-887d-4c38-bc7b-50b519f5c910.jpg)

**Comment by nyagami** [comment]
@rajarsheechatterjee  I think this should be solved with current dev version. I've tested on real devices (android 8 and 11)
