### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by mrlee023** [LNReader/lnreader#351]
Add options to keep screen awake while reading.

**Comment by rajarsheechatterjee** [comment]
That is the default behaviour. Screen should always be awake in reader.

**Comment by mrlee023** [comment]
i've noticed it when i switch between chapters in the reader

**Comment by rajarsheechatterjee** [comment]
> i've noticed it when i switch between chapters in the reader

You mean when the next chapter is loading?

**Comment by mrlee023** [comment]
No, whenever i move to chapters using these.
![IMG_20220808_213625](https://user-![IMG_20220808_214109](https://user-images.githubusercontent.com/110322518/183432527-8046c259-58db-4555-8f61-ce4c9e3af23b.jpg).githubusercontent.com/110322518/183432403-8d8e32a7-b53d-479d-980e-f5d789f13979.jpg)

**Comment by mrlee023** [comment]
No, when only the chapter is already loaded up, then around 15 seconds while reading then the screen would fall asleep.

**Comment by rajarsheechatterjee** [comment]
I can't reproduce this. The screens stays awake for me in reader.

**Comment by mrlee023** [comment]
it's ok, it is what it is.
