### ISSUE TITLE
[Bug] Deleted Categories with a categorize novel is not visible in dafault state. 

### ISSUE THREAD

**Issue by seizue** [LNReader/lnreader#370]
There's a bug when a category is deleted, the novel wont show up or not visible in the default category. The novel is still there but is just not visible. 
Clearing cache makes the novel visible again.
 While clearing cache,  I also found a new bug. The novel I change cover (from local source) won't refresh back to website (default) cover. It's in 'No Cover' state no matter how many times I tried to refresh the novel

https://user-images.githubusercontent.com/25120376/184519070-e15d9911-f81d-4549-bc35-b373594a7676.mp4

**Comment by rajarsheechatterjee** [comment]
> While clearing cache, I also found a new bug. The novel I change cover (from local source) won't refresh back to website (default) cover. It's in 'No Cover' state no matter how many times I tried to refresh the novel

Do you have `Automatically refresh metadata` on in General settings?

**Comment by seizue** [comment]
> > While clearing cache, I also found a new bug. The novel I change cover (from local source) won't refresh back to website (default) cover. It's in 'No Cover' state no matter how many times I tried to refresh the novel
> 
> Do you have `Automatically refresh metadata` on in General settings?

Nope. Should it be in 'On'?

**Comment by rajarsheechatterjee** [comment]
Turning `Automatically refresh metadata` on will reset the cover back to website image when you refresh a novel / update your library.

**Comment by seizue** [comment]
> Turning `Automatically refresh metadata` on will reset the cover back to website image when you refresh a novel / update your library.

alright. It's fix the problem. 
Thanks~
