### ISSUE TITLE
App crashes when updating library in updates

### ISSUE THREAD

**Issue by mrlee023** [LNReader/lnreader#373]

**Comment by rajarsheechatterjee** [comment]
Do you see any error message?

**Comment by mrlee023** [comment]
no errors just suddenly closes the app.

**Comment by rajarsheechatterjee** [comment]
Could you share a screen recording?

**Comment by mrlee023** [comment]
https://user-images.githubusercontent.com/110322518/184544397-98e6dde7-9700-4c3c-9396-f6e8ba65dabb.mp4

**Comment by mystic-man-rhino** [comment]
Same thing happened with me also Android 11 version 1.1.12.2
