### ISSUE TITLE
Bug: When categorising a new Novel it doesn't deselect The Previously selected catagory 

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader#375]
When categorising a new Novel it doesn't deselect The Previously selected Catagory and doesn't deselect it by default i have to deselect it manually

**Comment by rajarsheechatterjee** [comment]
I don't understand, could you share a screen recording and add the current and expected behavior.

**Comment by rajarsheechatterjee** [comment]
Closing this. Create a new issue and follow the template.
