### ISSUE TITLE
[Feature Request] Local Epub support

### ISSUE THREAD

**Issue by joseph619** [LNReader/lnreader#38]
A lot of good translations/official translations are not available on the aggregator sites, and can only be obtained locally, Request local epub support as that would allow readers to access their personal collections.

**Comment by KasukeLp23** [comment]
Yes, it would be greatly appreciated if the creator placed a local file option either in Epub or Pdf format.

**Comment by BhaturaGuy** [comment]
How tf is this not a feature already

**Comment by oromis995** [comment]
> How tf is this not a feature already

It's a volunteer project, have some respect. If you want it so bad why don't you develop it?

**Comment by cactusoftheday** [comment]
My guy we're slowly working on it with our free time. You can also work on it if you'd like. If you know any react native or anything, there's a pull request for this issue but it needs a front end component.

**Comment by BhaturaGuy** [comment]
Sorry, I was drunk last night and I apologise for any disrespect. But from a user perspective this just looks like LNScrapper at best, there isn't a single good source for LNs (ref piracy.moe), there were only MTL and bad fan translations only. Maybe add new sources (good ones) until local EPUB is supported?
