### ISSUE TITLE
Downloading Cover Image feature.

### ISSUE THREAD

**Issue by kyoyacchi** [LNReader/lnreader#394]
### Describe your suggested feature

I think it would be good to have downloading cover image of LNs to device gallery feature. Like in Tachiyomi.

![tachisy](https://user-images.githubusercontent.com/63583961/185140550-e71736d0-44e2-4873-a7a8-7e4875af9240.jpg)
(TachiyomiSY)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Resolved in f069a67660a2d4ce386a62318b70a4743e630ac4
