### ISSUE TITLE
No Novel Cover on NovelHall 

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader#395]
### Steps to reproduce

Go to Browse and Click on NovelHall

### Expected behavior

It should show the novel name with their cover

### Actual behavior

It is not showing Novel Cover but when we click on a novel then it will show its cover

### LNReader version

1.1.12

### Android version

11

### Device

Realme 3 pro

### Other details

![Screenshot_2022-08-17-19-45-45-05_3c1c179116822eec69c21805387f0489](https://user-images.githubusercontent.com/105352597/185157918-b7d608b3-ad98-4d77-98c3-cff0c4a1434b.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.12](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with an source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
