### ISSUE TITLE
Multiple "Category" feature requests 

### ISSUE THREAD

**Issue by LUNAEstelle** [LNReader/lnreader#397]
### Describe your suggested feature

Please add a feature where we can make separate categories for different genre or specifications.
E.g. I want to make a separate categories for Romance,action,adventure,josei,mature,BL, and etc genre. 
I also want to make a separate category/catalog for completed and ongoing novels. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Svk1190** [comment]
I see. Maybe this can be achieved by custom tags. 

1) The novels can be categorized by ongoing / completed / planned etc, and these categories are visible in the form of tabs.
2) The user can also add custom tags to each novel, for example, romance / action / adventure etc. The user can click on a tag to see all novels with that tag. Alternately, the user can search for the tag (or a combination of tags, categories, or description metadata) in the search bar, for example 'tag: action category:planned'.

**Comment by rajarsheechatterjee** [comment]
@LUNAEstelle Categories has been added in the preview versions, you can download the latest release from [here](https://github.com/LNReader/lnreader-preview/releases/latest). You can manually create all the different categories you want and add the novels.

@Svk1190 
For 1st, Not all sources provide the status and also they aren't consistent across different sources so the data in those categories would be incorrect.

2nd (Searching tags in library) is something which can be picked as an enhancement.

**Comment by Svk1190** [comment]
I probably did not word it well. 

For the first point, I wanted to talk about the novels that the user is currently reading, which can be manually categorized as 'reading' or 'planned' or 'completed reading', and these categories are shown in the form of tabs in the preview version. This is something you have already developed. 

For the second point, I considered the possibility of adding custom tags. A novel might have a tag 'fantasy' but the user might want some additional metadata to be associated with the novel, for example 'op mc', 'time travel', 'reincarnation' etc. If the user can add custom tags in addition to existing tags, this can serve as a second level of categorization.

**Comment by rajarsheechatterjee** [comment]
> For the second point, I considered the possibility of adding custom tags. A novel might have a tag 'fantasy' but the user might want some additional metadata to be associated with the novel, for example 'op mc', 'time travel', 'reincarnation' etc. If the user can add custom tags in addition to existing tags, this can serve as a second level of categorization.

There's an option to edit novel info where users can already add new tags or edit the existing ones. So if I add searching by the tags in library they should be able to it. I should also add clicking on tag goes to the library screen and adds the tag name as search text.

**Comment by Svk1190** [comment]
Thanks a lot! I had totally missed the feature of adding custom tags. Thanks again for this great app :)

**Comment by LUNAEstelle** [comment]
> > For the second point, I considered the possibility of adding custom tags. A novel might have a tag 'fantasy' but the user might want some additional metadata to be associated with the novel, for example 'op mc', 'time travel', 'reincarnation' etc. If the user can add custom tags in addition to existing tags, this can serve as a second level of categorization.
> 
> There's an option to edit novel info where users can already add new tags or edit the existing ones. So if I add searching by the tags in library they should be able to it. I should also add clicking on tag goes to the library screen and adds the tag name as search text.

I probably didn't word it right? 
What i mean is, i want to be able to make a customized folder/tab in library. I want to be able to create separate folders to add the different novels. 
Example:
 -Folder/tab 1 would be named "opmc/isekai", then i would put all the related novels there. 
-Folder/tab 2 would be named "favorite novels",then i would put all my favorite novels there. 
-Folder/tab 3 would be named "cute/fluffy/soft novels", then i would put all tge fluffy and slife of life novels there. 

This feature would make the library more organized. 

Btw i would also like to say thank you and to your team(if you have a team) for making and sharing this wonderful app♡

**Comment by Svk1190** [comment]
> I probably didn't word it right? What i mean is, i want to be able to make a customized folder/tab in library. I want to be able to create separate folders to add the different novels. Example: -Folder/tab 1 would be named "opmc/isekai", then i would put all the related novels there. -Folder/tab 2 would be named "favorite novels",then i would put all my favorite novels there. -Folder/tab 3 would be named "cute/fluffy/soft novels", then i would put all tge fluffy and slife of life novels there.
> 

This feature is present in the latest preview build. Categories are shown in the form of tabs.
