### ISSUE TITLE
The application does not have a version 1.1.12.4

### ISSUE THREAD

**Issue by yemenihandsome** [LNReader/lnreader#398]
### Describe your suggested feature

I can't download it because the download link for the app is not available 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
It had to be removed due to some issues, should be back soon.
