### ISSUE TITLE
Continuous audio reading feature for successive chapters

### ISSUE THREAD

**Issue by yemenihandsome** [LNReader/lnreader#399]
### Describe your suggested feature

We hope to add the successive audio reading feature to the successive chapters. We hope that there will be reading divisions for the chapter. I mean, I can move to the other lines when reading.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Duplicate of #90
