### ISSUE TITLE
Add slider in library 

### ISSUE THREAD

**Issue by Solovertical** [LNReader/lnreader#400]
### Describe your suggested feature

Its will helpful if there are more than 600 ch we can normally slide easily 
![IMG_20220820_073703](https://user-images.githubusercontent.com/109901807/185725315-45df23a1-ff55-4ee6-9a89-4fcd0731e24e.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
It's not possible in React Native, list items get rendered on screen as you scroll for better performance and loading all chapters at once would take a bit of time and make the app even slower.

You can read more about it [here](https://reactnative.dev/docs/flatlist).
