### ISSUE TITLE
Download continues to download chapter even with the internet connection turned off resulting to a chapter unavailable

### ISSUE THREAD

**Issue by Shiraru18** [LNReader/lnreader#403]
### Steps to reproduce

1. Download a Novel
2. While downloading turn off your internet connection
3. The downloader will continue to download the chapters despite no internet connection
4. Downloaded chapters will have a chapter not available error
[example video ](https://drive.google.com/file/d/1fLXcHkFAdRflAiiUd3h6VyrM5dqQAUlh/view?usp=sharing) 

### Expected behavior

Download will automatically turn off/stop when an Internet disconnection is detected. 

### Actual behavior

Download will continue resulting to a Chapter unavailable error 
![Screenshot_2022-08-21-18-08-14-336_com rajarsheechatterjee LNReader](https://user-images.githubusercontent.com/61309036/185786484-67f029f3-2ae3-4f97-8fac-da9df768b096.jpg)

### LNReader version

1.1.12.4

### Android version

Android 12

### Device

Poco F3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.12](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
This should be resolved in the newer versions.

If the download fails the app show an Notification of the error message.
