### ISSUE TITLE
Upgrade filter feature of Source: Novel Update 

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader#404]
### Describe your suggested feature

We can only add a genres for filter we can not exclude a genre from filter.

You can add a feature such as when you click on check box to select a genre than if you click on the same genre twice it will show a [X] Cross in Check Box which means the selected genre is excluded from filter 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
implemented in 2.0 version

**Comment by Palloxin** [comment]
If someone can close this issue..
