### ISSUE TITLE
Add This

### ISSUE THREAD

**Issue by MonomoySama** [LNReader/lnreader#408]
### Steps to reproduce

Add some "Light Novel" extension. There's no light novels here even if there's a whole lot of extensions. I don't like sites to read light novels so please add 

### Expected behavior

.

### Actual behavior

.

### LNReader version

.

### Android version

.

### Device

.

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.12](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with an source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).

**Comment by MonomoySama** [comment]
Yeah there are many extensions which don't have light novels but in their
real site they have just the extension don't. So this might be a issue with
extensions. So please fix this

**Comment by rajarsheechatterjee** [comment]
> Yeah there are many extensions which don't have light novels but in their
real site they have just the extension don't.

Create separate issues for every source with this problem in [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
