### ISSUE TITLE
novel trench bad url

### ISSUE THREAD

**Issue by capitanjal** [LNReader/lnreader#412]
### Steps to reproduce

Search on the novel trench source

### Expected behavior

Search on the selected source

### Actual behavior

The novel trench source is looking in a bad url
WebView search on https://novelhard.com/manga/https:/novelhard.com/novel/allrounders/
It should be
https://novelhard.com/novel/allrounders/

### LNReader version

1.1.12

### Android version

Android 11

### Device

Samsung Galaxy Tab a8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.12](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with an source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
