### ISSUE TITLE
Delete downloaded chapter when removing book from library 

### ISSUE THREAD

**Issue by BloodlineHeart** [LNReader/lnreader#413]
### Describe your suggested feature

When removing a book from library, let all the downloaded  chapters of the book be deleted.
The downloaded chapters of books I have removed from my library leaves files on the storage taking up space.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.12](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
There's already a snackbar which pops up when you remove a novel with downloaded chapters from library.
