### ISSUE TITLE
Not able to select text

### ISSUE THREAD

**Issue by shahzaib78631** [LNReader/lnreader#414]
### Steps to reproduce

Example:
1. Open a chapter
2. Long press on the text

### Expected behavior

Long pressing on text should allow the user to be able to select the text.

### Actual behavior

I am not able to select the text. 

### LNReader version

1.1.12

### Android version

Android 11

### Device

Samsung Galaxy A70

### Other details

Some times i am able to select text but mostly i am not able to select the text.
![Screenshot_20220826-214932_LNReader](https://user-images.githubusercontent.com/12490891/186953886-a1bdf6b4-1f95-4235-9528-9deac9e7cb46.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.12](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Selecting text was removed from the default reader, you can only select text if Render HTML is on.

**Comment by ukc895** [comment]
Turning this on would bring new features like text Highlighter, comments on the sentence. Which are useful for reference in the later times.

**Comment by ukc895** [comment]
After turning it on, I am able to select text. But my needs are additional features.

**Comment by rajarsheechatterjee** [comment]
Create separate issues for enhancements.
