### ISSUE TITLE
ReaperScans Issues

### ISSUE THREAD

**Issue by Xeiniac** [LNReader/lnreader#415]
### Steps to reproduce

Case 1 Browse:
1. Browse the source
2. Scroll

Case 2 Latest:
1. Click latest on the source
2. Scroll

Case 3 Missing free & paid chapters:
1. Browse a series

### Expected behavior

Case 1 Browse:
Grabs all the series from https://reaperscans.com/all-series/novels/ and shows them.

Case 2 Latest:
Grabs all the series from https://reaperscans.com/all-series/novels/?m_orderby=latest and shows them

Case 3 Missing free & paid chapters: 
Shows all the chapters for the series including the paid chapters where purchased ones can be accessed by logging in through webview.

### Actual behavior

Case 1 Browse:
Its shows couple of series and then repeats them.

Case 2 Latest: 
It still shows the same series as browse and they also repeat.

Case 3 Missing free & paid chapters:
It only shows chapters for one or two series which others are shown as 0 chapters. Paid chapters aren't shown at all.

### LNReader version

1.1.12

### Android version

Android 12

### Device

Samsung Galaxy Tab S5e

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.12](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with an source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
