### ISSUE TITLE
Readlightnovel search not functioning

### ISSUE THREAD

**Issue by XiaF0x** [LNReader/lnreader#417]
### Steps to reproduce

Go to search for readlightnovel and search for anything

### Expected behavior

The search searches

### Actual behavior

It doesnt :(

### LNReader version

1.1.12

### Android version

11

### Device

Z fold

### Other details

The search function just shows the default page for the readlightnovel source
![Screenshot_20220826-205100_LNReader](https://user-images.githubusercontent.com/88056797/187009801-632afcc6-7207-4011-bcfd-bd45a1001d02.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.12](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
LNReader/lnreader-sources#371
