### ISSUE TITLE
Fix Release date

### ISSUE THREAD

**Issue by Solovertical** [LNReader/lnreader#418]
### Steps to reproduce

On opening Ltnovel.com 

### Expected behavior

It should show release date frequently 
![Screenshot_2022-08-31-17-01-15-940_com rajarsheechatterjee LNReader](https://user-images.githubusercontent.com/109901807/187669029-06ce1f94-3e42-4bab-a392-5a6a1894360f.png)

### Actual behavior

It's showing date when the ch release

### LNReader version

1.1.12

### Android version

10

### Device

Mi

### Other details

Ltnovel.com it's a good extension ,Please fix this , There are very few extensions where I got this great novel.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.12](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with an source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
