### ISSUE TITLE
KolNovel(arabic) Source doesn't work

### ISSUE THREAD

**Issue by BenaliAziz** [LNReader/lnreader#419]
### Steps to reproduce

![Screenshot_20220901-143121_LNReader](https://user-images.githubusercontent.com/111535060/187926940-7e9fb842-3bb9-41c6-8fee-8f19107d3f2e.jpg)

### Expected behavior

This should fixed 

### Actual behavior

Same thing

### LNReader version

1.1.12

### Android version

Android 11

### Device

I don't know what's this

### Other details

![Screenshot_20220901-143814_LNReader](https://user-images.githubusercontent.com/111535060/187928056-babd05d3-3e19-4367-a115-35c5df15b75d.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.12](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with an source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
