### ISSUE TITLE
Restoring backup is stuck.

### ISSUE THREAD

**Issue by MrUNKNOWNN7** [LNReader/lnreader#422]
Hi bro! How have you been? I just wanted to let you know, that the latest update is getting stuck while I am restoring my backup. It goes slow, but well during the the initial stages, but get's stuck at the final stages. Hope it's not Android 12 issue, and can be fixed. Thank you.

**Comment by rajarsheechatterjee** [comment]
Does restoring backup work for you in previous versions?

**Comment by MrUNKNOWNN7** [comment]
If we are talking about LNReader previous version, I tried it when I started facing this issue, but that still got stuck. My device recently got A12 update, So wasn't in need for reinstall or checking whether the backup was working or not. But when I had to reset my device, I tried the latest version to restore my backup and here we are.

P.S - As far as I remember, in A11 the backup feature was working flawlessly and was pretty damm fast as well. And in A12, it take ages if you have a large library.

**Comment by rajarsheechatterjee** [comment]
It's probably happening because a source of your backup's novel might be broken.

**Comment by MrUNKNOWNN7** [comment]
That sounds like a valid reason. Well, thanks anyway for looking into it.

**Comment by nyagami** [comment]
This is because of wrong path in app cache's dir, for some reason.
