### ISSUE TITLE
Can't find novels that are actually available.

### ISSUE THREAD

**Issue by MrUNKNOWNN7** [LNReader/lnreader#426]
Hi bro! I know you are already working on the bug I reported earlier, but please hear me out. I was looking for a perticular novel, but It wouldn't show up. Even if the website actually has it, it wouldn't show up in the search. The search results I would actually get is also a lot lower than previous version.

**Comment by rajarsheechatterjee** [comment]
Open source related issues in the [sources repo](https://github.com/LNReader/lnreader-sources/issues) and follow the issue template.
