### ISSUE TITLE
[Bug] Left to right/right to left swipe gesture doesn't work properly

### ISSUE THREAD

**Issue by seizue** [LNReader/lnreader#43]
[![Left to Right gesture doesn't work properly](https://res.cloudinary.com/marcomontalbano/image/upload/v1625209240/video_to_markdown/images/streamable--qhwhns-c05b58ac6eb4c4700831b2b3070cd403.jpg)](https://streamable.com/qhwhns "Left to Right gesture doesn't work properly")

**Comment by nyagami** [comment]
I think this bug is actually a slow responding

**Comment by nyagami** [comment]
@rajarsheechatterjee  this should be resolved by #538
