### ISSUE TITLE
AI Reading voice costumizations 

### ISSUE THREAD

**Issue by fazecasdavid** [LNReader/lnreader#433]
### Describe your suggested feature

I think it would be awesome to add a few more options for the AI reading voice (different voices maybe some more natural, ability to costumize reading speed, ability to start the reader from anywhere in the chapter)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.13](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by dantetdc8** [comment]
You can customize the voice, pitch and speed in the screen reader options of your phone. It works on Android 12. Go to settings > general settings > text to speech and you will see the options there.
