### ISSUE TITLE
WuxiaWorld / LightnovalReader Broken

### ISSUE THREAD

**Issue by DtrixHD** [LNReader/lnreader#435]
Both sources are broken. 

WuxiaWorld: Findes novals but by opening the novals have 0 Chapters, no summery.

Lightnovalreader: Is completely blank

App Version Stable 1.1.13 (02.09.2022 08:00 AM)
Phone Nubia Red Magic 6S pro Android 11

**Comment by DtrixHD** [comment]
Update content of chapters in the source lightnovalreader are back.

**Comment by rajarsheechatterjee** [comment]
Open source related issues in the [sources repo.](https://github.com/LNReader/lnreader-sources/issues) and follow the issue template.
