### ISSUE TITLE
[Source Request] Tapas

### ISSUE THREAD

**Issue by semiya5** [LNReader/lnreader#438]
### Describe your suggested feature

I realize it may be a bit difficult to add, but I'd like to read from Tapas in the app. Maybe the same way as Tachi of having the locked chapters show a lock and using WebView to see all unlocked chapters, if possible.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.13](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).

There's already an open issue for it.
