### ISSUE TITLE
Where I can download the app? I forgot 

### ISSUE THREAD

**Issue by Newbie-Here** [LNReader/lnreader#441]
### Describe your suggested feature

Could you just give the exact site to download the latest version and different site for the reviews of changes I Don't Know Where Exactly to download the app

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.13](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
There's no site, all the releases and their changelogs are in the [release section](https://github.com/LNReader/lnreader/releases).
