### ISSUE TITLE
Track and highlight the paragraph and remember the last line when using read aloud

### ISSUE THREAD

**Issue by Skoppy2** [LNReader/lnreader#442]
### Describe your suggested feature

Track and highlight the paragraph and remember the last line when using read aloud so i don't lose focus and start from the last line when opening the app again

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.13](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
implemented in v2 app
