### ISSUE TITLE
readwn books cannot be accessed

### ISSUE THREAD

**Issue by lnreaderReadwn** [LNReader/lnreader#443]
### Steps to reproduce

1. In the app go to Browse, input "Versatile Mage" (or any novel of your choice).
2. Go to search results of Readwn.com

### Expected behavior

"Versatile Mage" is displayed.

### Actual behavior

"No results found" is displayed.

### LNReader version

1.1.13

### Android version

Android 12

### Device

Samsung Galaxy A52 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.13](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
