### ISSUE TITLE
add All Novel Download after backup from 1 device to another device, if possible.

### ISSUE THREAD

**Issue by afat123** [LNReader/lnreader#444]
### Describe your suggested feature

after the backup is restored and done, all of the novels are not downloaded. 
and i have too many novels in my library that download 1 title by 1 title gets tiring.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.13](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
done in https://github.com/LNReader/lnreader/pull/659

**Comment by nyagami** [comment]
implemented in 2.0 version
