### ISSUE TITLE
Deleting novels

### ISSUE THREAD

**Issue by AexaMK** [LNReader/lnreader#445]
### Steps to reproduce

You add a novel,read some chapters, everything is normal.You open the app next time make an update,the novel isn't there anymore.

### Expected behavior

I expect that after the update the novels to be there.

### Actual behavior

I found the novels again,on the same source so I added it again and again after the update some other novel disappeared.

### LNReader version

1.1.13

### Android version

Android 12

### Device

Xiaomi 11T

### Other details

Also if I let the app running in the background it doesn't update.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.13](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
Not able to reproduce. Reopen if it still happens in beta version.
We stop working on 1.x.x versions
