### ISSUE TITLE
[Feature request] Add volume button scroll amount 

### ISSUE THREAD

**Issue by SkillGG** [LNReader/lnreader#447]
### Describe your suggested feature

Because it scrolls 100% it may be a bit too much for someone who wants to see the last line of the previous "page". Or it may help with over-scroll on some devices. 

Also I like to be able to only half-scroll the screen.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.13](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by r1di** [comment]
I got the code almost done, i will be creating a pull request soon, but since its my first time programming in typescript, im not sure if its ok.
