### ISSUE TITLE
[Feature Request] add Categories

### ISSUE THREAD

**Issue by seizue** [LNReader/lnreader#45]
add categories (similar to tachiyomi but for organizing novels on library)

![Screenshot_2021-07-06-12-07-23-75](https://user-images.githubusercontent.com/25120376/124547938-89cb6600-de5f-11eb-877b-5b029db1ccf3.jpg)

I have 215 novels in my library so adding categories will be helpful
also just found out the update today. thank you for the hard work

**Comment by Philii** [comment]
option to switch off update check for certain category (tab).
like update include this tab or exclude this tab or default

**Comment by Rojikku** [comment]
+1 on this. The ability to change settings like auto download based on category would be a plus, but just the category feature so I can easily have a list of what I'm reading, and what I'm saving for later, would be glorious.
