### ISSUE TITLE
Fonts request

### ISSUE THREAD

**Issue by Humam-Hamdan** [LNReader/lnreader#456]
# Font 1:
Libre Baskerville 
Google fonts link:
    https://fonts.googleapis.com/css2?family=Libre+Baskerville

# Font 2:
Cinzel Decorative
Google fonts link:
https://fonts.googleapis.com/css2?family=Cinzel+Decorative

# Font 3:
Dancing Script
Google fonts link:
https://fonts.googleapis.com/css2?family=Dancing+Script

**Comment by rajarsheechatterjee** [comment]
Since the default Text reader was removed these can already be added using custom CSS.
