### ISSUE TITLE
possible to add searching chapter number?

### ISSUE THREAD

**Issue by afat123** [LNReader/lnreader#460]
is it possible to add that feature?
because sometimes, some of the chapters are too many, that if you read on PC as well on the app, theres a chance to forgot the chapter or, remember, but have to scroll too long to find it. (if the novel has 1000+ chapters, this can happen)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.13](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
There's already an option to search chapter number or name.

![Screenshot_2022-10-29-22-21-00-64_3c1c179116822eec69c21805387f0489.jpg](https://user-images.githubusercontent.com/57822170/198843581-07d296b3-d673-47ea-a508-a38c09bcb0f9.jpg)

**Comment by afat123** [comment]
oh F. i forgot about that symbol.
sorry for the quesiton then...
