### ISSUE TITLE
[F-R] Epub Export

### ISSUE THREAD

**Issue by Humam-Hamdan** [LNReader/lnreader#467]
### Describe your suggested feature

The Option to export the downloads to an epub file, which would make the read on other devices (i.e. kindle) much easier.

### Other details

Like what ranobe has for example

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.13](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Duplicate of #38

**Comment by Humam-Hamdan** [comment]
@rajarsheechatterjee isn't #38 about "importing" existing epub files and not "exporting what I downloaded"?

**Comment by rajarsheechatterjee** [comment]
> @rajarsheechatterjee isn't https://github.com/LNReader/lnreader/issues/38 about "importing" existing epub files and not "exporting what I downloaded"?

I thought the old ticket was about all kinds of EPUB support. I can reopen this one just to track the export feature.

**Comment by Humam-Hamdan** [comment]
Thanks :), that's what made me open this

> Request local epub support as that would allow readers to access their personal collections.

and

> placed a local file option
