### ISSUE TITLE
Every download is corrupted

### ISSUE THREAD

**Issue by vehosah** [LNReader/lnreader#468]
### Steps to reproduce

1. Press the download
2. Wait for the download to happen
3. Open the download and novel that you downloaded 

### Expected behavior

It should happen to read the novel that I downloaded 

### Actual behavior

But instead I downloaded a corrupt picture 

### LNReader version

1.1.13

### Android version

Android 12 

### Device

Nokia 5.4 

### Other details

It happens on every single source 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.13](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
The steps to reproduce aren't helpful as downloads work fine for me. 

Open another issue and mention the source, novel and chapter name in details or share a screen recording of the issue.

**Comment by vehosah** [comment]
I uploaded the video you wanted, all the sources have the same, all the novels have the same problem and all the chapters have the same problem

**Comment by rajarsheechatterjee** [comment]
> I uploaded the video you wanted

Where?

> all the sources have the same, all the novels have the same problem and all the chapters have the same problem

This isn't helpful as the source I tried to reproduce this are working fine, so mention the exact names.

**Comment by vehosah** [comment]
i can't upload the video because its too big

**Comment by vehosah** [comment]
i tried 1stkissnovel,comrademao,i trie lightnovelupdates

**Comment by vehosah** [comment]
https://mega.nz/file/KQ1zXSKa#U8hdiWmvue0m9-Vfs_vZ3sVSZXrPw0X70CqlAPhtuWw there is the video also

**Comment by rajarsheechatterjee** [comment]
> https://mega.nz/file/KQ1zXSKa#U8hdiWmvue0m9-Vfs_vZ3sVSZXrPw0X70CqlAPhtuWw there is the video also

Those aren't the downloads, they are just the dowloaded images present in the chapters in a different format. 

You can't access the downloads outside the app as they are stored in a SQLite database.

**Comment by vehosah** [comment]
oh i didn't knew that,sorry
