### ISSUE TITLE
Source broken

### ISSUE THREAD

**Issue by MonomoySama** [LNReader/lnreader#474]
### Steps to reproduce

1. Open The source
2. Images not loading even in high speed net

### Expected behavior

I opened 1stkissnovel source but the images are not loading even after sometime

And 2nd problem is LightNobelPub isn't working. Fix that source.

3rd problem there are so few Light Novels in this app. I can find mostly Web Novels. I can't find my favorite Light Novels e.g. Reincarnated as a slime

### Actual behavior

This app is called LNreader so there has to be light novels besides web novel too and sources are not for left broken i think

### LNReader version

1.1.13

### Android version

Android 10

### Device

Realme 7 Pro

### Other details

This app can be much more greater if just some things are fixed ASAP. Thank you

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.13](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> I opened 1stkissnovel source but the images are not loading even after sometime

This is due to their image links being behind Cloudflare which the app cannot bypass.

> And 2nd problem is LightNobelPub isn't working. Fix that source.

Wait for someone to fix it or feel free to fix is yourself and contribute.

> 3rd problem there are so few Light Novels in this app. I can find mostly Web Novels. I can't find my favorite Light Novels e.g. Reincarnated as a slime

> This app is called LNreader so there has to be light novels besides web novel too and sources are not for left broken i think

The name of the app has nothing to do with the content inside.
