### ISSUE TITLE
KolNovel dosent work

### ISSUE THREAD

**Issue by BenaliAziz** [LNReader/lnreader#477]
### Steps to reproduce

![Screenshot_20221122-194427_LNReader](https://user-images.githubusercontent.com/111535060/203397837-88ed9814-dfa4-4203-b7b9-f54a93faa48d.jpg)
![Screenshot_20221122-195516_LNReader](https://user-images.githubusercontent.com/111535060/203397969-f9b1900f-e483-40dc-b9e6-0eac8d6d4ced.jpg)

### Expected behavior

Anything 

### Actual behavior

Same thing 

### LNReader version

1.1.13

### Android version

Android 11

### Device

I don't know what's this (android)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.13](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
