### ISSUE TITLE
Add security feature

### ISSUE THREAD

**Issue by SuperDuperNoob** [LNReader/lnreader#479]
### Describe your suggested feature

Here's an example 

![touchmaster_20221125-52518](https://user-images.githubusercontent.com/17029875/203979390-f74bc1e5-6199-43b5-9409-15dacfa128e9.jpeg)

### Other details

Can you add athis features? At least a "Secure Screen" features.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.13](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Duplicate of #253
