### ISSUE TITLE
Text to speech causes screen to freeze

### ISSUE THREAD

**Issue by sjain3097** [LNReader/lnreader#484]
### Steps to reproduce

After clicking on speaker button for the text to speech the screen freezes and can't browse the app for a few minutes

### Expected behavior

Screen should freeze

### Actual behavior

Screen shouldn't freeze after text to speech 

### LNReader version

1.1.13

### Android version

Android 11

### Device

Redmi note 8 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.13](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Should be resolved by #530
