### ISSUE TITLE
Cannot read property 'Replace' of null

### ISSUE THREAD

**Issue by tehchy123** [LNReader/lnreader#487]
###
![Screenshot_20221206-065836_LNReader](https://user-images.githubusercontent.com/109418510/205731513-ae299362-d8ca-4940-a54a-6d534cdec89f.jpg)
 Steps to reproduce

1. After opening the app, tap the compass button
2. Select "Ranobes"
3. Search "Classroom of the elite"
4. Open the only option that matches exactly

### Expected behavior

The classroom of the elite Nobel should appear with the default chapter select display 

### Actual behavior

Blank screen other than the options at the top and a loading screen 

### LNReader version

1.1.13

### Android version

12

### Device

Samsung Galaxy a23 5G (SM-A236E/DSN)

### Other details

Tried with other methods that failed as well. Worked on older Samsung Galaxy S4 on android 5.0.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.13](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
