### ISSUE TITLE
App just Freeze for few seconds after updating a novel

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader#494]
### Steps to reproduce

1. Update any novel
2. Navigate back to library 

### Expected behavior

App should work normally and should allow to scroll or slide and go to different tabs

### Actual behavior

App just Freezes for few seconds or until it update the noval unread status 

### LNReader version

1.1.13

### Android version

11

### Device

Realme 3 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.13](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Not able to reproduce this issue, the app works normally for me in this case.

Reopen if the issue still persists.
