### ISSUE TITLE
Novel won't update its chapter in one reload 

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader#495]
### Steps to reproduce

1. Click on a novel in library
2. Scroll down from top to update it

### Expected behavior

If there are new chapter it should show the new chapter 

### Actual behavior

But it is not showing if there are new chapter on first reload i have to reload it again then it would show if there are any new updates

But if i reload it only one time and navigate to Library then the app would freeze until the reloaded novel update it's status

### LNReader version

1.1.13

### Android version

Android 11

### Device

Realme 3 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.13](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Not able to reproduce this issue, as new updates are showing up fine on first reload.

Reopen if the issue still persists and add more detailed steps to reproduce the issue.

**Comment by Diviance** [comment]
As an addendum to this, I experience the same thing.  My Android version is 13.  Samsung Galaxy Tab S7+.

If I open a novel and slide down to tell it to "update" the novel from the info screen... the new chapters will not show up until I leave the novel info screen back to the main screen and go back in to the novel info.

If I am reading the novel and an update runs and new chapters are found, they also do not show up until I leave the novel back to the main screen and go back in to the novel info.

This happens with any novel I have, the source does not appear to matter (BoxNovel does it, Ltnovel.com does it, ReadLightNovel does it).

**Comment by Pheonix-Flames** [comment]
> As an addendum to this, I experience the same thing. My Android version is 13. Samsung Galaxy Tab S7+.
> 
> If I open a novel and slide down to tell it to "update" the novel from the info screen... the new chapters will not show up until I leave the novel info screen back to the main screen and go back in to the novel info.
> 
> If I am reading the novel and an update runs and new chapters are found, they also do not show up until I leave the novel back to the main screen and go back in to the novel info.
> 
> This happens with any novel I have, the source does not appear to matter (BoxNovel does it, Ltnovel.com does it, ReadLightNovel does it).

Do you have lots of Novel in your library?

**Comment by Pheonix-Flames** [comment]
> Not able to reproduce this issue, as new updates are showing up fine on first reload.
> 
> Reopen if the issue still persists and add more detailed steps to reproduce the issue.

It might be because I have lots of Novel in my library. Can you add 40 or 50 novel in your library and then try this again

I have 2000+ Manga in my Tachiyomi App and it takes a while to load all the manga it might be the same with LNReader

**Comment by Diviance** [comment]
> > As an addendum to this, I experience the same thing. My Android version is 13. Samsung Galaxy Tab S7+.
> > If I open a novel and slide down to tell it to "update" the novel from the info screen... the new chapters will not show up until I leave the novel info screen back to the main screen and go back in to the novel info.
> > If I am reading the novel and an update runs and new chapters are found, they also do not show up until I leave the novel back to the main screen and go back in to the novel info.
> > This happens with any novel I have, the source does not appear to matter (BoxNovel does it, Ltnovel.com does it, ReadLightNovel does it).
> 
> Do you have lots of Novel in your library?

I have 22 novels.

**Comment by Pheonix-Flames** [comment]
> Not able to reproduce this issue, as new updates are showing up fine on first reload.
> 
> Reopen if the issue still persists and add more detailed steps to reproduce the issue.

Add 40-50 novels in your library and create 6-7 catagory and divide all the novel in the categories and open lots of Novel so you can also fill your history tab than try to open a novel and refresh it and come back to Library and check if the app Freezes
