### ISSUE TITLE
ComradeMao doesn't pick up English translation

### ISSUE THREAD

**Issue by Yalg-0** [LNReader/lnreader#498]
### Steps to reproduce

Open any random chap in ComradeMao

### Expected behavior

There is some kind of protection from parsing and from some ip's

### Actual behavior

ComradeMao source doesn't pick up English translation
Chinese symbols are visible

### LNReader version

1.1.13

### Android version

10

### Device

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.13](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
