### ISSUE TITLE
Source Errors 

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader#501]
### Steps to reproduce

1. Click on Browse tab
2. Open any source mentioned in the given screenshot such as DaoNovel

### Expected behavior

It should show its front page with all the novels loaded 

### Actual behavior

It is showing 'No results found'

### LNReader version

1.1.13.1

### Android version

Android 11

### Device

Realme 3 pro

### Other details

They are all the non working Sources:

![Screenshot_2022-12-22-01-11-36-24_3c1c179116822eec69c21805387f0489](https://user-images.githubusercontent.com/105352597/208990824-c1a1db9b-d299-47af-8ab8-5af17887740d.jpg)
![Screenshot_2022-12-22-01-11-25-79_3c1c179116822eec69c21805387f0489](https://user-images.githubusercontent.com/105352597/208990830-08b240d0-be2c-4a1a-9f07-a9638a5ea630.jpg)
![Screenshot_2022-12-22-01-11-11-96_3c1c179116822eec69c21805387f0489](https://user-images.githubusercontent.com/105352597/208990837-0bc01d87-8a08-4329-918e-d70c4636ea84.jpg)
![Screenshot_2022-12-22-01-11-08-09_3c1c179116822eec69c21805387f0489](https://user-images.githubusercontent.com/105352597/208990842-a3fe0215-5a3c-4c5e-b2d8-b7e699c98dab.jpg)
![Screenshot_2022-12-22-01-10-30-18_3c1c179116822eec69c21805387f0489](https://user-images.githubusercontent.com/105352597/208990846-ab7e6559-2d02-4bef-863f-2b7d061757a3.jpg)
![Screenshot_2022-12-22-01-10-19-82_3c1c179116822eec69c21805387f0489](https://user-images.githubusercontent.com/105352597/208990853-43dcb968-c2e1-4fb3-9866-2c89153d94f8.jpg)
![Screenshot_2022-12-22-01-10-13-01_3c1c179116822eec69c21805387f0489](https://user-images.githubusercontent.com/105352597/208990859-f31ac314-b608-4e39-beb2-9896f084491b.jpg)
![Screenshot_2022-12-22-01-09-52-92_3c1c179116822eec69c21805387f0489](https://user-images.githubusercontent.com/105352597/208990864-660a492e-0a40-433b-a988-0c8338788913.jpg)
![Screenshot_2022-12-22-01-09-48-07_3c1c179116822eec69c21805387f0489](https://user-images.githubusercontent.com/105352597/208990867-8b8bf1ef-a230-4554-b694-533cb0525e94.jpg)
![Screenshot_2022-12-22-01-09-39-39_3c1c179116822eec69c21805387f0489](https://user-images.githubusercontent.com/105352597/208990871-0e6ed8cd-472e-48a0-976c-a68bcefcd3c4.jpg)
![Screenshot_2022-12-22-01-09-10-71_3c1c179116822eec69c21805387f0489](https://user-images.githubusercontent.com/105352597/208990876-65ec429f-632f-4740-a19c-b6d548f483d1.jpg)
![Screenshot_2022-12-22-01-09-05-87_3c1c179116822eec69c21805387f0489](https://user-images.githubusercontent.com/105352597/208990878-26925141-f647-4d2e-b6ea-84eb514a456c.jpg)
![Screenshot_2022-12-22-01-08-53-79_3c1c179116822eec69c21805387f0489](https://user-images.githubusercontent.com/105352597/208990880-1277c43c-498a-4c92-b172-9cbe9343ddda.jpg)
![Screenshot_2022-12-22-01-08-44-07_3c1c179116822eec69c21805387f0489](https://user-images.githubusercontent.com/105352597/208990881-3a2e070d-00ee-4238-8121-482603296352.jpg)
![Screenshot_2022-12-22-01-08-36-89_3c1c179116822eec69c21805387f0489](https://user-images.githubusercontent.com/105352597/208990887-8e6b1e0c-6736-4374-8b64-4571fae1076d.jpg)
![Screenshot_2022-12-22-01-08-21-98_3c1c179116822eec69c21805387f0489](https://user-images.githubusercontent.com/105352597/208990891-6e3a7d4d-3d7f-4336-aa02-d7eab1a37c5e.jpg)
![Screenshot_2022-12-22-01-08-03-22_3c1c179116822eec69c21805387f0489](https://user-images.githubusercontent.com/105352597/208990892-4a3ad9c1-169c-4d25-8770-62969f4e49f8.jpg)
![Screenshot_2022-12-22-01-08-28-83_3c1c179116822eec69c21805387f0489](https://user-images.githubusercontent.com/105352597/208990894-4a2204d2-8753-4bd3-9fde-7f5ccbcfbed1.jpg)
![Screenshot_2022-12-22-01-07-40-25_3c1c179116822eec69c21805387f0489](https://user-images.githubusercontent.com/105352597/208990899-21deea74-79c6-4d3c-a35a-cfdd2c1f477e.jpg)
![Screenshot_2022-12-22-01-07-32-70_3c1c179116822eec69c21805387f0489](https://user-images.githubusercontent.com/105352597/208990904-e78d2a87-78e2-463d-aea8-2c1f5e2d7848.jpg)
![Screenshot_2022-12-22-01-07-20-62_3c1c179116822eec69c21805387f0489](https://user-images.githubusercontent.com/105352597/208990910-a542c3ba-09d3-4d12-90b3-68bfc5b240b6.jpg)
![Screenshot_2022-12-22-01-07-10-52_3c1c179116822eec69c21805387f0489](https://user-images.githubusercontent.com/105352597/208990915-65f6d196-36cf-4f52-a65b-1fb67dfca665.jpg)
![Screenshot_2022-12-22-01-07-27-14_3c1c179116822eec69c21805387f0489](https://user-images.githubusercontent.com/105352597/208990920-5de6b678-b929-4220-a257-d4da6d1a2888.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.13](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).

Most of these have already have open individual issues.
