### ISSUE TITLE
Only Displays the 1st Page Of Search Result 

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader#502]
### Steps to reproduce

1. Open a source such as Ltnovel or readwn
2. Search a common word such as Immortal
3. Go to the last result and read its name
4. Go to Webview then input the same search item (immortal) 
5. Then go to last result of the search page
6. You will see the Last result in app and the last result in web view's 1st page are the same

### Expected behavior

After Searching a item in the source it should load all the pages in the search result not just first page

### Actual behavior

It is only loading and display the results of first page of the website 

### LNReader version

1.1.13

### Android version

Android 11 

### Device

Realme 3 pro 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.13](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
I think this should be a feature request: implement page number for searchNovels

**Comment by nyagami** [comment]
Implemented in 2.0 version

**Comment by nyagami** [comment]
You can try v2 beta or wait for its stable release
