### ISSUE TITLE
App Is lagging 

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader#507]
### Steps to reproduce

Read any novel and click on next chapter button at the end of the chapter

### Expected behavior

It should open next chapter 

### Actual behavior

I have to click multiple time then the button will work or if i press it only one it will open next chapter in 3-4 sec

### LNReader version

1.1.13

### Android version

Android 11 

### Device

Realme 3 pro

### Other details

At first when i was using LNReader it was working fine but after i added many novels and
7-8 categories it started to become laggy .
Make the app more stable

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.13](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
There isn't a single fix for performance issues, it'll eventually get better.

**Comment by Pheonix-Flames** [comment]
> There isn't a single fix for performance issues, it'll eventually get better.

Let me send you a screen recording
