### ISSUE TITLE
Give us options to install extensions

### ISSUE THREAD

**Issue by SGthecoder** [LNReader/lnreader#511]
### Describe your suggested feature

Give us options to install extensions because searching in all extension consumes a lot of data so please give us options to install extensions and use the extension that we like

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.13](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
You can pin the sources you want to use and turn off search all sources in global settings and the app would only search pinned sources.

> Give us options to install extensions because searching in all extension consumes a lot of data so please give us options to install extensions and use the extension that we like

This isn't possible as there's no way to implement external sources in React Native. There's already an open issue (#166) for it.
