### ISSUE TITLE
Extension not working 

### ISSUE THREAD

**Issue by SGthecoder** [LNReader/lnreader#512]
### Steps to reproduce

Light novel pub extension not working 

### Expected behavior

I think I should able to see novels in lightmovel pub and read and download but it doesn't show any of it

### Actual behavior

As i open the extension it just shows no results found

### LNReader version

1.1.13

### Android version

11

### Device

Xiaomi 11i 5g 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.13](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).

**Comment by SGthecoder** [comment]
> > If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).

Ok done
