### ISSUE TITLE
Support Categories in Backup 

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader#518]
### Steps to reproduce

1. Create a backup
2. Reinstall LNReader
3. Restore the backup 

### Expected behavior

It should backup all the catagories and the Novel in them and their read status 

### Actual behavior

It is only restoring the novels not their catagories and there status 

### LNReader version

1.1.13

### Android version

Android 11

### Device

Realme 3 pro

### Other details

I had 60-70 novels and now every this is ruined 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.13](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
done in https://github.com/LNReader/lnreader/pull/659
