### ISSUE TITLE
BackUp In Drive Or Mega Support

### ISSUE THREAD

**Issue by Roaqe** [LNReader/lnreader#522]
### Describe your suggested feature

Instead of saving file in device directly add a Feature to button to directly save the backup file in **Drive** or **Mega** or Anyother Backup services

### Other details

Add Options of open-source cloud Storage platforms if possible or A feature to directly share the backup file to anyone in any app that supports send option

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.14](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
We now have https://github.com/LNReader/lnreader/pull/659 - Backup in your own PC. 

And I think backup in other Cloud Storage is difficult. Because backup action may make a ton of request or a super big size of data  that Cloud Service usually require some $ to unlock

**Comment by nyagami** [comment]
Google Drive backup is implemented in 2.0 version

**Comment by Palloxin** [comment]
If someone close this issue..
