### ISSUE TITLE
Touch issue

### ISSUE THREAD

**Issue by jvangat17** [LNReader/lnreader#526]
after updating to 1.1.14 . 
when i try to alt tab for few secs/minutes(checking twitter or fb)

the touch is not responding on lower part of the screen.

**Comment by jvangat17** [comment]
https://drive.google.com/file/d/1rqY3DMAeqkBCRF1YLRc0XrIPrDH2Zi4B/view?usp=drivesdk

starting 00:30 i tried scrolling on the bottom part of the screen but it wont scroll down or up. but when i tried to touch and scroll around the middle of screen. it will scroll.

**Comment by rajarsheechatterjee** [comment]
Open a new issue and follow the issue template.
