### ISSUE TITLE
Link doesn't work 

### ISSUE THREAD

**Issue by I-feel-empty-for-no-reason0** [LNReader/lnreader#536]
### Steps to reproduce

Kolnovel.com doesn't work

### Expected behavior

It should work

### Actual behavior

The link doesn't work 

### LNReader version

. 

### Android version

. 

### Device

. 

### Other details

. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.14](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
