### ISSUE TITLE
[Feature request] Self update of the app

### ISSUE THREAD

**Issue by VGFlash** [LNReader/lnreader#54]
Can you please add the feature of the app to self update whenever a new version is published.

**Comment by BreadGenie** [comment]
I don't get what you meant by self update but we already have a check for stable release and the app notifies whenever an update is released. You can download the .apk file directly from the pop up iirc.

**Comment by VGFlash** [comment]
No what I mean is whenever a new update comes out a notification gives an option to update the app andon clicking it  the app downloads the apk itself and installs it without any assistance.

**Comment by VGFlash** [comment]
> No what I mean is whenever a new update comes out a notification gives an option to update the app andon clicking it  the app downloads the apk itself and installs it without any assistance.

So no need to go to GitHub and download the file itself and then install the new apk.

**Comment by rajarsheechatterjee** [comment]
> No what I mean is whenever a new update comes out a notification gives an option to update the app andon clicking it the app downloads the apk itself and installs it without any assistance.

Automatically installing apps without user interaction isn't allowed for security reasons.
