### ISSUE TITLE
In some sources don´t see  the web view option when i read a chapter

### ISSUE THREAD

**Issue by AtreussOT** [LNReader/lnreader#555]
### Steps to reproduce

in foxaholic, when i enter in a chapter from any novel, i don´t see a webview option

### Expected behavior

 I should be able to observe the webview option

### Actual behavior

 i don´t see a webview option

### LNReader version

1.1.14

### Android version

android 12

### Device

Redmi Note 10S

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.14](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
The WebView option in Reader is only available for Chapters which have their absolute url saved in db. So it's not possible to add it for existing sources without breaking the existing Novels in library.
