### ISSUE TITLE
Favorites disappearing in the library

### ISSUE THREAD

**Issue by Remielas** [LNReader/lnreader#567]
### Steps to reproduce

Sometimes your favorite LN/WN will disappear after you exiting and then starting it again

### Expected behavior

Normally, your favorite LN/WN will appear in your library

### Actual behavior

But it won't show and just say that you don't have anything in your library

### LNReader version

It's on ver. 1.1.14.

### Android version

Android 11

### Device

Realme 5i

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.14](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
Have you checked that the source of your favorite novel is still working properly

**Comment by rajarsheechatterjee** [comment]
@Remielas Could you add proper steps for reproducing the issue?

**Comment by rajarsheechatterjee** [comment]
Duplicate of #445
