### ISSUE TITLE
Escape symbols in Next Chapter button

### ISSUE THREAD

**Issue by satarov-ruslan** [LNReader/lnreader#573]
### Steps to reproduce

Open a chapter where the next one has a quote symbol in it

### Expected behavior

Quote symbol without the escaping

### Actual behavior

Escape backslash before the quote symbol
![Screenshot_20230307-165249](https://user-images.githubusercontent.com/42942835/223679527-8d3422c6-936e-4e27-b276-dbfb2e3ea422.jpg)

### LNReader version

1.1.14

### Android version

Android 10

### Device

OnePlus 5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [x] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.14](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Could you add the Source, Novel and Chapter name?

**Comment by satarov-ruslan** [comment]
@rajarsheechatterjee 
FirstKissNovel
True Martial World
For example, Chapter 1125: Ru'Er

**Comment by rajarsheechatterjee** [comment]
I see it's also present on the source website.

![Screenshot_2023-03-11-12-32-42-34_3c1c179116822eec69c21805387f0489.jpg](https://user-images.githubusercontent.com/57822170/224478466-8cabd0ce-ea3f-43cc-8bfb-33a80d9d5ba0.jpg)

**Comment by rajarsheechatterjee** [comment]
Closing since I feel the app should exactly display what's on the source website.
