### ISSUE TITLE
Update doesn't start

### ISSUE THREAD

**Issue by Remielas** [LNReader/lnreader#576]
### Steps to reproduce

Updating for new chapters doesn't work. It only says "update is already running" if you try to start the update even though it isn't running at all

### Expected behavior

Usually by pressing the update button, the update will start

### Actual behavior

But in this case, it says that there's already a running update

### LNReader version

It's on ver. 1.1.14.

### Android version

Android 10

### Device

Realme 5i

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.14](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Closing this issue as its stale.

You can reopen if the issue still persists.
