### ISSUE TITLE
random text 

### ISSUE THREAD

**Issue by abdogabal** [LNReader/lnreader#578]
### Steps to reproduce

the text in kolnovel Arabic extinction is random 

### Expected behavior

the text is same as the site 

### Actual behavior

random text 

### LNReader version

1.1.14

### Android version

android 10

### Device

redmi note 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.14](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
