### ISSUE TITLE
Novel adding Bug

### ISSUE THREAD

**Issue by MonomoySama** [LNReader/lnreader#580]
### Steps to reproduce

1. Adding a new novel from any extension
2. When coming to library, it's isn't there
3. When adding that same novel again, it appears in every category in library(categories i made)
4. If i remove that novel from any category, it removes from every other category too

### Expected behavior

When adding a novel in a certain category or just default library, the novel should go where i select only

### Actual behavior

The novel i was trying to add was "Night Ranger" from "AllNovelFull" extension

### LNReader version

1.1.14

### Android version

Android 10

### Device

Realme 7 Pro

### Other details

Please fix this issue ASAP...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.14](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Not able to reproduce this.

You can reopen if the issue still persists.
