### ISSUE TITLE
Illustration Request

### ISSUE THREAD

**Issue by MonomoySama** [LNReader/lnreader#581]
### Describe your suggested feature

I read many novels in this app, but there wasn't any illustrations in those.. even though they have illustrations in the chapters when i try download the EPUB/PDF ver. from any other site. Can you guys add the illustrations too? As i know it'll maybe bit difficult for you guys... Please

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.14](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
The app already supports showing illustrations in Render HTML mode. 

It could be an issue with the source, open an issue in the [sources repo](https://github.com/LNReader/lnreader-sources/issues).
