### ISSUE TITLE
Under the right conditions, "error: network request failed” warning is downloaded instead of chapter

### ISSUE THREAD

**Issue by redrhetoric** [LNReader/lnreader#582]
When this occurs, chapters will appear as downloaded, will not attempt download again, and accessing the chapter is impossible without deleting all chapters for the novel, even after Internet connection is restored.

I don't have exact reproduction steps, but it seems to happen occasionally when connection drops while chapters are downloading.

**Comment by Sosisksksk** [comment]
૮₍ ˃ ⤙ ˂ ₎ა "Network request failed" only appears for the stories I'm about to read.

**Comment by nyagami** [comment]
Fixed in https://github.com/LNReader/lnreader/commit/f0b8df93b4c396d8193ec6f94e33e88344cdd1c0
