### ISSUE TITLE
Volume scroll stops working when going to the next chapter

### ISSUE THREAD

**Issue by tobinstultiens** [LNReader/lnreader#585]
### Steps to reproduce

1. Open a chapter on any novel
2. Scroll to the bottom of the chapter using the volume keys (done by setting it to html render and enabling volume scrolls).
3. Press the next chapter.
4. Attempt to use the volume keys.

### Expected behavior

It should scroll using the volume keys.

### Actual behavior

It doesn't scroll and just functions as normal volume keys.

### LNReader version

1.1.14

### Android version

Android 13

### Device

Galaxy S22+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.14](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by SkillGG** [comment]
Related to #440

**Comment by tobinstultiens** [comment]
That is correct. will close the issue. (Probably only searched for volume scroll not buttons).
