### ISSUE TITLE
Changing background image

### ISSUE THREAD

**Issue by shrujalganatra** [LNReader/lnreader#586]
### Describe your suggested feature

I was wondering while I use custom CSS why doesn't it a!lows me to change background image 
Please help me with my issue I will like to make custom themes for myself thanks

And also if possible make a feature to import CSS file.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.14](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Adding background image in custom CSS used to work fine. Could you add the CSS you are using?


> And also if possible make a feature to import CSS file.

Should be possible.

**Comment by shrujalganatra** [comment]
![Screenshot_2023-03-30-19-13-49-097](https://user-images.githubusercontent.com/76093855/228855989-fe0fdc54-c2f3-442e-8373-11232c897b5a.jpeg)

body {
 background-image: url("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQteAMVTI70Y9gVQgU1CGbCd-k3dejWJ_HS6g&usqp=CAUj");
}
