### ISSUE TITLE
Bug "Enable javascript and cookies to continue"

### ISSUE THREAD

**Issue by B10Reaper** [LNReader/lnreader#590]
Novel works fine in the browser. Same source is working for other novels. All that is displayed on trying to read the novel is the text in the title. I've tried downloading the novel, clearing the cache from inside the app and outside, accessing it in the browser first, force stopping before clearing cache, so far nothing. I scrolled back a ways in the issues and didn't see any tricks to fix it. 
The specific novel this is hitting consistently on is "The Undead Great Sage Becomes the Elves’ Guardian!" Source is Novel Updates.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).

And follow the issue template.

**Comment by B10Reaper** [comment]
I don't know if it's a source issue that's why I posted it generally. If it was a source issue, I would assume all the novels would do that, wouldn't they?

**Comment by rajarsheechatterjee** [comment]
Novel Updates just redirects to the original sites so each novel could be from a different source.

**Comment by B10Reaper** [comment]
I didn't know that, thank you. I'll see if it's possible to narrow it down, otherwise I'll head over and open a source ticket. Thank you!
