### ISSUE TITLE
Unable to install update 

### ISSUE THREAD

**Issue by Anan5a** [LNReader/lnreader#592]
### Steps to reproduce

Download V1.1.15 from GitHub
Try to install 

### Expected behavior

Install app

### Actual behavior

Installation failed

### LNReader version

1.1.14

### Android version

Android 11

### Device

Realme X2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.14](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Closing since it doesn't seem like an app issue.

You can try installing Split APK installer from the [link](https://play.google.com/store/apps/details?id=com.aefyr.sai&hl=en_IN&gl=US) and installing the APK through that.
