### ISSUE TITLE
Latest update doesn't retain last read position

### ISSUE THREAD

**Issue by Razzemmatazz** [LNReader/lnreader#593]
### Steps to reproduce

Steps to repeat:
1) Open chapter, scroll down some
2) Back out to menus
3) Reopen chapter, it starts at the beginning again

### Expected behavior

When resuming reading a chapter, you should start from previous reading position

### Actual behavior

Chapter starts over at the beginning

### LNReader version

1.1.15

### Android version

11/13

### Device

Hisense Touch, Pixel 6

### Other details

I haven't had time to check out what changed, but if I have time tonight I'll see if I can get figure it out and push a fix. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.14](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
I am not able to reproduce this issue, it starts from the previous reading position.

Could you share a screen recording of the issue?

**Comment by Razzemmatazz** [comment]
Sure. 
https://drive.google.com/file/d/1Y2V9gn3PfKTu4O6CYrYheqgmaTeQO_h6/view?usp=drivesdk

**Comment by rajarsheechatterjee** [comment]
It seems to only happen for downloaded chapters.

**Comment by stepan323446** [comment]
Problem not fixed yet. Yes.  I checked, it's only for downloaded chapters

**Comment by Kellenerskine** [comment]
Read position also resets if you change the background color of the page.
