### ISSUE TITLE
Cannot restore backup in the new version.

### ISSUE THREAD

**Issue by Naironic** [LNReader/lnreader#594]
### Steps to reproduce

1. Press "Restore backup" and choose backup file.

### Expected behavior

Backup is restored.

### Actual behavior

After choosing the backup file it goes back to the "Backup" tab in the settings, and displays this error: "No resource found with the name /data/user/0/com.rajarsh..." (can't see the end of an error). No backup files I had worked, but after reinstalling 1.1.14 everything worked fine, so apparently this is an issue with the new version (1.1.15).
![Screenshot_20230407_210832_LNReader 1](https://user-images.githubusercontent.com/72698256/230675535-7394737c-4931-4fbf-b289-c7bfd8702c15.jpg)

### LNReader version

1.1.15

### Android version

13

### Device

Samsung S21+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.14](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
damn, I knew this error but i forgot to fix it in main branch

**Comment by Naironic** [comment]
> damn, I knew this error but i forgot to fix it in main branch

Just curious, when could it be fixed?

**Comment by nyagami** [comment]
> > damn, I knew this error but i forgot to fix it in main branch
> 
> Just curious, when could it be fixed?

I fixd it in anothẻ branch, not sure I will work on main branch
