### ISSUE TITLE
I couldn't see background  image

### ISSUE THREAD

**Issue by SGthecoder** [LNReader/lnreader#595]
### Steps to reproduce

Go to settings 
Reader 
Enable html reader
Now type custom css

body {
 background-image: url("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQteAMVTI70Y9gVQgU1CGbCd-k3dejWJ_HS6g&usqp=CAUj");
}

### Expected behavior

It should change the background 

### Actual behavior

Not changing background even after restarting the app

### LNReader version

1.1.15

### Android version

12

### Device

Samsung galaxy m01

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.15](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Pasting the exact CSS changes the background image for me. Are you able to access the image in WebView?

![Screenshot_2023-04-09-11-56-45-97_3c1c179116822eec69c21805387f0489.jpg](https://user-images.githubusercontent.com/57822170/230758107-a7f9f58e-ae0b-41d0-a2ab-1c5feea6e7d8.jpg)

**Comment by SGthecoder** [comment]
> Pasting the exact CSS changes the background image for me. Are you able to access the image in WebView?
> 
> ![Screenshot_2023-04-09-11-56-45-97_3c1c179116822eec69c21805387f0489.jpg](https://user-images.githubusercontent.com/57822170/230758107-a7f9f58e-ae0b-41d0-a2ab-1c5feea6e7d8.jpg)

Nope i cannot i think i should try re installing app ?

**Comment by rajarsheechatterjee** [comment]
> Nope i cannot i think i should try re installing app ?

If you can't access the image in WebView, it doesn't seem like an app issue. You could try using a different image / url.
