### ISSUE TITLE
Wrong default padding on 1.15 version

### ISSUE THREAD

**Issue by AnataBakka** [LNReader/lnreader#599]
### Steps to reproduce

Use text size 17 and text align center.
Compare the padding from version 1.14 to 1.15.

### Expected behavior

Padding should be the same as no change was expected.

### Actual behavior

Unknown behaviour causes padding to be larger on 1.15? causing the text to be more cluttered.

### LNReader version

1.1.15

### Android version

Android 11

### Device

Realme 6

### Other details

Even though i can change the padding through css, i still think this should be investigated so that the default padding doesn't randomly change from one patch to the other.

1.14
![Screenshot_2023-02-12-22-34-13-60_3c1c179116822eec69c21805387f0489](https://user-images.githubusercontent.com/78822218/230904540-5a03f655-c2ab-4de9-a6c2-e781cb57a368.jpg)

1.15
![Screenshot_2023-04-07-20-18-29-27_3c1c179116822eec69c21805387f0489](https://user-images.githubusercontent.com/78822218/230904659-73fb63b9-e4a3-4136-901d-aca1d99fa713.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.15](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by SkillGG** [comment]
This change happened because in 1.15 there is no non-HTML reader. In HTML Reader you can set padding to whatever you want it with custom CSS
```css
chapter {
  padding-inline: <value of new padding>;
}
```
Where value of new padding can be in any [CSS measurement unit](https://www.w3schools.com/cssref/css_units.php)
Negative values will make the margin smaller and text wider

**Comment by AnataBakka** [comment]
oh, thanks for the explanation.
can i do the same for the space between the separate lines of texts? i see that space has been reduced instead (reason for which, in my comparison, you can see more lines of text than before)

**Comment by SkillGG** [comment]
Yup. It's called line-height
https://developer.mozilla.org/en-US/docs/Web/CSS/line-height
You can add it below the padding like so:
```css
chapter {
 padding-inline: <size>;
 line-height: <size>;
}
```

**Comment by rajarsheechatterjee** [comment]
> Even though i can change the padding through css, i still think this should be investigated so that the default padding doesn't randomly change from one patch to the other.

The value of default padding is same, the default text reader was removed in this release and there's a slight difference for the same value in Text and HTML reader. So it won't change in every release.
