### ISSUE TITLE
Characters within a <> are cut and not displayed in normal view,  while the're in webview 

### ISSUE THREAD

**Issue by Zeznyipre** [LNReader/lnreader#602]
### Steps to reproduce

Go to source: novelpub

Go to novel: the author's pov

Go to chapter: midterms [3]

Read through the first bit then go to WebView and you'll notice that the rank characters <C> or anything inside a <> are missing

### Expected behavior

What should happen is that these characters should be displayed without having to go into WebView mode.

### Actual behavior

Anything inside of a <> is not displayed in normal view and only accessible in WebView 

### LNReader version

1.1.15 stable

### Android version

Android 13

### Device

Samsung A33

### Other details

Perhaps make an option to turn this on and off, as I think this was developed to remove the annoying (read this at ____) message

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.15](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Zeznyipre** [comment]
Well actually it's much easier to notice chapter Midterms [4] as the sentence that is Missing the characters is the 5th sentence

**Comment by DarioCastagnola** [comment]
I can confirm. I've also seen it while reading Mushoku Tensei. A lot of words are displayed as <>. Thought it was intended but then I've opened the web view and seen that the text was originally <<text here>> but it only displayed <>

**Comment by mgourment** [comment]
I have the same problem but in a multiple novels and sources: all <[something]> disepear like in the exemple below
![_20230512_104806](https://github.com/LNReader/lnreader/assets/46496555/9924a765-efc7-468e-8a9a-d2e265db91b1)
Became
![_20230512_104737](https://github.com/LNReader/lnreader/assets/46496555/69f4c55f-d5a8-4769-ad7a-d5ecdebadb98)
