### ISSUE TITLE
Novelhall crashed 

### ISSUE THREAD

**Issue by Mustafakhalifa258** [LNReader/lnreader#603]
Novelhall stopped responding and gives you have been blocked in book's title
![Screenshot_20230414-032252_LNReader](https://user-images.githubusercontent.com/112098073/231917173-959fd4f7-3167-4f7e-a00b-8ae5e77ec254.jpg)
![Screenshot_20230414-032228_LNReader](https://user-images.githubusercontent.com/112098073/231917176-d50e19eb-0afc-4ddf-8b6d-c6f1d47a5386.jpg)

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).

And follow the issue template.
