### ISSUE TITLE
Scribble hub extension

### ISSUE THREAD

**Issue by OMNITHORN** [LNReader/lnreader#604]
### Steps to reproduce

0 chapters in all novels
Whenever i enter a novel it has 0 chapters however whenever i use webview there are chapters but it doesn't show in LNreader

### Expected behavior

Example: World Keeper(novel)
In webview there are 940 chapters
However in LNreader there are 0

### Actual behavior

0 chapters

### LNReader version

1.1.15

### Android version

Android 12

### Device

Redmi 8a(custom rom)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.15](https://github.com/lnreader/lnreader/releases/latest)**.
- [x] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
