### ISSUE TITLE
Divine Dao Library source doesnt update new chapters

### ISSUE THREAD

**Issue by dailyfloof** [LNReader/lnreader#608]
### Steps to reproduce

1. Update library for new chapters with DDL source and updating through pulling down to update in novel.
2.  Doesn't add new chapter.

### Expected behavior

adding new chapters from the novel.

### Actual behavior

no new chaps added 

### LNReader version

1.1.15

### Android version

Android 12

### Device

LG Q90

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.15](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
