### ISSUE TITLE
LNreader freezes

### ISSUE THREAD

**Issue by EdelReid** [LNReader/lnreader#609]
Everytime I jump from LNreader app to another app in the background, or simply by putting the reader app in background, and coming back to it, freezes the app within seconds. After freezing, whenever I try to scroll up and down, the font size decreases considerably. 

I had to force close the app and restart everytime this happens. 

*edit- now I found out why this happens. Whenever, I return back to the reader app in the background, and enter full screen mode by hiding the bottom 3 navigation keys, this triggers the app freezing. 
So, now as long as I don't try to swipe down the dedicated navigation bar to enter the full screen, the app will function properly. 

### Expected behavior

-

### Actual behavior

Mentioned earlier 

### LNReader version

1.1.15

### Android version

Android 10

### Device

Honor 8x

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.15](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Could you share logs of when the app freezes? You can use [logcat](https://play.google.com/store/apps/details?id=com.dp.logcatapp).

**Comment by rajarsheechatterjee** [comment]
Closing this issue as its stale.

You can reopen if the issue still persists.
