### ISSUE TITLE
Nothing is shown

### ISSUE THREAD

**Issue by demon456blade** [LNReader/lnreader#612]
### Steps to reproduce

Open the app
Go to the different extension section
Click on reaper scans

### Expected behavior

There should be alot of different novels

### Actual behavior

Nothing is shown
![Screenshot_2023-04-27-23-26-45-405](https://user-images.githubusercontent.com/82254389/235047582-117121bf-16df-4d61-968d-26ecb33fa9c5.jpg)

### LNReader version

1.1.15

### Android version

Android 12

### Device

Red magic 7s pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.15](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).

**Comment by cactusoftheday** [comment]
Reaper scans has been through multiple overhauls now but I think they don't do novels anymore but only manhua and manhwa now.
