### ISSUE TITLE
A problem regarding Kolnovel source (arabic source)

### ISSUE THREAD

**Issue by Mishayui1** [LNReader/lnreader#614]
### Steps to reproduce

I have a problem when reading from Kolnovel source. When I click on a chapter it shows some random words between every paragraph.

As in this chapter for example:
![IMG_20230501_163544_545](https://user-images.githubusercontent.com/132284338/235482734-21a65119-95c3-4412-bbe2-e4ce35a9ad98.jpg)
The yellow lines are the actual text in the original site. But the blue lines are just random words between every paragraph that doesn't make any sense.

 This problem is not in the original source.

Here is the same chapter in the original site:
[Classroom of the elite ch 144](https://kolnovel.com/sclassroom-of-the-elitez-195640/) 

### Expected behavior

I want to read without these random words between paragraphs

### Actual behavior

This problem is with all novels from this source and all chapters.
I tried some other arabic sources and it was fine.

### LNReader version

1.1.15

### Android version

Android 8

### Device

SM - A260F

### Other details

I can't read from the other sources because I don't find the novels I want there. And also it's annoying to read from the original site because of the ads

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.15](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
