### ISSUE TITLE
Backup not working after uninstall and reinstall

### ISSUE THREAD

**Issue by Sinntax44** [LNReader/lnreader#633]
### Steps to reproduce

1. Uninstall the app
2. Reinstall
3. use the backup file created that I put in sd card > downloads > LN reader backup
4. App doesn't open file
5. Error message appears "No resource found with the name /data/user/0/com.rajarsheechatterjee.LNReader/cache/DocumentPicker/a5caef17-75cc-42a1-bfd4-d64ae8cc2da6.json
![346108121_1545089729350161_4685716039080636152_n](https://github.com/LNReader/lnreader/assets/79892857/13440c1a-b180-4062-a65b-808e1e4339ad)

### Expected behavior

App should be able to restore the everything that the backup file has

### Actual behavior

Error message occurs as stated above

### LNReader version

1.1.15

### Android version

Android 13

### Device

Oppo Reno 5 5G

### Other details

before this happened, i also got another issue that made the covers of my novels have blank cover page, blank description, and unknown author status
![346107115_1832855403774548_2385905707070185519_n](https://github.com/LNReader/lnreader/assets/79892857/cd7770a5-ab69-4e3e-bb00-0cf41decff17)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.15](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by FemiBlack** [comment]
Any update on this? Saw a similar issue, #594 which seems to be resolved

Or is this expected in the next release?

**Comment by Sinntax44** [comment]
> Any update on this? Saw a similar issue, #594 which seems to be resolved
> 
> Or is this expected in the next release?

It seems there's a 'fix' but it's on another branch. I don't want to switch in the meantime that's why I put it there. Idk hopefully they'll fix it in the main branch.

**Comment by nyagami** [comment]
You should move to v2 app because the main branch is not be maintained anymore.
