### ISSUE TITLE
Crashes when changing categories

### ISSUE THREAD

**Issue by kyabetsuki** [LNReader/lnreader#640]
### Steps to reproduce

Long press on title in library

Click the category icon on the bottom left

Change to different category

App crashes

### Expected behavior

Should change category without crashing. 

### Actual behavior

Crashes when changing category

### LNReader version

1.1.15

### Android version

Android 13

### Device

Galaxy S21+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.15](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Not able to reproduce this. Is this issue still happening?

**Comment by kyabetsuki** [comment]
It appears to happen only

**Comment by nyagami** [comment]
Not able to reproduce. Reopen if it still happens in beta version. 
We stop working on 1.x.x versions
