### ISSUE TITLE
No chapter appears when clicked on Sakuranovel

### ISSUE THREAD

**Issue by alfianbayu11** [LNReader/lnreader#647]
### Steps to reproduce

Click Novel in Sakura Novel Click Chapter then the content does not appear

### Expected behavior

The chapter should appear when clicked on Sakuranovel

### Actual behavior

The chapter dont appear when clicked on Sakuranovel

### LNReader version

Lnreader versi 1.1.15

### Android version

Android 11

### Device

Poco X3 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.15](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment]
Fixed in preview release, you may get it here https://github.com/LNReader/lnreader-preview/releases/tag/v1.1.15.1
