### ISSUE TITLE
Js injector: preformed code for common users with assist

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#651]
### Describe your suggested feature

Common users like me don't know how to write a java script so i would like some kind of assist from the app. 
A pratical example might something like this:

https://github.com/LNReader/lnreader/assets/75091899/4ff47938-c548-4d43-926c-a9267749abca

Recently i learned how to replace certain words or phrases with Js injector on discord:

``chapter = document.querySelector('chapter');
chapter.innerHTML = chapter.innerHTML.replaceAll(/WORDS TO REPLACE/g, 'WORDS TO REPLACE WITH');``

Normal users don't know it so it would be very very helpful to add a kind of semplified register of simple commands setted like in the video above.
I also discovered that the syntax needs to be changed based on the content of the words to replace  like in this example:

``chapter = document.querySelector('chapter');
chapter.innerHTML = chapter.innerHTML.replaceAll(/read at https:\/\/noblemtl\.com/g, '')``

here special characters need \ before the special character so that the js code injected applies successfully.
Unfortunately normal users don't know that so it would be helpful if the app corrected the generated syntax based on the content.

edit 
NOTE: the part of the code example ``chapter = document.querySelector('chapter');
chapter.innerHTML = chapter.innerHTML`` has been changed from(before edit) ``document.querySelector('chapter').innerHTML = html``
because the previous(before edit) couldn't replace some words properly.
nyagamy(discord) gave the solution (8th June 2023 10:17 gmt+1) and it works on that 'particular' case too now.

2nd edit
a preformed code to replace names:
``.replace(/\bShiu\b/g, "Siwoo") ``
to replace ``Shiu`` with ``Siwoo``.

3rd edit
a code to color all text between ``"`` and its kinds like ``“`` and ``”``  simbols (by SkillGG and Nyagami - Discord)

```js
const regex = /[\"“”]([^\"“]+?)[\"”“]/g;
const colorElement = (x) => {
  const ps = x.innerHTML.split(/<br\/?>/g).map(p => p.replace(regex, `"<span style='color: red'>$1</span>"`))
  x.innerHTML = ps.join("<br/>");
};
(col = (parent) => {
  if (parent.nodeName === "SCRIPT") return;
  const childsWith = [...parent.children].filter((ch) =>
    /[\"“”]/.exec(ch.innerText)
  );
  console.log(parent.innerHTML);
  if (!childsWith.length) colorElement(parent);
  else childsWith.forEach((ch) => col(ch));
})(document.querySelector("chapter"));
```
If by chance the dialogue text has no " at its end to mark its end then the paragraoh will not be colored

One should be able to input the color and the symbols and choose if the symbol the user input-ed should be colored together with the text. 
This is the result:
![IMG_20230612_172341](https://github.com/LNReader/lnreader/assets/75091899/7ea6fc12-793f-480e-873c-15a4887f201f)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.14](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
The app is for reading Novels, there are no plans to make the Custom JS section a full-fledged code editor.
