### ISSUE TITLE
Toggle option to disable completely the text selector in the reader

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#652]
### Describe your suggested feature

Ability to disable the text selector when reading with a toggle option.

![IMG_20230601_104440](https://github.com/LNReader/lnreader/assets/75091899/989bdb8e-b5f5-44ac-8ead-36d2102b9363)

Sometimes when one scrolls the text manually (finger) the option of the text selector appears by mistake (mine) since i hold for too much time the finger on the text triggering the appearance of the text selector options while scrolling. Copying, pasting, cutting and other things are useless to me on novels. why would i, an average user, need to copy the text of chapters. If i ever need to do it, it would be an extraordinary case. I read 10k chapters between novels on lnreader and still i didn't find the text selector useful in any way, because i never needed it, really. it was only a hassle since sometimes i trigger its option by mistake, over and over again, sigh.

Usually when i activate tge text selector i have to click away to make it disappear. Then it will trigger the seek bar and to hide it i have to tap again. It is a hassle since it happens 2-3 times per chapter in my case

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.14](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
You can add this in Custom CSS to disable text selection.

```css
* {
   user-select: none;
}

**Comment by Palloxin** [comment]
I didn't know thank. But wrapping it in a toggle option avaiabke in reading mode would allow me to copy name or words more comfortably for js injector (.replace and stuff)
