### ISSUE TITLE
Css and Js editor messes up the selector logic and position

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#654]
### Steps to reproduce

I am not sure if one can reproduce it since it is a very obvious flaw so i suppose it happens only on my device.

https://github.com/LNReader/lnreader/assets/75091899/86107e4f-dc6f-44e3-a6f9-15bfa3b8908c

Deleting text will shift the position of the text selector of one backward;
Typing text between other words place the letters in the opposite order (so ``game``==> ``emag``);
If you type text in a position that has NO words forward the editor will not place typed words in the opposite order.

### Expected behavior

Normal editor logic

### Actual behavior

Messed up logic of editor (see video)

### LNReader version

1.1.15.1

### Android version

Android 8 miui 8

### Device

Huawei p8 lite 2017

### Other details

This the text selector i am talking about
![IMG_20230602_115000](https://github.com/LNReader/lnreader/assets/75091899/22339f20-90e4-4fa9-8c84-ca19da3da9e7)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.15](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Kai-Nui** [comment]
Same with me
Android 12, MIUI 13
