### ISSUE TITLE
Dedicated js section for every sources

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#663]
### Describe your suggested feature

I would like Js sections dedicated to sources.
Why?
Because many times i need to replace certain words or phrases that are common only on that source like 

1. ``read at https://noblemtl`` kind of stuff
2. bad translated terms of MTL sources like Korean=>English
``after-``=>``Sigh``
``Five...``=>``Uh...``
``smart-``=>``Knock-Knock``
``Collock``=>``Cough``
and so on...

3. js scripts to fix bizarre ways sources censor words like BestLightNovel 
![IMG_20230616_105248](https://github.com/LNReader/lnreader/assets/75091899/7e799179-6324-48a0-ab04-b1838f00ff9d)
4. names of characters, abilities and stuff like that so that the normal js editor doesn't get clogged with code to replace specific names for a novel

The main reason is that over time the js code will be more and more stuffed with code not meant for all souces (especially with MTLs) so i would like to keep things in order and separated.

    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.14](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
This can already be achieved by putting source specific logic under a check on the source's ID. 

```ts

if (sourceId === <SOURCE_ID>) {
...
}

```

Adding dedicated JS section for every source would just make the UX complex.
