### ISSUE TITLE
A way to store the main code of js and css for tests purpose

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#666]
### Describe your suggested feature

A way to store the main code, css and js.

### Why
To facilitate tests with code injection. Many times when I test if a code works on a chapter I have to delete a piece of my main code (if not all of it) to test new code and to do so i have to "Save"(button) it. The problem is that most of the times i will need to restore the main code so i usually paste it in a Notepad and when i am done testing i put it back in the app.
So i would like.a place where i can store easly my main code.
Maybe here:
![IMG_20230619_192935](https://github.com/LNReader/lnreader/assets/75091899/22409e01-3dff-40ed-ab86-62828bb0bcda)

### Alternative
A kind of history of codes applied.
Every time the button "Save" is clicked a new entry in the History will appear. Like this:
![IMG_20230619_193607](https://github.com/LNReader/lnreader/assets/75091899/44f01a01-f398-4e2a-906c-86d77cb0bd8e)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.14](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> Many times when I test if a code works on a chapter I have to delete a piece of my main code (if not all of it) to test new code and to do so i have to "Save"(button) it. The problem is that most of the times i will need to restore the main code so i usually paste it in a Notepad and when i am done testing i put it back in the app.
So i would like.a place where i can store easly my main code.

You can save you main code in a file and use "Open JS file" to restore whenever you make some changes.
