### ISSUE TITLE
Performance improvement of very slow global search

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#669]
### Describe your suggested feature

https://github.com/LNReader/lnreader/assets/75091899/aff38a04-6c85-4476-a123-14954309d541

the video is 4x faster

As you can see the globak search has two problems that need performance improvement:
1. Almost impossible to open an entry mid loading with a global search due to it being very very slow;
2. Global search requests continue even after opening a search result. IF the opening of the novel triggers by miracle the loading of covers, plot, chapters etc.. will be very very slow too due to global search continuing background until the global search in background is 100% completed;
3. IF i click a lot of times(like in the video) on the entry while it is loading on global search the app will open the novel page in question multiple times once the global search is 100% completed like here:

https://github.com/LNReader/lnreader/assets/75091899/3cb36a61-f101-432e-9501-d884427b0982

So the limit shoukd be just one, not multiple.

### Other details

OS: Android 8 Miui 8
Device: Huawei p8 lite 2017
Version: 1.1.15.1

I reported a similar issue on tachi with almost the same problem as the bug n°2:
![IMG_20230622_130044](https://github.com/LNReader/lnreader/assets/75091899/144c4b89-eb00-404a-807f-ad0f66805c1c)

EDIT: i just noticed i choose the "feature request" tag by mistake and idk how to change it to Bug.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.14](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> Almost impossible to open an entry mid loading with a global search due to it being very very slow;

This is already mentioned in the app, searching a large number of sources is not recommended as all the concurrent network calls to different websites will freeze the app.


> Global search requests continue even after opening a search result. IF the opening of the novel triggers by miracle the loading of covers, plot, chapters etc.. will be very very slow too due to global search continuing background until the global search in background is 100% completed;


This is the expected behaviour as the Global Search screen is still present in the navigation stack. We could implement a feature to pause searching if the screen is not on focus but if you aren't searching in a large number of sources, opening a novel isn't slow.
