### ISSUE TITLE
[Bug] Custom CSS font stops working sometimes

### ISSUE THREAD

**Issue by llariola00** [LNReader/lnreader#67]
I'm using custom css font by importing google font. But sometimes, the app reverts to basic font, I've experienced this twice. I'm guessing it has something to do with my internet connection since it always happens when I'm opening the app and I'm not connected to the net. 

It doesn't always happen though, I've only encountered it twice, and can be fixed by turning on internet connection and restarting the app.

**Comment by rajarsheechatterjee** [comment]
Google fonts are served from Google's servers. They will not work without internet connection.
