### ISSUE TITLE
Arnovel not working

### ISSUE THREAD

**Issue by uwKILLER** [LNReader/lnreader#672]
### Steps to reproduce

Arnovel not working when i choose any novel i want to read i can't find any chapter 

### Expected behavior

![Screenshot_20230627_215210_com rajarsheechatterjee LNReader](https://github.com/LNReader/lnreader/assets/107407548/7d936721-11c6-4c30-9d7e-4f894cce0b3b)

### Actual behavior

![Screenshot_20230627_215021_com rajarsheechatterjee LNReader](https://github.com/LNReader/lnreader/assets/107407548/c5f9acf7-354c-4773-9759-7e08e26cdc14)

### LNReader version

1.1.15

### Android version

Android 10

### Device

Huawei nova 7 5G 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.15](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
