### ISSUE TITLE
Reproduceable bug that makes the app crash

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#673]
### Steps to reproduce

do like in the video

https://github.com/LNReader/lnreader/assets/75091899/549655dd-e46e-43b9-a4a3-7a949726beb1

### Expected behavior

no crash

### Actual behavior

crash

### LNReader version

1.1.15.1

### Android version

android 8 miui 8

### Device

huawei p8 lite 2017

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.15](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
I am not able to reproduce this issue as there shouldn't be 2 entries of the same novel in history. 

If this issue is still happening, could you provide crash logs? You can use [logcat](https://play.google.com/store/apps/details?id=com.dp.logcatapp).

**Comment by Palloxin** [comment]
[llmogcat.txt](https://github.com/LNReader/lnreader/files/11928920/llmogcat.txt)
logcat @rajarsheechatterjee
