### ISSUE TITLE
Make the resume button area in History, bigger

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#674]
### Describe your suggested feature

![IMG_20230629_095624](https://github.com/LNReader/lnreader/assets/75091899/447c4e30-47de-4b83-8e7b-d586ea43770c)
Make the clickable are of this button bigger.
Why?
sometimes my finger doesn't click precisely on the button and this happens:

https://github.com/LNReader/lnreader/assets/75091899/56c256be-7411-4060-8658-f70855ddf94f

and it is annoying.
I would the button area to cover completely the right side so a misclick can't happen:
![IMG_20230629_100055](https://github.com/LNReader/lnreader/assets/75091899/e00eae91-451e-406f-868f-ff754d586d79)
blue area should be part of resume button

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.14](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
The resume button has been removed in 710cca66f3603ebae3d678835972526c8e9447a8 and now the entire row navigates to the chapter.
