### ISSUE TITLE
Precise resuming of chapters from entries.

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#675]
### Describe your suggested feature

Lets say i fully read a chapter without swiping to the next one, i finished reading completely this chapter, then i close the app and do something else. The moment i come back and press the Resume button i want the app to exactly resume where i was and NOT to the beginning of the next chapter. This can be an optional feature activeable in the settings so no need to force this change on unwilling users.

## Why

If i am reading a book and i leave a bookmark between two pages i wouldn't like to find that someone moved the bookmark between the next two pages.
Another reason is present in this context:

![IMG_20230217_195903](https://github.com/LNReader/lnreader/assets/75091899/cb677c7f-b425-4c80-be74-0b5fd0648aeb)

The blue circled part is read by the user(the rest is not), but since i scrolled until the end of the chapter the app sees it as completely read; if in this case i close the app, take a break and then come back clicking "resume" button (not from history) the app will load the next chapter and it is annoying.
Resuming directly the next chapter is an additional step that is not useful. I think the bookmark example on physical books explains the problem very well.

### Other details

The "Resume" button of the History sectiom
![IMG_20230629_100055](https://github.com/LNReader/lnreader/assets/75091899/016e63ae-50e7-455b-abb2-0b0b8b0da5fc)
Does EXACTLY what i am asking in this feature request. When i click resume it doesnt go to the other page resuming exactly where i leaved.
There is nothing new to add, just copy the feature from history section and wrap it up in a toggle option.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.14](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
I havent read the description, but I like the novel cover

**Comment by nyagami** [comment]
I've just read it, and ye, it could be annoying a bit. Also auto moving to the nextchapter is also a expensive and not safe implement. Should ask Traitor remove it in future lol.

**Comment by Sardonyx001** [comment]
Is anyone taking up this issue? If so I'd like to give it a try!

**Comment by rajarsheechatterjee** [comment]
@Sardonyx001 Feel free to work on this.

**Comment by Sardonyx001** [comment]
@rajarsheechatterjee 
I was checking out this out and I couldn't really find a problem? 
I'm on 1.1.17 and while there is no resume button in the history section, pressing on the entries brings me right back where I left so it is my understanding that there is nothing to add here I guess?

**Comment by Palloxin** [comment]
@Sardonyx001 yeah i did the issue before the removal of the resume button in History.

**Comment by rajarsheechatterjee** [comment]
@Sardonyx001 I assume the issue was to have an option for the "Resume" button on Novel Details screen to have the same behaviour as the History screen.
