### ISSUE TITLE
Unreaded chapters don't have their reading progress% resetted

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#678]
### Steps to reproduce

1. open an unreaded chapter never opened
2. scroll until the end then exit reading mode
3. mark as unread the said chapter
4. open the said chapter again

### Expected behavior

Reset reading progress

### Actual behavior

the app will bring you to the end of the chapter. so no reset

### LNReader version

1.1.15.1

### Android version

Android 8 

### Device

huawei p8 lite 2017

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.15](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Perry-God** [comment]
Still an existing issue
