### ISSUE TITLE
Export to epub

### ISSUE THREAD

**Issue by samanta-widjaja** [LNReader/lnreader#681]
### Steps to reproduce

Is this already implemented. I don't see any button the novel page. How can I export to epub? Thanks

### Expected behavior

Export button available

### Actual behavior

Export button missing

### LNReader version

1.1.15

### Android version

Android 12

### Device

Redmi note 9 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.15](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment]
You need the debug build for that
You can find it here, https://github.com/LNReader/lnreader/actions/runs/5447078129
Login to github and download the file under artifacts

**Comment by samanta-widjaja** [comment]
I downloaded trash of the count family from novel updates and export it. It's hard to read because of the color. And it will be better for each new chapter on a new page & the chapter title or number on top. Thanks

**Comment by ai4hub** [comment]
> I downloaded trash of the count family from novel updates and export it. It's hard to read because of the color. And it will be better for each new chapter on a new page & the chapter title or number on top. Thanks

Which source did you use

**Comment by samanta-widjaja** [comment]
I use novel updates

**Comment by CD-Z** [comment]
The next few days there should come a better version of this feature, however I am not at home at the moment and need to do a few changes first, before it can be approved.

I that version it will be possible to do a bit more customization.

**Comment by samanta-widjaja** [comment]
Ok. Thank you
