### ISSUE TITLE
Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by saiayyappa** [LNReader/lnreader#683]
### Steps to reproduce

1. Go to any novel from Library(in my case went from default tab)
2. Click of any chapter or click on resume button

### Expected behavior

It should open the chapter or resume from the chapter thats last read.

### Actual behavior

Instead of chapter getting opened I get error page  with the following error:

Cannot read property 'replace' of null 
![Screenshot_2023-07-10-18-47-59-44_3c1c179116822eec69c21805387f0489](https://github.com/LNReader/lnreader/assets/10359824/9958a98e-9c79-494e-b11c-65462b721a09)

### LNReader version

1.1.15

### Android version

Android 13

### Device

Realme 10 Pro 5g

### Other details

![Screenshot_2023-07-10-18-47-59-44_3c1c179116822eec69c21805387f0489](https://github.com/LNReader/lnreader/assets/10359824/0880734b-ab6b-4905-862c-e99353546d44)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [x] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.15](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
>If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).

![Screenshot 2023-07-10 at 7 01 14 PM](https://github.com/LNReader/lnreader/assets/57822170/27a583c8-0855-4fdc-9276-435c63e15a15)
