### ISSUE TITLE
Export to epub

### ISSUE THREAD

**Issue by ai4hub** [LNReader/lnreader#689]
### Steps to reproduce

I used the export button
Selected location
saved
checked epub in exported location

### Expected behavior

The epub should be readable and it should have chapter number

### Actual behavior

The epub should be readable and it is not.

### LNReader version

1.1.16

### Android version

Android 11

### Device

Redmi note 11

### Other details

Export to EPUB not readable by any any epub sortware that I have used. I do not know if it the software I use but I have tried all options and various sources and still, it is unreadable.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.16](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Currently the app only exports downloaded chapters as EPUB. Did the novel you tried the feature on had downloaded chapters?

**Comment by ai4hub** [comment]
Yes I downloaded them

**Comment by CD-Z** [comment]
Could you please also post the novel, source, tested epub reader and the actual epub file.

**Comment by ai4hub** [comment]
Hi, sorry I just copied to pc and it was able to open with calibre. for some reason, no android app was able to open it.

**Comment by CD-Z** [comment]
Still it should be able to open on android, and I also have no problem opening on android.

**Comment by ai4hub** [comment]
Android working... Thanks for this app. It is awesome
