### ISSUE TITLE
Search button in the js editor

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#692]
### Describe your suggested feature

The more text is present in the js editor the more this feature will be useful.
Like Notepad has a find button it would be very helpful for the js editor for more reasons:
1. A lot of code in it makes the search and edito of previous code more harder (scrolling, testing and stuff)
2. The text space is just a little window so it is too small and tight. In this way the code will have more "line codes"(since there are more break lines due to the small editor box? and it will require more scrolling.
3. too much scrolling require than a normal notepad app oj android. the scrolling is awful because it doesn't have the "jump" effect

this is the jump effect (or continuous slide effect idk its name).

https://github.com/LNReader/lnreader/assets/75091899/1dd1271e-08a9-47ff-a5db-4eb73dd350c3

This is how it is on lnreader:

https://github.com/LNReader/lnreader/assets/75091899/46593f95-2a37-46bf-8a6d-4cf3d7dd6bb2

### Other details

It would be better to make css and js editor boxes bigger

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.14](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
There's already a feature for importing custom JS from files. In your case since you have this much custom JS it is recommended to use a file instead of using the app's editor for maintaining it. Existing text editors already have the features mentioned in this issue.

As previously mentioned, there are no plans to make the custom JS section a full fledged code editor.
