### ISSUE TITLE
Not full Russian language in the application settings.

### ISSUE THREAD

**Issue by alextrik67** [LNReader/lnreader#694]
### Steps to reproduce

When you enter the settings, the translation is not complete, but only part of the points.

### Expected behavior

Translation into Crowdin almost complete. 

### Actual behavior

Many items are not translated.

### LNReader version

1.1.16

### Android version

13

### Device

Google Pixel 6 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.16](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Not all strings have been added to Crowdin yet so even 100% their wouldn't mean the entire app is translated.
