### ISSUE TITLE
Ranboes New URL (Cannot see LN's in Ranboes because of their new url)

### ISSUE THREAD

**Issue by tehchy123** [LNReader/lnreader#697]
### Steps to reproduce

1. Open LN Reader
2. Navigate to explore menu (compass button)
3. Search for Ranobes and enter
4. Tap the globe button at top right.

### Expected behavior

Open Ranobes and/or be able to search for LN's under Ranobes

### Actual behavior

Following message:

**The site is temporarily disabled**
Go to the new site - https://ranobes.top

### LNReader version

1.1.15

### Android version

Android 13

### Device

Samsung Galaxy A23

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.16](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).

This has been already fixed in develop, you can either try a [dev build](https://github.com/LNReader/lnreader/actions/runs/5567514089) or wait for next release.
