### ISSUE TITLE
Some novels are broken in the ARnovel website 

### ISSUE THREAD

**Issue by meliodas143** [LNReader/lnreader#698]
### Steps to reproduce

![Screenshot_٢٠٢٣٠٧٢٢_١٣٥٥٥٤_LNReader](https://github.com/LNReader/lnreader/assets/139044129/4894938c-30d8-4a56-89f2-7b5e4fa8560a)

### Expected behavior

I have to find the chapters of the novel 

### Actual behavior

There are no chapters 

### LNReader version

1.1.16 

### Android version

Android 11 

### Device

Google Pixel 5

### Other details

These are some of the novels I found broken: 
اسبر حريم في نهاية العالم

جينات الاله الخارقة

توقف، نيران صديقة!

لورد الغوامض

القس المجنون

هيمنة الإمبراطور

عاهل الزمن

مشعوذ عالم السحرة

ترقية أخصائي في عالم آخر

أسطورة الحكيم العظيم

10000 عام في طائفة زراعة: لقد حصلت على تقنية قوية منذ البداية

أي شخص آخر هو عائد

التنين الرابض

تسجيل الجسد المقدس للقدماء منذ البداية

تلاميذي جميعهم أشرار

مشعوذ الدم: مع شريكة سكبوس في نهاية العالم

ملك الآلهة

عالم فنون القتال

المانا اللانهائية في نهاية العالم

تطور عفريت إلى الذروة

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.16](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
>If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
