### ISSUE TITLE
Can't select js file on the "open js file" of the js editor

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#700]
### Steps to reproduce

https://github.com/LNReader/lnreader/assets/75091899/df7c2fa5-ee7a-40a6-a256-9972b68b1786

Not sure, i just used the feature normally.

### Expected behavior

Js fike selectable.

### Actual behavior

Js file unselectable

### LNReader version

1.1.6

### Android version

Android 8 Miui 8

### Device

Huawei p8 lite 2017

### Other details

https://cdn.discordapp.com/attachments/835757769172713503/1132361545867870308/aaa.js
(i can't upload this file directly here, github doesn't allow it somehow)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.16](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Are you able to read files from device anywhere else in the app (custom covers / backup)?

**Comment by Palloxin** [comment]
https://github.com/LNReader/lnreader/assets/75091l899/49b68274-56c8-49c7-a8e3-363eb33eead2

Mmm i not sure i clicked on the restore file and nothing happened. no new window pop up.
Well at least the file is selectable.

**Comment by rajarsheechatterjee** [comment]
Closing this since it was an issue with our file. The app not being able to read files in Android 9 or lower is a separate known issue.
