### ISSUE TITLE
App getting crashed when scrolling extension option

### ISSUE THREAD

**Issue by samad3w** [LNReader/lnreader#706]
### Steps to reproduce

When I scroll extension option for extension.. App getting crashed/restart. 
I don't why , my device's old, Android 6 arm v7a. 
I faced the same issue in previous version

### Expected behavior

...

### Actual behavior

...

### LNReader version

1.1.16

### Android version

Android 6

### Device

LG Stylus2 Dual

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.16](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Could you share logs of the crash? You can use [logcat](https://play.google.com/store/apps/details?id=com.dp.logcatapp).

**Comment by rajarsheechatterjee** [comment]
Closing this issue as its stale.

You can reopen if the issue still persists.
