### ISSUE TITLE
Reduce the space occupied by the reader-settings preview

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#707]
### Describe your suggested feature

As the title says. Having only half of the avaiable screen dedicated to actual settings is a bit weird (at least for me... and i enter the reader section of settings very often)
So i propose to trim it a little bit and give the reader-settings more space (less for preview):
![image](https://github.com/LNReader/lnreader/assets/75091899/58b03ff4-7472-43b7-8996-7cde81a58f41)

Green zone removed from preview and given to reader-settings
Yellow zone removed. that much space in those specific parts seems a waste so it would be better to give it to reader-settings.

### Other details

The yellow zone is not a must but it would be better if both color zones are removed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.14](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
The preview section has a static height of 280px, it takes half the screen as your screen size might be smaller. 

Reducing it's height wouldn't be a solution. The UX would have to be revamped otherwise it would still happen on smaller devices.

**Comment by Palloxin** [comment]
What about making it adaptive to the screen?

**Comment by rajarsheechatterjee** [comment]
> What about making it adaptive to the screen?

It could then be really big or small depending on the screen size which wouldn't be a UX. Some new design has to be figured out for the screen.
