### ISSUE TITLE
Css/js editor problem with capital "mode" on keyboard when typing fast

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#708]
### Steps to reproduce

1. go to js/css editor
2. Paste inside it a good amount of text (mine is 21000 characters)
3. type whatever u want but fast, THEN while typing, click on "Shift" (idk the name of Android equivalent) to show capital letters

https://github.com/LNReader/lnreader/assets/75091899/8046bc91-6e32-4467-a697-498380e28b45

BUT if i wait a bit before clicking on "Shift", the capital "mode" will not revert to non-capital "mode"

### Expected behavior

No interference with keyboard

### Actual behavior

Interference with keyboard

### LNReader version

1.1.16

### Android version

Android 8 Miui 8

### Device

Huawei p8 lite 2017

### Other details

i remember it being present in the 1.1.15.1 (idk 1.1.15)

It bug starts occourrinf when too much text is inside and editor.
I tested it on CSS editor and it does't happen because there is little amount of text there

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.16](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Closing since its related to #704
