### ISSUE TITLE
SakuraNovel : Empty Webview (error)

### ISSUE THREAD

**Issue by AhmadNaruto** [LNReader/lnreader#712]
### Steps to reproduce

l. open SakuraNovel and browse
2. choice one of novel
3. titel and synopsis showed

### Expected behavior

when chapter choiced show chapter content 

### Actual behavior

there are no chapter content, just show

`Chapter is empty. Report on github if it's available in webview.`

### LNReader version

1.1.15

### Android version

Android 12

### Device

Poco M4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.16](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
