### ISSUE TITLE
Ajitoon source not going anymore.

### ISSUE THREAD

**Issue by ai4hub** [LNReader/lnreader#717]
### Steps to reproduce

1)Open LNReader
2)Click on BROSWE
3)Click on Agitoon source

### Expected behavior

Should load 

### Actual behavior

Loads for a sec then brings out error.
![Screenshot_2023 07 29_22 33 10 363](https://github.com/LNReader/lnreader/assets/137424956/83a04034-2a95-4edc-b0ac-47cabec14b01)

### LNReader version

1.1.16

### Android version

Android 11

### Device

Redmi note 11

### Other details

sometimes loads longer than a sec but stops and brings out error. Either when I click on search or just waiting for complete load... Same issues now matter what.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.16](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).

**Comment by ai4hub** [comment]
That reminds me, do you use lab ads?
