### ISSUE TITLE
Volume button scroll functionality degradation.

### ISSUE THREAD

**Issue by acewinters** [LNReader/lnreader#719]
### Steps to reproduce

1. Open app.
2. Read any chapter.
3. Click the button to go to next chapter.
4. Volume scrolling stops working.

### Expected behavior

" Using the volume buttons should continue working after going to next chapter."

### Actual behavior

" the volume buttons cease to work for scrolling after continuing to the next chapter."

### LNReader version

Tested 1.1.16 and 1.1.17

### Android version

Android 13

### Device

Google pixel 7 pro

### Other details

Volume scrolling functionality returns after leaving the chapter and coming back but that is incredibly tedious to do every single chapter.

This was an opened issue in the past. However you have locked said issue and have noted it's "fixed".

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.16](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
Fixed in https://github.com/LNReader/lnreader/commit/d6290294f7e9a9569ec09d87dbb7d68e3f78815c
