### ISSUE TITLE
Source issue : (arnovel)

### ISSUE THREAD

**Issue by Ghost01152** [LNReader/lnreader#730]
### Steps to reproduce

![Screenshot_2023-08-07-18-39-18-03_3c1c179116822eec69c21805387f0489](https://github.com/LNReader/lnreader/assets/141438343/834accf9-9e78-4479-a371-bcd6c7685b62)

### Expected behavior

Big light novels chapters in (arnovel) should show up 

### Actual behavior

Big light novels over 2000 chapter or even 1000 in (arnovel) don't show up 

### LNReader version

LNReader-r879/virsion : 1.1.17

### Android version

Android 10 and android 8

### Device

Realme 2 pro / Samsung galaxy Tab A6

### Other details

![Screenshot_2023-08-07-18-39-18-03_3c1c179116822eec69c21805387f0489](https://github.com/LNReader/lnreader/assets/141438343/a516c6f3-d861-48c4-9dd8-334c94e54a3f)

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.17](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).

**Comment by Ghost01152** [comment]
Why was the problem rejected

**Comment by Ghost01152** [comment]
I don't understand what should i do ?

**Comment by rajarsheechatterjee** [comment]
Create an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
