### ISSUE TITLE
Cannot read Trim issue

### ISSUE THREAD

**Issue by TonyRaj02** [LNReader/lnreader#734]
### Steps to reproduce

When I tried to update my novels but some of the novel which tried to get update but there is some issue saying that "Cannot read property trim".
Please resolve as I always use this app ..

### Expected behavior

I have been using your app from like your third update..please resolve this issue and I like your man.

### Actual behavior

When I tried to update my novels but some of the novel which tried to get update but there is some issue saying that "Cannot read property trim".
Please resolve as I always use this app ..

### LNReader version

1.1.17

### Android version

"Android 13"

### Device

Realme note 10 pro 5g

### Other details

![Screenshot_2023-08-14-07-28-56-95_3c1c179116822eec69c21805387f0489](https://github.com/LNReader/lnreader/assets/142190516/1ce313ae-01e1-460f-ae76-0a541279fde4)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.17](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
This seems to be an issue with the sources of those novels. 

Create an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose) and mention the source and novel names.

**Comment by TonyRaj02** [comment]
But it's not one like 10-20 novels like that

**Comment by TonyRaj02** [comment]
FastNovel, NovelTop1.like that there are more
