### ISSUE TITLE
Global search for pinned sources is not working

### ISSUE THREAD

**Issue by PondelekB** [LNReader/lnreader#735]
### Steps to reproduce

1 opening global search
2 typing the title
3 nothing loading or searching, staying on default screen 

### Expected behavior

Should search through pinned sources

### Actual behavior

Nothing searching and just closing off the keyboard 

### LNReader version

1.1.17

### Android version

Android 12

### Device

Oppo reno 3 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.17](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Not able to reproduce this. Do you have any pinned sources?

Could you attach a screen recording of the issue?
