### ISSUE TITLE
Permanent application of the JS to exported Epubs

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#737]
### Describe your suggested feature

Instead of including the custom JS into the EPUB (and hope to find a good reader that supports it) apply permanently the changes that comes with the JS injection making the EPUB more compatible with epub readers that do not support JS.

### Why 
Few readers support JS, so just change permanently the text based on the custom JS injected so the EPUB will not have the JS in it.

### Other details

It would make the js injection in epubs way more comfortable since it would make the epub file very compatible with epub readers.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.14](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Svk1190** [comment]
Epub3 readers support Javascript, for example:
Reasily, Lithium, PocketBook, Gitden Reader, Aldiko Next, Overdrive, Bluefire Reader, BookFusion, Infinity Reader, and possibly many more.
