### ISSUE TITLE
Words in <angled brackets> not appearing.

### ISSUE THREAD

**Issue by atxkirl** [LNReader/lnreader#743]
Words in angled brackets don't appear in the reader, seems like a html thing? If theres a way to turn this feature off I'd love to know :)

**Comment by rajarsheechatterjee** [comment]
This was fixed in v1.1.16.

If the issue still persists open another issue and follow the [issue template](https://github.com/LNReader/lnreader/issues/new?assignees=&labels=Bug&projects=&template=report_issue.yml).
