### ISSUE TITLE
Make Export Epub path position box keep the last folder used 

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#747]
### Describe your suggested feature

https://github.com/LNReader/lnreader/assets/75091899/8444132d-a7a4-47a3-ae08-eebfcfe7090b

The export epub path is not kept as u can see so i would like it to be kept.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.14](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Resolved in f7f02dc1795e8e0f3ec2517cb71fca00924c1a70
