### ISSUE TITLE
Prevent weird text boxes to appear in the chapter

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#750]
### Steps to reproduce

1. inject this js: https://cdn.discordapp.com/attachments/1055525753325883403/1141673728732827801/aaa.js
2. Go to AllNovelFull, The Incubus System, Glossary (Chapter 0).
3. open Chapter 0 (Glossary)

### Expected behavior

Weird text box never appears

### Actual behavior

https://github.com/LNReader/lnreader/assets/75091899/fb5389ff-e65b-4a00-876d-1cec09aca151

### LNReader version

1.1.17

### Android version

Android 8 miui 8

### Device

Huawei p8 lite 2017

### Other details

These text boxes appear rarely, but when they do they are a pain.
Maybe directly deleting them before before the JS is applied.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.17](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
There is no input present in the chapter's HTML and neither is the text box present in the chapter without applying any custom JS.

If this only happens after applying your custom JS then it's not an app issue.
