### ISSUE TITLE
Resume button doesnt track the last read chapter when the reading progress is involved

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#751]
### Steps to reproduce

1. Go to a new random novel entry
2. mark as read all chaps until chapter 5
3. open chapter 6 and scroll until the end of the chapter.
4. click next chapter button and exit reading mode
5. mark as unread chapter 6,5 and 4

### Expected behavior

![IMG_20230819_204215](https://github.com/LNReader/lnreader/assets/75091899/b8aa7ed8-7b28-48c7-9953-a754c0f47c66)
How it should be.

### Actual behavior

![IMG_20230819_204343](https://github.com/LNReader/lnreader/assets/75091899/8905649e-025f-4696-beb1-5b208e225542)

It would happen anyway even if i didnt click on next chapter and go to chapter 7, directly exiting at the end of chapter 6

### LNReader version

1.1.17

### Android version

Android 8

### Device

Huawei p8 lite 2017

### Other details

This doesnt happen when there is no real reading progress% involved. The resume button will adapt accordingly.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.17](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
It's the expected behaviour as manual progress has higher priority.
