### ISSUE TITLE
Chapters not refreshing immediately upon update

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#755]
### Steps to reproduce

https://github.com/LNReader/lnreader/assets/75091899/f5ec1e67-b0e3-49b7-b3bb-32c69456b0c5

1. need an entry to update and that has new chapters not "registered" (in the chapter list)
2. update it

### Expected behavior

The new chapters appear in the list without the need to exit the entry and enter again, or changing chapter order to make them appear.

### Actual behavior

The new chapters dont appear in the list unless i exit the entry and enter again, or change chapter order to make them appear.
Some sort of trigger.

### LNReader version

1.1.17

### Android version

Android 8

### Device

Huawei p8 lite 2017

### Other details

In the video you can see the total chapter count change from 466 to 469 when i changed the chapter order.
Also i didnt show it but new chapters dont appear too in the same way unless i trigger the change of chapter sorting or exit the entry.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.17](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
Could you check if it still exists in v2?

**Comment by Palloxin** [comment]
Cant reproduce on beta
