### ISSUE TITLE
Novels in source "FastNovel" doesn't show any chapters

### ISSUE THREAD

**Issue by 0JamesJoseph0** [LNReader/lnreader#756]
### Steps to reproduce

Open FastNovel
Select a novel (Favourited or not Favourited)

### Expected behavior

When opening a source, in this case "FastNovel" and selecting the novel you want whether or not you have it Favourited in the library it should show the content of the novel aka chapters.

### Actual behavior

When opening source, "FastNovel" and selecting the novel you want whether or not you have it Favourited in the library it doesn't show any chapters and when you try to update the library it doesn't update anything of the source "FastNovel"

### LNReader version

1.1.17

### Android version

Android 9

### Device

Resmi Y2 (S2)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.17](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Palloxin** [comment]
Write it in the source section https://github.com/lnreader/lnreader-sources/issues/new/choose

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
