### ISSUE TITLE
Cloudfare verification problem 

### ISSUE THREAD

**Issue by Gurujiop12** [LNReader/lnreader#758]
### Steps to reproduce

Verification keeps going on and on
Everytime its a failure and restarts

### Expected behavior

The verification must be linked to browser

### Actual behavior

Verification goes on and keeps failing in Novelr18.com

### LNReader version

1.1.17 

### Android version

Android 10

### Device

Oppo A17

### Other details

Verification keeps running 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.17](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).

**Comment by Gurujiop12** [comment]
It must be the webview page problem not the cloudfare verification as its
not working on Android webview
