### ISSUE TITLE
Zoom In to Images in Reader

### ISSUE THREAD

**Issue by cactusoftheday** [LNReader/lnreader#763]
### Describe your suggested feature

Images are loaded in with their aspect ratios constant and their max width essentially being limited to the width of the phone. This makes viewing text or small details in images very difficult. If users could just double tap on an image and be able to zoom in and double tap to exit the zoom, that'd be great.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.14](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
implemented in 2.0 version

**Comment by nyagami** [comment]
You can try v2 beta or wait for its stable release
