### ISSUE TITLE
Search results not appearing 

### ISSUE THREAD

**Issue by Remielas** [LNReader/lnreader#764]
### Steps to reproduce

I tried searching on some of my used sources but results doesn't appear. It only goes back to it's initial display 

### Expected behavior

Normally, it would only happen if the the keyword doesn't match any novels

### Actual behavior

But I checked it again and again and it's the correct title

### LNReader version

It's on ver. 1.1.14.

### Android version

Android 10

### Device

Realme 5i

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.17](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).

Also the latest app version is v1.1.17.
