### ISSUE TITLE
Chapter is Empty 

### ISSUE THREAD

**Issue by LazyHermitGal** [LNReader/lnreader#765]
### Steps to reproduce

1. Chosen (specific) novel
2. Start reading ch. 1

### Expected behavior

What should have happen is the specific chapter should have shown up.

### Actual behavior

What I got is the error msg "Chapter is empty. Report on github if it's available in webview."

### LNReader version

Version 1.1.17

### Android version

Android 11

### Device

Xiaomi Mi 9T Pro 

### Other details

I check the webview is there. The source is Siv’s Novels

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.17](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
