### ISSUE TITLE
Toggle option to remove Overscroll animation in the reading mode

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#766]
### Describe your suggested feature

Uploading YouCut_20230902_112158042.mp4A toggle option to remove overscroll animation in the reading mode. If disabled( to remove), when overscrolling in chapters the animation should not occour.

### Why
Personal preference

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.14](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
The video isn't present. From the description, this can already be done using custom CSS. 

Adding options for things already possible would just make it harder to maintain the app.

**Comment by Palloxin** [comment]
oh i didnt check

https://github.com/LNReader/lnreader/assets/75091899/99c366c2-2a28-4ef8-b042-0d13aaacf25e
