### ISSUE TITLE
Chapter number option doesnt work on a specific kinds of entries

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#767]
### Steps to reproduce

![IMG_20230902_115723](https://github.com/LNReader/lnreader/assets/75091899/904eaf5b-e88e-48df-83a7-cdcf58ffcf0f)
1. Find a novel entry with no chapter numeration whatsoever
2. checkmark the option in the image

### Expected behavior

![IMG_20230902_120047](https://github.com/LNReader/lnreader/assets/75091899/5cac5e93-53af-439f-953e-659e38f65c37)

### Actual behavior

![IMG_20230902_120133](https://github.com/LNReader/lnreader/assets/75091899/5334d090-7926-4e8e-ba62-79c96446ee55)

### LNReader version

1.1.17

### Android version

Android 8

### Device

Huawei p8 lite 2017

### Other details

the entry in the screenshot (bugged) is this
![IMG_20230902_120326](https://github.com/LNReader/lnreader/assets/75091899/9851645d-734c-49f5-abb0-d9cd537f67a3)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.17](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
The chapter names of mentioned novel doesn't have chapter numbers in them. The app wouldn't be able to parse the number if its not present in the name.

**Comment by Palloxin** [comment]
the app can accurately number chapters already.

https://github.com/LNReader/lnreader/assets/75091899/d139a9f9-791c-478c-ae39-447d4246b57d

And that is why it should assign a number to them. If there isn't, the app should do it.
can u reopen the issue?
if not, do i need to do a feature request issue and ask to numerate chapters of entries who don't have their chapter numbered (extension doesnt provide for it).

**Comment by rajarsheechatterjee** [comment]
> the app can accurately number chapters already.

It's not the chapter number, it scrolls to the item present at 1000th index.


> And that is why it should assign a number to them. 


It wouldn't be accurate. If the chapters are not in order or there aren't all the chapters present in source website using the index would just show wrong numbers.


> if not, do i need to do a feature request issue and ask to numerate chapters of entries who don't have their chapter numbered (extension doesnt provide for it).


If you have a accurate solution which handles all the edge cases, feel free to open a feature request.
