### ISSUE TITLE
Toggle option to show the raw html of a chapter

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#774]
### Describe your suggested feature

As the title says. It should be in the Advanced section of the settings since the average user doesnt even use JS (not sure if it is useful for CSS or other reasons).

### Why
Sometimes i am writing a code for a thing but can't figure out what is behind the text so it doesnt match OR matches in a way it shouldn't so having it avaiable raw would help (i can test on regex websites mkre confortably)
An example:

https://github.com/LNReader/lnreader/assets/75091899/97be875e-4072-4ce4-af4a-7c8d006dc938

(the frog is added by me for reasons, focus on the text box)

A piece of code(color dialogue text" ") makes that text box appear rarely on chapters and i have no idea why that happens, what specific elements trigger that code in that way (video). 
Yes, I could download the chapter on an emulator, activate the root and check the the html but it is very annoying.
So this is a QoL request.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.17](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
I dont think Webview can render `raw html`

**Comment by rajarsheechatterjee** [comment]
> Yes, I could download the chapter on an emulator, activate the root and check the the html but it is very annoying.
So this is a QoL request.

You can just open the source website in a browser and use Devtools to see the HTML.


There is no other use case for showing raw HTML other than using complex custom JS so I don't think the app should support showing it when theres already a workaround.
