### ISSUE TITLE
Adding Lnreader on open with option and share for opening epub

### ISSUE THREAD

**Issue by Taki132** [LNReader/lnreader#776]
### Describe your suggested feature

I want to adding epub faster on Lnreader

### Other details

**Bug report**
The epub folder not created and not button to import this epub on the lnreader app

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.17](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by cactusoftheday** [comment]
Huh?

**Comment by rajarshee-harness** [comment]
> I want to adding epub faster on Lnreader

Local EPUB support has been added in develop and would be present in next release.

> Bug report
The epub folder not created and not button to import this epub on the lnreader app

Create a separate issue and add more details.
