### ISSUE TITLE
[Feature Request] Individual download file for faster download

### ISSUE THREAD

**Issue by Lustsifer** [LNReader/lnreader#78]
Currently, downloading chapter will save all of them in one database file that make downloading kinda slow and laggy. Furthermore if we download and read at the same time, it will become more laggy.
So it will be more smoother and faster if you can separate the chapter downloaded to one file/novel or it will be more good if you can separate them to one file for every chapter like what Tachiyomi do.

**Comment by Philii** [comment]
https://drive.google.com/folderview?id=1Ffb1Wg8SyDaND44p37qy7uBwbHq2mDHE

test video and screenshot of my library.
Take 30s every 10mins to load.

**Comment by nyagami** [comment]
implemented in 2.0 version
