### ISSUE TITLE
Save novel covers locally

### ISSUE THREAD

**Issue by LyviaG** [LNReader/lnreader#780]
### Describe your suggested feature

When you select the Novel's cover you can save it like you can with Tachiyomi. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.17](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by christmovies** [comment]
Yes
