### ISSUE TITLE
Please bring this

### ISSUE THREAD

**Issue by christmovies** [LNReader/lnreader#784]
### Describe your suggested feature

![Screenshot_2023-09-30-15-18-17-230_com rajarsheechatterjee LNReader](https://github.com/LNReader/lnreader/assets/97629848/712d2a3b-eca7-47fc-8957-fa87168b51fc)

### Other details

I need this feature For all novels like in tachiyomi, the change has to be permanent 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.17](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by christmovies** [comment]
If You don't understand, is permanent sort

**Comment by rajarsheechatterjee** [comment]
More > Settings > General > Default Chapter Sort
