### ISSUE TITLE
Weird logic of numeration for chapters with certain conditions

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#790]
### Steps to reproduce

1. Find a novel with a source that doesnt provide the numeration of chapters like this novel
![IMG_20231001_163627](https://github.com/LNReader/lnreader/assets/75091899/2142eca4-b31a-48ef-98cc-476ef244bebb)
2. Switch to "chapter number"
3. Find a chapter who has a number in the title

https://github.com/LNReader/lnreader/assets/75091899/db8dc489-9b2c-4f38-8373-cc1fd71d0198

### Expected behavior

The chapters with a number in the title should have ``Chapter -1`` too AND the number is incorrect since it is merely taken from the title due to a bug.

### Actual behavior

chapters of entries of sources that dont provide numeration of chapters with (for example) the title "The 8 wonders of Gugu" (so a number in it) are numerated as Chapter 8.

### LNReader version

1.1.17

### Android version

Android 8

### Device

Huawei p8 lite 2017

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.17](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
App chapter number parser is not perfect and will never ever be perfect, it can not cover all cases.
Each plugin should provide chapter number to app while parsing novel, if no number found app would use its own parser.
