### ISSUE TITLE
Have chapters start at the beginning again after reaching the end of the chapter

### ISSUE THREAD

**Issue by ayameumi** [LNReader/lnreader#791]
### Describe your suggested feature

Currently, if you open a chapter after previously reaching the end of it, it scrolls all the way down to the bottom, forcing you to scroll to the top again if you wanted to reread a chapter from the beginning. Having a chapter start at the top again after finishing it makes it much easier to reread chapters and a nice quality of life upgrade.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.17](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Palloxin** [comment]
You reminded me of the fr i had in mind.
Let me detail it:
1. Clicking on "<"(previous chapter) while in reading mode makes the app resume from the BOTTOM of that chapter(100%)
2. Clicking on ">" makes it always resume from the TOP no matter if the user already read it;
3. Opening an already read chapter using the chapter list in the reading mode (see image) makes the app resume at the TOP 
4. Clicking "Next chapter" makes always start the chapter at the TOP;
![IMG_20231004_223757](https://github.com/LNReader/lnreader/assets/75091899/a70dc387-4210-44c3-8726-5a3669b80532)

5. Opening an already read chapter from the normal chapter list (entry screen) makes always opem the chapter at the TOP
6. history resume logic should not be touched (i am sying it just in case)
