### ISSUE TITLE
Importing some Epub file cause to crash

### ISSUE THREAD

**Issue by dailyfloof** [LNReader/lnreader#798]
### Steps to reproduce

1. Importing epub
2. choose file (Some epub work, some crashes)
3. app crashes

### Expected behavior

Imported

### Actual behavior

app crash

### LNReader version

1.1.18

### Android version

android 12

### Device

LG Q90

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.18](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Could you share an EPUB which is crashing the app?

**Comment by dailyfloof** [comment]
cant seem to share here the file.

**Comment by dailyfloof** [comment]
https://drive.google.com/drive/folders/1eCsC4JZTXxdLfsx9M0big2zvZzvwO9Kn

**Comment by cactusoftheday** [comment]
Yeah I'm working on a fix right now for this. There are some Epub formats that are currently not supported so they may crash the app.

**Comment by Palloxin** [comment]
[logcat.txt](https://github.com/LNReader/lnreader/files/12847487/logcat.txt)

**Comment by yuu1412** [comment]
Hello! From testing it appears epubs made from Google docs or feom ao3 both cause this behavior (

**Comment by nyagami** [comment]
Fixed in v2 app
