### ISSUE TITLE
Give the downloaded state (icon) to imported chapters

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#801]
### Describe your suggested feature

![IMG_20231009_125949](https://github.com/LNReader/lnreader/assets/75091899/eaaf2e0f-873b-49f2-b008-554ba6209cd6)
just this, change it to the Downloaded icon.

### Other details

Maybe not full white like normal chapters since it is imported.
I also guess it needs a new logic since the user shouldn't be abke to delete them normally like usual entries.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.18](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
So as not to confuse people. There's no download/dowloaded icon in chapters from imported entries
