### ISSUE TITLE
BACKUP RELATED ISSUE

### ISSUE THREAD

**Issue by TonyRaj02** [LNReader/lnreader#808]
Hey, this is raju . This morning I got a prompt saying that lnreader harmful from security manager in mobile. I thought maybe I could uninstall and reinstall.so I created a backup and saved in file manager then I uninstalled it and reinstalled, when I tried to restore data but I could not find any backup related file.. how can I find my saved data I have so many novels....can u resolve this issue...

**Comment by rajarsheechatterjee** [comment]
Follow the [issue template](https://github.com/LNReader/lnreader/issues/new?assignees=&labels=Bug&projects=&template=report_issue.yml).

> This morning I got a prompt saying that lnreader harmful from security manager in mobile. 

It's a false positive.

> how can I find my saved data I have so many novels....can u resolve this issue...

If there's no backup file then you can't restore them.
