### ISSUE TITLE
Improve specific animation in the reader

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#814]
### Describe your suggested feature

https://github.com/LNReader/lnreader/assets/75091899/e7ac587c-4bb9-419a-9dc8-8f8ffa129dee

As you can see.. the "frame" appears with two phases (a short one and then it becomes longer).
The feature is about fixing it by making it just one phase (the "longer" state result. So without the short one).
### Why
Aesthetic reasons. Seeing it seems like the app is lagging so it is not good to look at.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.18](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Palloxin** [comment]
I discovered this animation occours only when the Fullscreen feature is turned ON. When it is OFF this happens:

https://github.com/LNReader/lnreader/assets/75091899/48be5395-9e80-4cf3-816c-5fc40cc2548a

There is a strange effect here too which is not aesthetically good:

https://github.com/LNReader/lnreader/assets/75091899/2279a389-0cc3-4f21-837e-68631e220888

**Comment by nyagami** [comment]
Fixed in v2 app
