### ISSUE TITLE
Chapter search with number teleports to the wrong chapter

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#815]
### Steps to reproduce

1. Sort chapter list with a decrescent order (100-->1). Lets say with 1000 chaps
2. Use "Go to the chapter" feature to go to the 300th chapter

### Expected behavior

The "go to chapter" Teleports to the 300th chapter based always on the ascendent order

### Actual behavior

The teleport is calculated from the top of the chapter list to the ``xxx``th chapter towards the bottom. Usinf the example above it teleports to the chapter n° 700.

### LNReader version

1.1.18

### Android version

Android 8

### Device

Huawei p8 lite 2017

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.18](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by danisty** [comment]
This is probably intended, when sorting chapters the selected order also applies to the reader. If you want to navigate to the next chapter inside the reader, it will be the next chapter in the sorted order.

**Comment by nyagami** [comment]
This is expected behavior, it jumps to searched chapter by chapter number not chapter position
