### ISSUE TITLE
Can't open Web View of novel that requires Cloudflare verification

### ISSUE THREAD

**Issue by KShivum** [LNReader/lnreader#818]
### Steps to reproduce

1. Open novel from NovelUpdates that requires a Cloudflare verification (in my case, I was caught up in a Hero summoning but that world is at peace WN)
2. Go to chapter that translated by Foxaholic
3. Open chapter and get Cloudflare error
4. Try to open up buttom bar

### Expected behavior

Bottom bar should open to allow you to open the webview

### Actual behavior

No matter where you tap, you cannot get any of the LNReader UI to show

### LNReader version

1.1.18

### Android version

Android 13

### Device

ZFold 4 (Happens on both layouts)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.18](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> No matter where you tap, you cannot get any of the LNReader UI to show

This is the expected behaviour as the bottom bar isn't present in the error state.

**Comment by KShivum** [comment]
Then should it might not want to say to open it in Webview then unless it is a generic error message since even if you open the chapter in Webview from the novel's Webview, the error doesn't go away

**Comment by rajarsheechatterjee** [comment]
> Then should it might not want to say to open it in Webview then unless it is a generic error message

Ideally there should be a way to open WebView from that state so added the Feature Request label.

> even if you open the chapter in Webview from the novel's Webview, the error doesn't go away

It's probably a NovelUpdates issue, try using the Foxaholic source instead.
