### ISSUE TITLE
Release date of chapters: bug

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#823]
### Steps to reproduce

I asked a dev (nyagami) and he said that the time counter is made by the app.
1. LightNovelPub, add Infinite Mana in the apocalipse to the library
2. download the last 100 chapters
3. Turn off internet from the device for a day minimum (absolutely no internet)
4. Turn on internet and update that entry

### Expected behavior

The release date of chapters has a properly working time counter

### Actual behavior

Time counter doesnt time count properly
![IMG_20231025_203025](https://github.com/LNReader/lnreader/assets/75091899/c527321c-7430-4472-8ff4-de5c996acab6)

Multiple release dates 

https://github.com/LNReader/lnreader/assets/75091899/c14d2df1-861d-47bd-b779-54b1e9f5d6b9

### LNReader version

1.1.18

### Android version

Android 8

### Device

Huawei p8 lite 2017

### Other details

The reproduction steps are just what i did. I cant garantee it will be reproduced. I suggest to check the time counter logic.
As a said already nyagami told me that the app does the counting so it should not be the source.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.18](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> the time counter is made by the app.

The app saves whatever is present on the site as a string. Ideally date should be converted and saved as timestamps at a source level which would require some refactor and migrations. 

For now create a source issues for the sources whose dates need to be fixed.
