### ISSUE TITLE
[bug] lnreader fails to build on python 3.12

### ISSUE THREAD

**Issue by K1ngfish3r** [LNReader/lnreader#826]
### Steps to reproduce

```
python --version === 3.12
npm install
npm run buildRelease
```

### Expected behavior

I has apk

### Actual behavior

BUILD FAILED

### LNReader version

git

### Android version

N/A

### Device

Linux

### Other details

None

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.18](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by cactusoftheday** [comment]
Python should be 3.7>=

**Comment by K1ngfish3r** [comment]
Gradle daemons will seek to keep using the same python version and will not respect the environment variables you set. Can either 

- kill them off or 
- delete the ~/.gradle folder or 
- restart computer after setting the environment variables. 

Resetting whatever gradle daemons that are currently running is the only solution.
