### ISSUE TITLE
Blank Screen when opening a chapter

### ISSUE THREAD

**Issue by ATLAS097** [LNReader/lnreader#829]
### Steps to reproduce

1.Select a novel
2.Select a chapter 

### Expected behavior

It should show the actual writing instead of a blank screen.

### Actual behavior

![Screenshot_20231103-173645_LNReader](https://github.com/LNReader/lnreader/assets/134499426/febfa352-9eb6-4f2a-8cf5-e22b7be3485b)

### LNReader version

1.1.18

### Android version

Android 10

### Device

Samsung A7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.18](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).

**Comment by ATLAS097** [comment]
I don't think it is because of the source as I tried some of them and it come out the same

**Comment by rajarsheechatterjee** [comment]
The app uses WebView to render the chapters. Could you check if Android System WebView is installed on your device / try to reinstall it?

**Comment by ATLAS097** [comment]
Thank you after I delete and install it again it work
