### ISSUE TITLE
Restore

### ISSUE THREAD

**Issue by christmovies** [LNReader/lnreader#830]
### Describe your suggested feature

When I use restore it doesn't restore chapters where I left off, as well as categories 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.18](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Duplicate of #518
