### ISSUE TITLE
Switching fonts makes the chapter reload without resuming the read progress

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#836]
### Steps to reproduce

1. Open a chapter and scroll until 50% read progress
2. Switch the font with the reading mode setting

### Expected behavior

Chapter reloaded and resuming based on read progress (50%).

### Actual behavior

Chapter reloaded and resume starting from the TOP(0%)

### LNReader version

1.1.18

### Android version

Android 8 Miui 8

### Device

Huawei p8 lite 2017

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.18](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by VeceluXa** [comment]
This issue also happens when switching font size, theme, text alignment and line height.

**Comment by Palloxin** [comment]
Not present in beta
