### ISSUE TITLE
[BUG] Frequent Lags while clicking anything in app 

### ISSUE THREAD

**Issue by rsmyst** [LNReader/lnreader#84]
I have a pretty powerful phone definitely capable to handling this app (S9+)
FOr some reason, the app lags at every step just a tad bit. THere's a 0.5 second delay while clicking anything that changes teh UI.
for example, while switching from updates tab to sources tab. 
otherwise, the app is GREAT! thanks

**Comment by rajarsheechatterjee** [comment]
> for example, while switching from updates tab to sources tab

You can try clearing updates tab in Advanced settings.

> The issue is very annoying when using continuosly. I couldn't even get sort options inside manga overview to work because of the extreme lag.

This only happens on Samsung devices, taps don't get registered in bottomsheets.

**Comment by rsmyst** [comment]
@rajarsheechatterjee 
I found this issue the moment I started using app. meaning, no updates were even there to show. it was an issue from day 1
And yes, i am using a samsung device but never really noticed this issue in any other app. even tachiyomi and tachij2k which have a similar style to this app. Good luck with fixing this issue. i'll be happy to help if anything is needed (like logs and stuff)

**Comment by SkillGG** [comment]
> even tachiyomi and tachij2k which have a similar style to this app

They're "similar" because LNReader is stylized after Tachiyomi, but Tachiyomi is a native Android app, whereas LNReader is made in React, a cross-platform library, which limits us in what optimizations we can do and has lots of drawbacks (for example slow af lists). It may look similar, but insides are completely different.

**Comment by rsmyst** [comment]
Oh i just assumed that lnreader is a fork of tachiyomi. Can those drawbacks be overcome eventually? The app looks nice but is still very much in development. Why was react chosen over the native android app anyway for lnreader? isn't lnreader only available for android?

**Comment by rajarsheechatterjee** [comment]
> Why was react chosen over the native android app anyway for lnreader

This app started as a personal project of mine to learn React Native and later other people also started using it. Also I don't know native android development.

Closing since performance should eventually get better.
