### ISSUE TITLE
Add “Raw chapter text” toggle option

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#840]
### Describe your suggested feature

```js
chapter = document.querySelector('chapter');
chapter.innerText = chapter.outerHTML 
```
This can allow one to see this:
![Screenshot_20231110-103933](https://github.com/LNReader/lnreader/assets/75091899/f60903cd-b02e-4f0d-a0d0-81f68aaf8925)
It should be wrapped up in a toggle option.

### Why
For test purposes it would be very useful since going to the website with a pc is a pain. 

Another example might be this chapter:
![IMG_20231110_111030](https://github.com/LNReader/lnreader/assets/75091899/baa9d9a1-82fb-49b4-9c70-38df3e42e6c8)

Why is there so much space? using the toggle option would help to indentify the problem and eliminate it with JS very fast:
![Screenshot_2023-11-10-11-08-55](https://github.com/LNReader/lnreader/assets/75091899/624001ed-7382-40c1-a5f1-6cca12c773c3)

### Other details

Not sure if it should be applied before or after the JS injector of the app 

In the past i made an issue asking for raw html feature and i guess this current issue grants what i had in mind without much bother for the devs.

EDIT:
Using this code instead would make the raw chapter text more orderly sorted, easy to read and search. Better for everybody.
```js
chapter = document.querySelector('chapter');
chapter.innerHTML = chapter.innerHTML
.replace(/(<\/(p|h[1-5]|br)>)(?!\n|\s*<p>\s*<\/p>|\s*<(br|h[1-5]))/g, '$1\n')

chapter.innerText = chapter.outerHTML
```
Like here:
![IMG_20240116_164827](https://github.com/LNReader/lnreader/assets/75091899/77638f7a-0bec-4f99-86c9-175a82e887d8)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.18](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
This is not common usecase and can be done from user end.
Btw, that code just show only chapter body, not entire code. So it is not `raw chapter`
