### ISSUE TITLE
Empty Chapters

### ISSUE THREAD

**Issue by CodeJazper** [LNReader/lnreader#853]
### Steps to reproduce

1. Go to a novel, ex: SSS-Class Suicide Hunter
2. Go to a random chapter
3. Chapter is empty

### Expected behavior

There should be contents for me to read.

### Actual behavior

There isn't a content inside the chapter.

### LNReader version

1.1.18

### Android version

12

### Device

Xiaomi Redmi 9T

### Other details

I tried many things to fix the issue. I cleared the app data, I uninstalled and installed it, I reboot my phone, but none of these worked. I do have android system webview app installed and updated so it can't be that.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.18](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment]
Source name?

**Comment by CodeJazper** [comment]
> Source name?

Woopread

**Comment by CodeJazper** [comment]
> @CodeJazper https://github.com/K1ngfish3r/lnreader/actions/runs/6958680754
> 
> 1. sign in github
> 2. download and install artifact from this link
> 3. More > Settings > Advanced > Delete Database
> 
> If issue persists, provide screenshot

It's fixed! Thank you very very much!!!
