### ISSUE TITLE
Add new source and feature

### ISSUE THREAD

**Issue by Mr-death-ji** [LNReader/lnreader#855]
### Describe your suggested feature

Add mtn nation
Mtl nation has many novels 
Mtl nation is the best for the app
Url of the website (https://mtlnation.com/)
And 
New features like
1 name changing 
2 language changing 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.18](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
