### ISSUE TITLE
Next Chapter Button Bug

### ISSUE THREAD

**Issue by Ateile** [LNReader/lnreader#862]
### Steps to reproduce

1. excited me first time using this app
2. finished reading a chap so I was about to click the next chap
3. the next chap is the previous chap 🤯
4. p.s. I did click it and it did brought me to the previous chap 
![Screenshot_2023-12-14-20-19-23-39_3c1c179116822eec69c21805387f0489](https://github.com/LNReader/lnreader/assets/153827808/b26be917-9779-4353-9907-d77777f9478f)

### Expected behavior

The next chap button should've brought me to the next chap and not the previous one :v

### Actual behavior

The next chap button brought me to the previous one

### LNReader version

1.1.18

### Android version

Android 13

### Device

Oppo Reno 8 5G

### Other details

I've been using this app for only few months by now

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.18](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
The default order of chapters from the source might have been incorrect as I'm not able to reproduce the issue. 

You can create an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose) and fill the necessary information.
