### ISSUE TITLE
Chronology not working correctly 

### ISSUE THREAD

**Issue by Enrico-Fabbri** [LNReader/lnreader#868]
### Steps to reproduce

Open the app and check the chronology tab

### Expected behavior

Should show the last chapter I read

### Actual behavior

When I read the light novels and go to the chronology tab to check the last chapter I read it set them as the last chapter I read was -1
![Screenshot_2023-12-29-13-36-49-17_3c1c179116822eec69c21805387f0489](https://github.com/LNReader/lnreader/assets/70634071/798b498d-9c21-4f94-a949-a4708eb6404a)

### LNReader version

1.1.18

### Android version

Android 13

### Device

Oppo a54 5g

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.18](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> Should show the last chapter I read

They are the last chapters you read. The app shows -1 when it's not able to parse the chapter number from the chapter name. There's another issue for it (https://github.com/LNReader/lnreader/issues/790).
