### ISSUE TITLE
Tracking services aren't working.

### ISSUE THREAD

**Issue by SnowxBlank** [LNReader/lnreader#869]
### Steps to reproduce

I can't track. Even in the setting page it doesn't do anything when I click to link up them.

### Expected behavior

They should be activating like in tachiyomi 

### Actual behavior

But they aren't 

### LNReader version

Stable 1.1.18

### Android version

Android 13

### Device

Motorola edge 20

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.18](https://github.com/lnreader/lnreader/releases/latest)**.
- [x] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Could you share a screen recording of the issue?

**Comment by rajarsheechatterjee** [comment]
Closing as this issue appears to be stale. Please reopen if it persists.
