### ISSUE TITLE
Covers won't show up for novelupdates novels if you're logged in through webview unless you log out

### ISSUE THREAD

**Issue by Sakya22** [LNReader/lnreader#878]
### Steps to reproduce

1. Add any novel from novelupdates
2. Open novelupdates using webview
3. Log in using novelupdates account
4. Go to novel in app then refresh
5. You'll see that cover will disappear

### Expected behavior

Everything should work as normal whether logged in or out on novelupdates

### Actual behavior

Covers disappear making it difficult to locate novels in library

### LNReader version

1.1.18

### Android version

Android 13

### Device

Redmi Note 10 Pro

### Other details

![Screenshot_2024-01-07-13-48-37-927_com rajarsheechatterjee LNReader](https://github.com/LNReader/lnreader/assets/117186887/dde32cd6-2b38-4580-bb95-62fa44237b93)
Before logging in
![Screenshot_2024-01-07-14-02-33-710_com rajarsheechatterjee LNReader](https://github.com/LNReader/lnreader/assets/117186887/9d625832-5d79-4926-8769-d513bace3f73)
After logging in

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.18](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nguyd1** [comment]
noticed the same issue made a fix https://github.com/LNReader/lnreader/pull/880
