### ISSUE TITLE
Problems with settings interface on landscape mode

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#882]
### Steps to reproduce

1. Activate "Auto-rotate" mode
2. Put the phone in landscape position
3. Go to "…" (more) and then Settings
4. Try scrolling

### Expected behavior

Scrollable settings and others (u can see in the video below)

### Actual behavior

https://github.com/LNReader/lnreader/assets/75091899/d856a2f1-6c0d-45cf-9192-99efa770a82f

### LNReader version

1.1.18

### Android version

Android 8

### Device

Huawei p8 lite 2017

### Other details

If you prohibit landscape mode in settings it would solve all problems, quick fix.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.18](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Not able to reproduce this. Could be a device specific issue. 

https://github.com/LNReader/lnreader/assets/57822170/5a1484ca-ccaa-4b10-b41e-15c9962341dc

**Comment by Palloxin** [comment]
It is indeed so.
On landscape mode, the "height" of the phone becomes the width. So it depends on the device screen size.
1. The settings are not scrollable so when on landscape mode one can't see all the sub-sections (in the video i can only see the first three) due to the small screen.
2. The "reader" sub-section is unexplorable due to the same problem, screen height too little when on landscape mode.
Could you reopen it?
