### ISSUE TITLE
Entry interface bug if switched between landscape and portrait mode

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#883]
### Steps to reproduce

1. Open an entry
2. Switch to landscape mode, wait 3 sec
3. Switch to portrait mode

### Expected behavior

Interface not blocked and expected normal behaviour

### Actual behavior

https://github.com/LNReader/lnreader/assets/75091899/ebe0a066-b056-40c0-a469-1f091f688047

### LNReader version

1.1.18

### Android version

Android 8

### Device

Huawei p8 lite 2017

### Other details

Once the bug in "actual behaviour" is triggered to exit that, one needs to restart the app

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.18](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
Not able to reproduce this. Could be a device specific issue. 

https://github.com/LNReader/lnreader/assets/57822170/10f125a4-7bca-4695-9e5f-6091ed1a6b39
