### ISSUE TITLE
Logic flaw in the chapter progress bar

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#884]
### Steps to reproduce

1. Inject this js  (copy, paste)
```js
chapter = document.querySelector('chapter');
chapter.innerText = chapter.outerHTML 
```
2. Go to a chapter and open it
3. Move chapter progress using the chapter progress bar

Another way to show the logic flaw if you:
1. Empty your css
2. Set font size to 15 using Lnreader related setting
3. Go to a chapter, scroll until 50% read progress and exit it
4. Set font size to 30 using Lnreader related setting
5. Go to the chapter previously menzioned and watch the resumed read progress. It will be roughly 15%

### Expected behavior

Precise movement with the progress bar when used to move in the chapter without "after-click-displacement"

### Actual behavior

https://github.com/LNReader/lnreader/assets/75091899/b0179035-875e-4484-b931-083277f68e2c

1. If I try to go to 50% the bar will show 65% so it is not precise
7. Sometimes when clicked on, it will not "teleport" to the progress indicated remaining unmoving (for example click on 70% zone but remaining on the bottom of the chapter)

### LNReader version

1.1.18

### Android version

Android 8

### Device

Huawei p8 lite 2017

### Other details

~~I am not sure why. Might be the fact that the content is the same but the space occupied by the paragraphs is not actually displayed.~~
I guess it is because the chapter progress logic is not actually saved as a %. 
In any case the chapter height scrollable doesnt match the chapter progress showed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.18](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Pheonix-Flames** [comment]
Can you guide me on customizing the reader with CSS? I'm encountering a novel where the "?" symbol appears randomly in the text.

**Comment by Pheonix-Flames** [comment]
![Screenshot_2024-02-05-16-14-08-05_3c1c179116822eec69c21805387f0489](https://github.com/LNReader/lnreader/assets/105352597/3669bb6e-ef82-4a05-9bbd-f2c64222f9cc)

**Comment by Palloxin** [comment]
Fixed in beta
