### ISSUE TITLE
Apk download

### ISSUE THREAD

**Issue by ValeriaRomana** [LNReader/lnreader#892]
I can't download the apk from releases

**Comment by cactusoftheday** [comment]
Like you can't download the file? Or when you try to install the apk, it says application couldn't be installed.

**Comment by ValeriaRomana** [comment]
> Like you can't download the file? Or when you try to install the apk, it says application couldn't be installed.

I can't download the file at all, not only lnreader but also tachiyomi it

**Comment by cactusoftheday** [comment]
Is it because you have some sort of antivirus installed on your phone preventing you? Maybe a screenshot or screen recording might help.

**Comment by ValeriaRomana** [comment]
> Is it because you have some sort of antivirus installed on your phone preventing you? Maybe a screenshot or screen recording might help.

Like this
![Screenshot_20240116_173900_Chrome.jpg](https://github.com/LNReader/lnreader/assets/153893710/e6b13462-ac78-4777-a1c5-dc54df69d2ec)

**Comment by rajarsheechatterjee** [comment]
> I can't download the file at all, not only lnreader but also tachiyomi

Closing since this doesn't seem like an app issue.
