### ISSUE TITLE
[Feature Request] TTS Improvements

### ISSUE THREAD

**Issue by BoredBrownBear** [LNReader/lnreader#90]
Thanks for including TTS support on your recent updates! Just a few more features related to TTS that are still not implemented, but is common in all readers with TTS support. 

1. Controls for speech rate / speed
2. Controls for seeking where to start, move forward, go back, etc.
3. Text highlighting for current sentence being read by TTS.

These features are found in most epub readers (i.e. Moon+ Reader) and the late Ranobe app.

**Comment by FireTner** [comment]
Oh, that'd be awesome I'd love that

**Comment by 0-shubham-0** [comment]
Yes please. I want this so much. Also, another feature: Start tts from the selected part/word/sentence.

**Comment by Dohko1** [comment]
This was requested almost a year ago, sadge.

**Comment by satvikpendem** [comment]
Is this still being worked on?

**Comment by nyagami** [comment]
3 was done in plugins branch

**Comment by satvikpendem** [comment]
Thanks, primarily looking for 1 and 2 as I listen to audiobooks mainly and doing that for LNs is kind of a pain, you have to download them manually.

**Comment by cactusoftheday** [comment]
I'm kinda interested in working on this. @satvikpendem could you perhaps clarify on what point 2 is? I know point 1 is just controlling the speed at which the voice goes at but what does point 2 mean?

**Comment by satvikpendem** [comment]
@cactusoftheday Check out how Moon+ Reader Pro does it, it starts the TTS at the top of the current page or when you highlight a piece of text. LNReader currently starts at the beginning of the chapter regardless of how far along you are in the chapter.

**Comment by nyagami** [comment]
implemented in 2.0 version

**Comment by nyagami** [comment]
you can try v2 beta version, or wait for it stable release
