### ISSUE TITLE
Empty chapter 

### ISSUE THREAD

**Issue by IchiharuYui221** [LNReader/lnreader#907]
### Steps to reproduce

1. I opened the source light novels updates
2. I searched the novel "The novice alchemist store."
3. It just says empty chapter.

### Expected behavior

I should be able to read the novels.

### Actual behavior

When I try to read a chapter it just shows empty chapter 

### LNReader version

1.1.18

### Android version

Android 12

### Device

Redmi 9 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.18](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Nithin-Johnson** [comment]
Open the source in webview and see if the chapter is empty or not.
As I see it, their site itself is broken.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
