### ISSUE TITLE
novelupdates fetch chapters broken

### ISSUE THREAD

**Issue by nguyd1** [LNReader/lnreader#909]
### Steps to reproduce

1. try to update or fetch any novel from novelupdates
2. notice the chapters are not updating

looks like the https://www.novelupdates.com/wp-admin/admin-ajax.php fetch api for parseNovelAndChapters function inside novelupdates.js is returning 0 as the body instead of the actual chapters 

### Expected behavior

novels should update chapters to latest

### Actual behavior

novels are not fetching chapters

### LNReader version

1.1.18

### Android version

Android 11

### Device

any

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.18](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment]
Login is now a requirement for Novel Updates I believe
Use webview to login, then exit the source and re enter, chapters should appear just fine

**Comment by nguyd1** [comment]
yea ur right just tried logging in and i can update fine now thanks!

**Comment by Batorian** [comment]
For me it worked for a bit after logging in. But now it duplicates all chapters from a novel and when I click on one to open it, it randomly opens a chapter from some random novel. When I close a chapter and open it again it is yet another random chapter.

**Comment by LazyHermitGal** [comment]
My problem with NovelUpdates is I can't bypass cloudflare protection even after using the webview. What to do?

**Comment by nguyd1** [comment]
> Screenrecorder-2024-01-26-22-46-28-534.mp4 
> My problem with NovelUpdates is I can't bypass cloudflare protection even after using the webview. What to do?

I ran into this issue once on novel updates and it went away after a few hours, if it still happens try to use data, reset cookies in the app settings, or reinstall the app

**Comment by nguyd1** [comment]
> For me it worked for a bit after logging in. But now it duplicates all chapters from a novel and when I click on one to open it, it randomly opens a chapter from some random novel. When I close a chapter and open it again it is yet another random chapter.

Haven't had this issue yet can u try a different novel? If it still happens then try a fresh install of the app

**Comment by combatwars** [comment]
> > For me it worked for a bit after logging in. But now it duplicates all chapters from a novel and when I click on one to open it, it randomly opens a chapter from some random novel. When I close a chapter and open it again it is yet another random chapter.
> 
> Haven't had this issue yet can u try a different novel? If it still happens then try a fresh install of the app

It seems to be an issue with NovelUpdates site. The redirect links that they use are broken so accessing the same link multiple times will redirect you to multiple sites.

**Comment by gwynsday** [comment]
hi! i've experienced this issue and did all what was said in this comment section. i unstalled and installed the app, and restored my backup. then logged in my novelupdates account. only some of the chapters came back but when i open it, it shows a chapter from a completely different novel, which i do not have in my library btw. is this an error regarding the app or the novelupdates extension? i checked the other novels i have from different source but they're completely fine tho.

**Comment by rajarsheechatterjee** [comment]
Closing this since it is a source issue.
