### ISSUE TITLE
problems in reading 

### ISSUE THREAD

**Issue by Feeyajabiargampang** [LNReader/lnreader#911]
### Steps to reproduce

There isn't any 

### Expected behavior

the application has been repaired 

### Actual behavior

I had to wait a while to read this ln on the Indonesian website 
![Screenshot_20240125-204753](https://github.com/LNReader/lnreader/assets/157714496/a93b68c7-aa26-443b-a28a-8a816410fe98)

### LNReader version

1.1.18

### Android version

10

### Device

Samsung 

### Other details

Hopefully the application will be repaired quickly to make it easier for readers to read 
Hopefully the admin will read it 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.18](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
