### ISSUE TITLE
Duplicate Chapters in Novel Updates

### ISSUE THREAD

**Issue by Chris-Boho** [LNReader/lnreader#912]
### Steps to reproduce

1. Log in to Novel Updates because of recent bugs/ changes.
2. Update library
3. Chapters are duplicated
![Screenshot_20240125-140201](https://github.com/LNReader/lnreader/assets/8922442/bc891652-dafc-4fa7-82ad-e8cec88ef59a)

### Expected behavior

In this image the last chapter should be 192, but afterwards it starts again from the beginning. On the novel updates page, it is not like that. 

### Actual behavior

Chapters are repeated. 

### LNReader version

1.1.18

### Android version

Android 11

### Device

Xperia 5 ii

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.18](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by combatwars** [comment]
While this is a bug, it isn't the bug you reported. Its not actually duplicating chapters. It's pulling the chapters from the wrong novel. All the duplicate chapters are from a different novel.

**Comment by Chris-Boho** [comment]
Moved to lnreader-sources issues.
