### ISSUE TITLE
Duplicate chapter after updating library

### ISSUE THREAD

**Issue by Lunaritia** [LNReader/lnreader#915]
### Steps to reproduce

1. Go to update section
2. Scroll down to update
3. Wait
4. Only latest chapter update will be shown

### Expected behavior

Only latest update will be shown

### Actual behavior

![Screenshot_20240127-004535](https://github.com/LNReader/lnreader/assets/157833665/44d639cb-4b71-48fd-8ebd-2d69e8441334)

![Screenshot_20240127-004551](https://github.com/LNReader/lnreader/assets/157833665/10787609-3385-4485-9d0c-8c65207e8b9b)

![Screenshot_20240127-005007](https://github.com/LNReader/lnreader/assets/157833665/96c0d460-c3a9-4d46-807c-3c94bfc03b4f)

The chapter I've read in the past got updated too (1st SS) and it got duplicated (2nd SS)

And the duplicated ones are considered as new entry, so I need to manually mark them as read so I won't miss which chapter I've read (3rd SS)

### LNReader version

1.1.18

### Android version

Android 13

### Device

Tecno POVA 5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.18](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
