### ISSUE TITLE
Bring back the CSS default settings of 1.1.18

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#922]
### Describe your suggested feature

As the title says.
Or fix it a bit.
Body has no padding.
nyagami, so.
1. Default padding can'be changed with CSS addressing "body" or "chapter" (One has to address p to do so)
```css
body,chapter {
padding: 0px !important;
}
```
 while before 1.1.19 one could change it using body.
Raw chapter text mode↓
![Screenshot_20240117-161812](https://github.com/LNReader/lnreader/assets/75091899/6f328a12-fd9a-4af0-a948-f06500d072dc)
Text not inside a tag
![IMG_20240117_155046](https://github.com/LNReader/lnreader/assets/75091899/666a42a0-6cb4-441d-9fd3-89256e0cd211)
I set the padding on body.
2. The default CSS of preview in Reader section of settings is different from the one applied to chapters (i can change padding using body on the preview but not on chapters)
3. Text that is not contained in a tag will have 0px padding. The same applies to the text of a chapter when one uses the "raw chapter text" script.
4. 

https://github.com/LNReader/lnreader/assets/75091899/b4cc27be-d13c-42ff-858c-6e7875242d73

Preview allows to scroll sideways? pls no. Idk if it happens on chapters too.

Is possible to revert some of the CSS parameters back to the 1.1.18? I know the change comes from the horizontal paging feature but i am sure there can be a balance between this request and the current feature.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> Default padding can'be changed with CSS addressing "body" or "chapter" (One has to address p to do so)

```css
body {
  padding: ANY_VALUE;
}
```

This is working as expected.

**Comment by Palloxin** [comment]
The first point is correctly wrong, ok.
I presented 3 more points for the issue which are still true.

![IMG_20240129_091659](https://github.com/LNReader/lnreader/assets/75091899/62eb51ab-629b-4161-9847-01bd5299f41a)
Can you reopen it?

**Comment by rajarsheechatterjee** [comment]
> 2. The default CSS of preview in Reader section of settings is different from the one applied to chapters (i can change padding using body on the preview but not on chapters)

Both can be changes using padding on `body`. 

> 3. Text that is not contained in a tag will have 0px padding. The same applies to the text of a chapter when one uses the "raw chapter text" script.

Everything is contained under `body` and all the chapter text is under `chapter` tag. 

> 4. Preview allows to scroll sideways? pls no. Idk if it happens on chapters too.

No, it wouldn't happen in Reader as there are CSS styles to prevent that.

**Comment by Palloxin** [comment]
> Both can be changes using padding on ``body``.
Yeah, i used this css and..

```css
body{
padding: 0.5em
}
```
preview:
![IMG_20240129_093332](https://github.com/LNReader/lnreader/assets/75091899/8cb0fbc6-eb04-4a42-8a33-63711ff1ac45)
reader:
![IMG_20240129_093316](https://github.com/LNReader/lnreader/assets/75091899/99d469cb-5121-4942-a0ee-f15c2a20d571)

the padding is different, the default css applied to preview and reading is not the same.
> Everything is contained under ``body`` and all the chapter text is under ``chapter`` tag.

Fine it is still into a tag, but the default padding is not applied to body. That is what I wanted to point, to bring back how it was in the 1.1.18 where the default padding was applied to body.

> No, it wouldn't happen in Reader as there are CSS styles to prevent that.

Yeah but it happens in the preview, which confirms the second point (``2.``)

Addition:
The css problem applies to the raw chapter text mode (using JS script).
In the 1.1.18 the css was applied there too with no problem but now it is bizare.
1em (body) applied while on raw chapter text is less than the normal mode. Idk it is just confusing and annoying.
Raw Chapter Text mode:
![IMG_20240129_095311](https://github.com/LNReader/lnreader/assets/75091899/9f1aacb8-67de-4611-a9f9-f766e04b1ac8)

Normal mode:
![IMG_20240129_095438](https://github.com/LNReader/lnreader/assets/75091899/a6bd1cce-1a65-40a2-9bae-ce2b3dc7c40b)

the same CSS applied but with different result. The deafult CSS in the 1.1.19 is just confusing for no reason. The one in 1.1.18 was fine. Now it is just complicated for no reason.

**Comment by rajarsheechatterjee** [comment]
> padding: 0.5em

`em` is a relative unit. It depends on the font-size. If the fontSizes are different in Preview and Reader the padding's would be different. 

> Fine it is still into a tag, but the default padding is not applied to body. That is what I wanted to point, to bring back how it was in the 1.1.18 where the default padding was applied to body.

Why should the app support it when it can be easily achieved by your custom CSS?

> Yeah but it happens in the preview, which confirms the second point (2.)

You can just add:

```css
html {
  word-wrap: break-word;
}
```

> The css problem applies to the raw chapter text mode (using JS script).
In the 1.1.18 the css was applied there too with no problem but now it is bizare.
1em (body) applied while on raw chapter text is less than the normal mode. Idk it is just confusing and annoying.

In the reader, now the padding is added to the elements inside the `chapter` tag. You can override it if you want:

```css
chapter > * {
  padding-left: 0;
  padding-right: 0;
}
```

> The deafult CSS in the 1.1.19 is just confusing for no reason. The one in 1.1.18 was fine. Now it is just complicated for no reason.

Not really.

**Comment by Palloxin** [comment]
> `em` is a relative unit. It depends on the font-size. If the fontSizes are different in Preview and Reader the padding's would be different.

Yeah, the font in both images is the same.
There was not such a problem on 1.1.18 ver.

> Why should the app support it when it can be easily achieved by your custom CSS?

The app supported it in the 1.1.18. Now the default padding is applied to the tags inside body. It is like having a shop to buy everything one needs(1.1.18k but now u have to go 8 different ones to buy all u need(1.1.19)
I had to just point body and that was it.
Also, the point of ``2.`` is that the reader and preview have different default CSS (preview has css A, reader has css B) in the 1.1.19. It was fine in the 1.1.18.

> You can just add:
> ```css
> html {
>   word-wrap: break-word;
> }
> ```
I want it the the default CSS of the preview. This reinforces the second point. The default CSS in the preview and reader is not the same which makes the job of the preview not an exact preview.

> In the reader, now the padding is added to the elements inside the `chapter` tag. You can override it if you want.

In the 1.1.18 is was easier to understand and manage. Better.

> Not really.

Of course it isn't for a developer, especially a LNReader one... :/
I am a normal user that can CSS a tiny tiny bit.
In the 1.1.18 it was more understandable. Now it is complicated (not for devs)
Just the example above with the em is confusing as hell. Again. there wasn't such a thing in the 1.1.18
Is there REALLY not a solution to keep the advantages of the 1.1.18 default CSS and the 1.1.19 one (the one that came to accomodate the horizontal paging)
Can there be two different default CSS for when the horizontal paging is turned on?(i am just throwing a random solution)
