### ISSUE TITLE
FreeWebNovel Source having Error 

### ISSUE THREAD

**Issue by Pheonix-Flames** [LNReader/lnreader#926]
### Steps to reproduce

1. Go to Browse
2. Search FreeWebNovel Source
3. Open FreeWenNovel Source
4. Search The Martial Unity in FreeWebNovel Source
5. Click on The Martial Unity Novel or Try Different novels

### Expected behavior

It should open the novel and display it's chapter and description etc.

### Actual behavior

It is given an error. Some novels are working and I am able to read them but some are showing error.
Error is shown in the picture below 👇
![Screenshot_2024-01-29-22-22-27-50_3c1c179116822eec69c21805387f0489](https://github.com/LNReader/lnreader/assets/105352597/4cdf24eb-2f31-4e38-8eff-3fe01d50228d)

### LNReader version

1.1.19

### Android version

Android 11

### Device

Realme 3 Pro 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.19](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).

Clear database in Advanced Settings and try again.

**Comment by Pheonix-Flames** [comment]
> > If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
> 
> Clear database in Advanced Settings and try again.

It doesn't work.

**Comment by Pheonix-Flames** [comment]
> > If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
> 
> Clear database in Advanced Settings and try again.

It doesn't work I have tried it
