### ISSUE TITLE
Fullscreen not re-applied properly in 1.1.19+

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#929]
### Steps to reproduce

1. Go to a novel scroll until.the bottom and click Next button.
--
If it doesnt work try going to a chapter from history section;

https://github.com/LNReader/lnreader/assets/75091899/fdb3558e-99f2-4e19-92bc-e6859bc7c2f0

### Expected behavior

The fullscreen is re-applied properly.
I say re-applied because even in the 1.1.18 the fullscreen is disabled for a moment and then re-applied upon chapter download, which is fine.

### Actual behavior

The fullscreen is not re-applied properly. U can see the android navigation bar in the video above on the chapter after I clicked "next".

### LNReader version

1.1.19

### Android version

A 8 miui 9

### Device

huawei p8 lite 2018

### Other details

Bug introduced with the 1.1.19 version.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.19](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Palloxin** [comment]
I just noticed that once I click "Next" button the reading settings are "summoned" for a split second (I slowed the video x25 times and framed it.
https://github.com/LNReader/lnreader/assets/75091899/ecfa058c-fd11-43c6-a5d9-d6db4a6cf9a6

**Comment by Palloxin** [comment]
I also noticed that the Next button in the current version can trigger the reader settings summoning.
I could replcate the effect of the bug with the normal < and > buttons by simply clicking twice on the novel AFTER i clicked < or > buttons.
Of course if I just click > < buttons withour the double click the the fullscreen will be fully applied.

https://github.com/LNReader/lnreader/assets/75091899/3050fad7-b0d5-4b79-9243-79b94b56348e

**Comment by Palloxin** [comment]
The ultimate bullet-proof proof.

https://github.com/LNReader/lnreader/assets/75091899/7d86ce08-4bce-4309-b022-c5f95248b2b5

IF i click "Next" with reader settings summoned, the next chapter will have a proper fullscreen.
If I don't, the bug occours.

**Comment by nyagami** [comment]
Cant reproduce in latest build

**Comment by Palloxin** [comment]
In beta it's not present. I didnt close the issue in case the main dev wanted to add some parts from stable, reintroducing the bug.

**Comment by nyagami** [comment]
I pretty sure development in main branch is end. At least in this org.
