### ISSUE TITLE
NovelUpdates chapter duplication

### ISSUE THREAD

**Issue by Batorian** [LNReader/lnreader#940]
Has anyone here some clue as to why NovelUpdates is just infinitely duplicating chapters inside a novel? Is it an issue with the app or with NovelUpdates itself? Has someone found a way to fix that?

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).

[Detailed Update on Novel Updates](https://discord.com/channels/835746409357246465/1202849673153355786/1202849673153355786).

**Comment by Pheonix-Flames** [comment]
> > If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
> 
> [Detailed Update on Novel Updates](https://discord.com/channels/835746409357246465/1202849673153355786/1202849673153355786).

Bro Fix FreeWebNovel Library Update issue
