### ISSUE TITLE
Updated chapters psorted in wrong order

### ISSUE THREAD

**Issue by Mexgaming950** [LNReader/lnreader#943]
### Steps to reproduce

1. Put novel in library 
2. Wait for an update 
3. Most updates are put in the wrong order

### Expected behavior

![Screenshot_20240206_204345_LNReader](https://github.com/LNReader/lnreader/assets/159219809/11429d88-3786-4494-afa1-54126d88dff0)
![Screenshot_20240206_204357_LNReader](https://github.com/LNReader/lnreader/assets/159219809/5b9f12c8-3238-4d65-8fc9-29375c4409c8)

### Actual behavior

![Screenshot_20240206_204643_LNReader](https://github.com/LNReader/lnreader/assets/159219809/d6b7cd17-a770-4491-9a18-f0be32b3c8b5)
![Screenshot_20240206_204622_LNReader](https://github.com/LNReader/lnreader/assets/159219809/359867e0-eb8f-4cd5-bd76-19163d1396c8)

### LNReader version

1.1.19

### Android version

Android 14

### Device

S6 light SM-P616

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.19](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Ppoollkkmmnn09** [comment]
https://github.com/LNReader/lnreader/assets/159732472/8e3f9b08-e6c7-47e6-8136-f38956366e00

**Comment by rajarsheechatterjee** [comment]
The current behaviour you're experiencing is expected, as each new chapter is inserted at the end. If the source adds or updates an older chapter later, it will indeed appear at the end. To address this in the beta version, we could implement a sorting option based on chapter numbers, provided the source website includes them.

**Comment by nyagami** [comment]
Fixed in v2 app by using chapter fetched order instead of id
