### ISSUE TITLE
Unable to add new tags with Edit Info

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#959]
### Steps to reproduce

https://github.com/LNReader/lnreader/assets/75091899/2e0cb209-5eba-405d-8034-ea42e693b59c

### Expected behavior

The tag is added.

### Actual behavior

No tag is added.

### LNReader version

1.1.19

### Android version

A8

### Device

huawei p8 lite 2017

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.19](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
It works as expected. Did you click submit on the keyboard?

https://github.com/LNReader/lnreader/assets/57822170/51fd7e98-957d-4312-818a-83c66c239446
