### ISSUE TITLE
Add Reset button to Edit Info

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#960]
### Describe your suggested feature

Reset button to reset all modified info(using edit info) of an entry.
There is no comfortable way to do so actually.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
you can turn on update novel metadata settings and update the novel

**Comment by Palloxin** [comment]
Yes I could, but I want it to be comfortable like on Tachiyomi.
![Uploading Screenshot_20240610-190413_1.jpg…]()
