### ISSUE TITLE
Turn on “Always show nav labels” option by default

### ISSUE THREAD

**Issue by Palloxin** [LNReader/lnreader#970]
### Describe your suggested feature

As the title says.
![IMG_20240224_110912](https://github.com/LNReader/lnreader/assets/75091899/852ff2b4-e6e7-4513-a941-f1803b4964b9)
This option turned on by default

### Why
1. Turned off, the nav bar response to actions is slower.
2. Users might take a while to figure out they can modify the nav bar labels
3. The first impression is important, so if it is faster => better.
4. An app should have by default options that give the best performance.
5. nyagami agrees with me

### Other details

Also adding a description below: " turning on this option might make the app slower"
Something like that. Users don't know

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/LNReader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
implemented in 2.0
