### ISSUE TITLE
Chapter is Empty 

### ISSUE THREAD

**Issue by LazyHermitGal** [LNReader/lnreader#979]
### Steps to reproduce

1. Open the chapter. It displayed a 'chapter is empty' error msg
2. Open webview. It works fine, the chapter is there.
3. I think the problem is on the specific website, Shanghai Fantasy? Two novel with the same problem.

https://github.com/LNReader/lnreader/assets/143852386/6547d13e-7ebc-43b0-a177-c9917abd60fe

https://github.com/LNReader/lnreader/assets/143852386/fade510c-5b7e-4b51-a8e6-a033b5c38ad5

### Expected behavior

The chapter opens up with no problem

### Actual behavior

Displayed error msg 'Chapter is Empty'

### LNReader version

Version 1.1.19

### Android version

Android 11

### Device

Xiaomi Mi 9T Pro 

### Other details

Its a redirection from novel updates.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.19](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
