### ISSUE TITLE
Swipe to next chapter sensitivity 

### ISSUE THREAD

**Issue by x-tj** [LNReader/lnreader#980]
### Steps to reproduce

While swiping during reading sometimes  You won't be able to draw a straight line using fingers

### Expected behavior

Chapter reading continues

### Actual behavior

Due to higher sensitivity of swipe to next chapter, the chapter accidentally changes to next one

### LNReader version

1.1.19

### Android version

13

### Device

Redmi Note 10 S

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.19](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nyagami** [comment]
Swipe sensitivity has been adjusted in v2 app.
Ideally I think it should be customized by users.
