### ISSUE TITLE
😭😡😭😡💢😭😭😭😭😭😭⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️❓❔❔❔❔❔❔❔❔❔❔❔❔❔❔❔🤔😔🤲❓😭😡😭😡😭😭😭😭😭

### ISSUE THREAD

**Issue by Ppoollkkmmnn09** [LNReader/lnreader#981]
![Screenshot_٢٠٢٤٠٢٢٨-٢٣١١٢٤.jpg](https://github.com/LNReader/lnreader/assets/159732472/4110ff9d-b95d-4ee0-973d-54e6f348c20c)

![Screenshot_٢٠٢٤٠٢٢٨-٢٣١١٥٣.jpg](https://github.com/LNReader/lnreader/assets/159732472/bb8565bb-ac80-4ce7-92ba-ca145e8b89a7)

😭😭😭😭😭😭😭😭😭😭💢💢💢😡😡😡😡😡😡😡😭😭😭😭😭⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️⁉️❓🙏

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).

**Comment by Ppoollkkmmnn09** [comment]
ارسل لي موقع التحديث في الروايه صور او مقطع ما اعرف تحدد الموقع الروايات حقتي ما بعرف اقرا صح ارسل الموقع كيف احدث صور موقع الروايات خرب علي الموقع كم له ما عرفت له اي حل
معي جوال يقرا لي بس ارسل لي مقطع اي مقطع واحد ارسل اي مقطع موقع يحارب  عيوني بطاريه كيف التحديث ارسلي لي مقطع تتعلم عليه

**Comment by Ppoollkkmmnn09** [comment]
❓❓❓❓❓⁉️⁉️⁉️⁉️😭😭

**Comment by Ppoollkkmmnn09** [comment]
https://github.com/LNReader/lnreader/assets/159732472/155ac36f-2ae7-4335-987f-9a4140d3a684

**Comment by error7404** [comment]
when the PR is merged HizoManga will work again on the beta version of the app (get the latest artifact from https://github.com/LNReader/lnreader/actions/workflows/build.yml, the latest one is this one [LNReader-r909.zip](https://github.com/LNReader/lnreader/actions/runs/8124336089/artifacts/1291873737)(for info on the beta look [here](https://github.com/LNReader/lnreader-preview/releases/tag/v2.0.0-alpha.0)))

**Comment by Ppoollkkmmnn09** [comment]
https://github.com/LNReader/lnreader/assets/159732472/155ac36f-2ae7-4335-987f-9a4140d3a684

**Comment by Ppoollkkmmnn09** [comment]
> when the PR is merged HizoManga will work again on the beta version of the app (get the latest artifact from https://github.com/LNReader/lnreader/actions/workflows/build.yml, the latest one is this one [LNReader-r909.zip](https://github.com/LNReader/lnreader/actions/runs/8124336089/artifacts/1291873737)(for info on the beta look [here](https://github.com/LNReader/lnreader-preview/releases/tag/v2.0.0-alpha.0)))

 


ارسل مقطع فيديو

**Comment by error7404** [comment]
wait for the PR [#819](https://github.com/LNReader/lnreader-sources/pull/819) to be merged

**Comment by Ppoollkkmmnn09** [comment]
Ok, I will wait. 🙏🙏😭

في الاثنين، ٤ مارس ٢٠٢٤ ٣:١٧ ص Justin COLLON ***@***.***> كتب:

**Comment by Ppoollkkmmnn09** [comment]
https://github.com/LNReader/lnreader/assets/159732472/745e21ce-e1c2-44f3-918a-b79c4c98b490

**Comment by Ppoollkkmmnn09** [comment]
https://github.com/LNReader/lnreader/assets/159732472/00380832-f6c7-4697-b812-6ad3276d8921
