### ISSUE TITLE
Issue in freewebnovel

### ISSUE THREAD

**Issue by TonyRaj02** [LNReader/lnreader#987]
### Steps to reproduce

There is an issue in freewebnovel extension when I try to update novels from that extension there is an error showing

### Expected behavior

There is an issue in freewebnovel extension when I try to update novels from that extension there is an error showing
![Screenshot_2024-03-05-15-30-00-36_3c1c179116822eec69c21805387f0489](https://github.com/LNReader/lnreader/assets/142190516/1fb219a0-d877-42b6-9aaf-e510d627b560)

### Actual behavior

There is an issue in freewebnovel extension when I try to update novels from that extension there is an error showing

### LNReader version

1.1.1.19

### Android version

11

### Device

Realme 10 pro 5g

### Other details

There is an issue in freewebnovel extension when I try to update novels from that extension there is an error showing
![Screenshot_2024-03-05-15-30-00-36_3c1c179116822eec69c21805387f0489](https://github.com/LNReader/lnreader/assets/142190516/5e6ded42-f83f-4730-b271-013ed5baa6ac)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.19](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
> If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
