### ISSUE TITLE
Authorization required

### ISSUE THREAD

**Issue by x7sony** [LNReader/lnreader#992]
### Steps to reproduce

When i download the app, when it ends or before, it says I need authorization

### Expected behavior

It download

### Actual behavior

When it ends or before, it says authorization requird

### LNReader version

1.1.19

### Android version

13

### Device

Samsung M12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[1.1.19](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment]
It's possible this might be related to an issue with GitHub or your browser. Try refreshing or using a different browser.
